### ISSUE TITLE
Title support

### ISSUE THREAD

**Issue by UzumakiYT** [SkriptLang/Skript#1213]
Maybe titles?

**Comment by ShaneBeee** [comment]
You can send titles and subtitles with skellett

**Comment by UzumakiYT** [comment]
are broken.

**Comment by ShaneBeee** [comment]
Im aware, but generally if theres an add-on that already includes something, they dont add it to Skript itself.

**Comment by HYPExMon5ter** [comment]
Skelletts titles aren’t broken? What Mc version are you on? You can also use mundosk and send titles using packets

**Comment by Pikachu920** [comment]
titles probably wont happen because spigot lacks a good api for them. complain to them

**Comment by ShaneBeee** [comment]
@Snow-Pyon  Ah... well the please ignore my response ;) and duly noted for the future. 
I was not aware of this. Clearly I was under the wrong impression.

**Comment by UzumakiYT** [comment]
still

**Comment by ShaneBeee** [comment]
> still

I don't think you need to "bump" this.
Snow set it to Lowest priority, which means things with a higher priority will be worked on first.
Skript is still having a few issues that is holding it from a proper stable release, and I think the team wants to focus more on fixing bugs rather than adding things that are already do-able thru add-ons right now!

**Comment by UzumakiYT** [comment]
there is no bump, I also know the priorities.
