### ISSUE TITLE
Bug with replace

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#1248]
Minecraft Version: PaperSpigot 1.12.2
Skript Version: I tried dev33 and dev35b and it works on both

Bugged Code:
```
command /bug:
	trigger:
		set {_test} to "hi"
		set {_testing} to "hello"

		replace all "hi" with "hola" in {_test} and {_testing}
		broadcast {_test} and {_testing}
```
Evidence: 
![image](https://user-images.githubusercontent.com/12315186/39832474-49eb3770-5395-11e8-9b6c-60b98611d3dc.png)

Working Code:
```
command /works:
	trigger:
		set {_test} to "hi"
		set {_testing} to "hello"

		replace all "hi" with "hola" in {_test}
		replace all "hi" with "hola" in {_testing}
		broadcast {_test} and {_testing}
```
Evidence: 
![image](https://user-images.githubusercontent.com/12315186/39832528-6d3ae2fc-5395-11e8-8eb0-25133a787f94.png)

Explanation:
Basically, if you specify more than 1 variable to replace something in it'll change the rest of the variables to the value of the first variable.

**Comment by TheBentoBox** [comment]
Sounds like it could cause notable problems when working with lists. Thanks for the clear report!

**Comment by HYPExMon5ter** [comment]
Yeah, it was hell to debug, took me like an hour and a half to figure out why my variables we're the same value.

**Comment by TheLimeGlass** [comment]
Ya it broke when Tuske did some updates a long time ago.

**Comment by Blueyescat** [comment]
@TheLimeGlass You added support for replacing in multiple texts in https://github.com/bensku/Skript/pull/177 and merged in deb20b. It didn't even work in dev20-dev23 ([It gave this error](https://gist.githubusercontent.com/Blueyescat/9827bf62740565a15042b633887d103a/raw/82e4694419926a49c2fa6add58f46699d017363a/gistfile1.txt)) i doubt the PR is even tried, because [you just added **`s`** to the syntaxes,](https://github.com/bensku/Skript/pull/177/files#diff-191a8ebc847551abb18e063d93012472R57) that also wrong. At least it didn't give that error since [Tuke's fixes](https://github.com/bensku/Skript/pull/373). So the bug exists since your PR.
