### ISSUE TITLE
Suggest some additional features for Skript

### ISSUE THREAD

**Issue by SiriuSKR** [SkriptLang/Skript#1291]
# Conditions
- [ ] plugin %string% is loaded
- [x] %chunk/world% is loaded

# Events
- [x] Locale change event (PlayerLocaleChangeEvent)
- [ ] Broadcast event (BroadcastMessageEvent) and recipient support for it (maybe? look at javadoc for recipient method)
- [x] Server ping event (ServerListPingEvent) with MOTD support
- [ ] Tab completion (TabCompleteEvent)
- [ ] Inventory drag event (InventoryDragEvent)
- [ ] Brew event (BrewEvent)
- [ ] Anvil prepare event (PrepareAnvilEvent)
- [ ] Horse jump event (HorseJumpEvent)
- [ ] Leash event (PlayerLeashEntityEvent)
- [ ] Unleash event (EntityUnleashEvent)
 
# Effects
- [ ] Load/unload plugins, worlds and chunks
- [x] Force player to chat
- [x] Show/hide player support
- [ ] Update inventory (maybe not, method is deprecated but has been forever so...?)
- [x] Send block change

# Expressions
- [x] hidden players of %players% (Player.Spigot#getHiddenPlayers)
- [x] locale of %players% (Player.Spigot#getLocale)
- [ ] New line

# Features
- [ ] Scoreboard support
- [ ] Bossbar support
- [ ] Firework support (firework types, launch effect, etc.)
- [ ] Inventory serialization

 It would be great to have the basic features of Bukkit available without addon. 😃

**Comment by Pikachu920** [comment]
I reformatted the issue and remove things that have already are in progress and/or already have an issue.

**Comment by SiriuSKR** [comment]
Thank you so much! @Pikachu920

**Comment by Blueyescat** [comment]
On fishing stuff ^^

**Comment by TheBentoBox** [comment]
Good shout, I removed loading/unloading scripts from this issue so #822 will remain the primary one for that request.

**Comment by TheBentoBox** [comment]
Spigot sound enum names are already supported in the play sound effect @TrademarkTM

**Comment by TheBentoBox** [comment]
The syntax would probably have to be pretty complicated to both be versatile and to read like English. I'm sure it could be improved but for starters, maybe something like this?

`send (title %text% [with subtitle %text%]|subtitle %text%) [with a %timespan% fade(-| )in][(,|and|with) [a] %timespan% (linger|stay)][(,|and|with) [a] %timespan% fade(-| )out] to %players%`

Title/subtitle should default to an empty string and and each of the timespans defaulting to one second. You'd need to convert the timespans to ticks since the `player#sendTitle` function accepts the durations as the number of ticks as an integer. 

If that works it would be versatile in how you could word it, all as pretty proper English. Would allow all of the following:
```
send title "Example" to all players
send subtitle "Just a subtitle" with a 3 second fade-out to player-argument
send title "Long example" with subtitle "Oh god" with a 99 second fade in, 3 second linger and a 1 second fade-out to all players
send title "Versatile fades!" with a 2 second stay and a 1 second fade-out to player's target
```

**Comment by HYPExMon5ter** [comment]
`(send|show) %players% title %string% [with subtitle %-string%] for %timespan% [with %-timespan% fade(-| )in (, | and) %-timespan% fade(-| )out]`?

**Comment by TheBentoBox** [comment]
I find the `for %timespan%` wording in title syntaxes a bit ambiguous since I don't think it's clear to the user that it indicates how long it should stay WITHOUT including the fades. If I was a new user that didn't know better I'd think the title should last that long in total, including the fades.

**Comment by Blueyescat** [comment]
Why there is no an effect to send only subtitle? Yeah, make the title blank in Java side.

**Comment by TrademarkTM** [comment]
`(send|display|show) %players% title %string% [with subtitle %string%] for %timespan%[( with|, )] %integer% [fade(-| )in](, | and) %integer% [fade(-| )out]`
As Blueyescat said, it's a pretty big effect to use `timespan` three times.
What about this? One timespan, fade-in and fade-out in ticks.

**Comment by Blueyescat** [comment]
Lol i don't mean that, they all must be timespans but ```vb
for %timespan%[( with|, )] %timespan% [fade(-| )in](, | and) %timespan% [fade(-| )out]```

"for" is used for the general timespan.

**Comment by Snow-Pyon** [comment]
Not a single syntax convinced me sadly, this is mainly why I didn't implement it before.  And integers won't work since it isn't concise and it isn't really user-friendly.

I'll think about it more thought and see if I can come up with a syntax based off the suggested ones. Also, to not fill this issue with rather unrelated comments, further discussion can be done at #random in Skript-chat (just mention me if you get a suggestion).

**Comment by Pikachu920** [comment]
Visibility and force chat are both addressed by pending PRs (#1302 and #1289, respectively)

**Comment by TrademarkTM** [comment]
Syntaxes for actionbars and titles:
```
(send|show|display) action[ ]bar %text% to %players%

(send|show|display) title %text%[( with | and |, )sub[ ]title %text%] for %timespan% to %players% [(with|and) fade[( |-)]in %timespan%( and |, ) fade[( |-)]out %timespan%]
```
I think it's more user-friendly now. Not sure if it's better to use fade-in and fade-out in the end or middle of the syntax.

**Comment by FranKusmiruk** [comment]
Closing this issue since as I've said in #3269, 1 feature request per issue is preferable and the feature set being requested is just too much of a general thing with little detail on them.
