### ISSUE TITLE
Skript Issue - Cursor Slot Expressions - Ver: 2.2-dev36

### ISSUE THREAD

**Issue by olivervincent** [SkriptLang/Skript#1312]
Hello all.

Following is a issue with skripts cursor slot expression:

```
on inventory click:
	if player's cursor slot is nether_star:
		send "1"
		if the lore of player's cursor slot contains coloured "&7Whatever":
			if clicked item is iron pickaxe:
```

It returns "cursor slot of olivervincent"

If i did:

`send "%clicked cursor%"`

It returns "nether_star".

But the code does not registrer im clicking with a nether star in my inventory, it doesn send the "1".

I also posted this in a thread on skunity forums: https://forums.skunity.com/threads/skript-issue-cursor-slot-expressions.7462/

**Comment by bensku** [comment]
The different string representation is intentional. If you're asking for a slot, you'll get a slot. If you are not doing that, you get an item (or a slot that looks like an item).

That being said, can someone verify that item equality check is not working? That would be a serious issue.

**Comment by olivervincent** [comment]
I pm’ed @LimeGlass about it, and he Said its a skript issue, and i should post it on the skunity forums and tag him in it, so he could inform the other devs about it.

**Comment by Blueyescat** [comment]
Your code totally works for me with Skript 2.2-dev36 and PaperSpigot 1.12.2.

**Comment by jaylawl** [comment]
@bensku i believe the op's issue is that it's somewhat confusing, relative to what you do with skript otherwise. take for instance stuff like 'player's tool'. that also returns the item - and i can only assume that's why the op (and me too) did expect these slot expressions to return items.

```on inventory click:
    set {_item} to event-player's cursor slot
    broadcast "%event-player's cursor slot%" #works, but not sure what that could ever be used for
    broadcast "%event-player's cursor slot's item%" #this doesn't even parse
    broadcast "%{_item}%"``` #this returns the item just fine

**Comment by TheBentoBox** [comment]
Actually, `player's tool` technically returns a referenceable slot as well. It just automatically converts to an item (i.e. returns the item in the slot) in the correct situations.

**Comment by jaylawl** [comment]
@TheBentoBox anyway, the way that one works, for example, is highly intuitive. So should this stuff be.

**Comment by jaylawl** [comment]
related issue:

```
loop all players:
    loop items of loop-player's inventory:
        broadcast "%loop-value%"
```

this totally returns "inventory slot # of player" for each respective item

**Comment by Snow-Pyon** [comment]
I'll clarify something, this isn't a bug but rather an awkward way to display the slots as strings but it isn't a bug. You can use `type of <slot>` meanwhile.

But I do agree with everyone that this isn't very intuitive nor helpful at all. I'd rather have a format like `<item> at <slot number> of <holder>` for inventory slots and `<item> in <holder>` for special slots (i.e. item frames).

**Comment by Blueyescat** [comment]
I think the current string forms are fine but "inventory" in "inventory slot" is unnecessary. Also still there is no `item in slot` expression..

**Comment by bensku** [comment]
Currently, it is not that bad, assuming it is not bugged. If you are explicitly requesting a slot, you get a slot. If you are not - for example, leave 'slot' out in an expression where it is optional - you're getting the item. Or, at least, it will convert to string as item.

**Comment by Snow-Pyon** [comment]
@Blueyescat there won't be either. Slots can do everything an item does. Adding such expression would be a bad workaround for a rather experimental implementation. 

@bensku I'd rather it return the item in the string representation, the only *useful* information in the current string form is the slot index which can be get via an expression so it is actually useless, I doubt users expect the index of a slot at this point (which by the way, completely defeats the fact that slots are not just a number as many people commented). It is also inconsistent with the tool expression which has an *special* behaviour to avoid people complaining about it not working as it did since it was implemented, when it is essentially the same thing as any other expression that returns an slot.

**Comment by Blueyescat** [comment]
@Snow-Pyon The expression won't change something or is not a workaround, just some readability. Better than "type of" when you want to print the item.

**Comment by bensku** [comment]
All slots used to be converted to strings based on their items. As result, writing code that operated on inventory click events was *very* annoying (what exactly was clicked when event-slot is "air"?).

All expressions that do not contain 'slot' in syntax should use their item's string representation. Is this still not the case? I may have some bug fixes to do for the next release.

For slots being just numbers, well... Do the numbers remember their inventory? Can you *set* numbers to items, *clear* them or *save* their contents to variables? All without ugly code such as
```
set event-slot of opened inventory of player to {item]
```
That is just *ugly*. To make things more fun, not all slots are necessarily in inventories.
