### ISSUE TITLE
lore error

### ISSUE THREAD

**Issue by xbxymax** [SkriptLang/Skript#1318]
```vb
on load:
    {test} = ice with lore "test lore"

    set {test}'s lore to "new test" # error
    set line 1 of {test}'s lore to "new test" # works
```

**Comment by TheBentoBox** [comment]
You need to provide more info; what version of Skript are you using? What version is your server? What is the error that you're getting?

**Comment by TheLimeGlass** [comment]
`%itemstack% with lore %strings%` - Returns an ItemStack

This is a syntax from SkQuery and not Skript. The error will be that it can't understand the expression. This should be added though.

**Comment by TheLimeGlass** [comment]
Related #1309

**Comment by TheBentoBox** [comment]
I'm putting both bug and enhancement: bug because apparently some changes broke add-ons and lore (relates #1309 as Lime pointed out) and enhancement for a new item with lore expression. This is important if it broke add-ons and variable lore.

**Comment by Nicofisi** [comment]
That's issue in OP is because of a conflict with skQuery.
The following scripts all work as expected, I have tested it a few minutes ago:
```vb
command /hi:
    trigger:
        set {_test} to ice
        set the lore of {_test} to "abc 1"
        give {_test} to player
```
```vb
command /hi:
    trigger:
        set {_test} to ice
        set the lore of {_test} to "abc 1"
        set line 1 of {_test}'s lore to "abc 2"
        give {_test} to player
```
```vb
command /hi:
    trigger:
        set {_test} to ice
        set the lore of {_test} to "abc 1"
        set line 1 of {_test}'s lore to "abc 2"
        set {_test}'s lore to "abc 3"
        give {_test} to player
```

---
@TheLimeGlass 
> `%itemstacks% with lore[s] %strings%` should be added to Skript itself though

true, I'm updating the lore code, I'll add it if I remember
> Also there is a bug in lores where you can't set the lore of an item stored in a variable

https://github.com/SkriptLang/Skript/issues/1287#issuecomment-406381386

> The inventory click item not being changeable has been a bug for a long time.

that's a different issue
> Also one of the newer Skript versions broke this simple expression from working in SkQuery, so that could also be another reasoning of this issue.
Somehow someone fucked the whole lore system up recently (Somewhere in the past 5 versions).

no idea about this but not really important because of all the above. skQuery has been abandoned for a long time so you can't really expect it to work, and if you are interested in maintaining it while keeping support for the latest Skript versions you should just remove the whole [ExprLore](https://github.com/SkriptLegacy/skquery/blob/master/src/main/java/com/w00tmast3r/skquery/elements/expressions/ExprLore.java) class
> Only thing that works all the time is by setting the lore by line set line 1 of {test}'s lore to "new test"

or not using skQuery

---

Keeping the enhancement label to track the `%itemstacks% with lore[s] %strings%`
