### ISSUE TITLE
Better syntax for copying a slot's item

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1320]
SKRIPT: Skript v2.2-dev36

Hi all,
I have this command:
Code (Skript):

```
command /looptest:
    trigger:
        set {_temp} to player's tool
        set {_name} to {_temp}'s display name
        replace all "%%player%%" with "%player%" in {_name}
        set display name of {_temp} to {_name}
        give player {_temp}
```
 

This will also change the display name of the original's tool in player's hand but it should only change the name of the "copied" tool. What is wrong here? A Skript bug?

With the first line "set {_temp} to player's tool" it should make a copy of the player's tool, right?
If not, how would I store the complete item in a variable?

**Comment by TheBentoBox** [comment]
It is supposed to work that way as far as I'm aware. Getting their tool returns it as a slot so the variable acts as a reference to the slot. There are a few situations where this is the case.

To make an exact copy of the player's tool in vanilla Skript, I believe you could instead just do `set {_temp} to (item amount of player's tool) of player's tool`. There might be a better way to forcibly store a copy that I'm not aware of since that syntax is a little messy.

**Comment by bensku** [comment]
This is correct behaviour. Slots are not copied, but that only means that if you *set* <code>temp</code> to something, the original tool will not change. Creating copy of an item should get better syntax available in future.

**Comment by TheBentoBox** [comment]
Updated title to better match the desired functionality.

**Comment by AyhamAl-Ali** [comment]
Tested using Skript 2.6.1 and the code seems to work as it should be, the original item stays untouched, probably fixed/improved somewhere in time
