### ISSUE TITLE
Feature Request: Action Bar

### ISSUE THREAD

**Issue by JustDylan23** [SkriptLang/Skript#1351]
I am basicly asking for an action bar api for skript, I found a good example here [https://github.com/ConnorLinfoot/ActionBarAPI](url)
skellett has it, but I'd like to see this in vanilla

**Comment by TheBentoBox** [comment]
Makes sense. Vanilla MC will have a command to send action bars to the player in 1.13 so hopefully Spigot also gets better support for it.

**Comment by jaylawl** [comment]
vanilla minecraft can already do this in 1.12 using `minecraft:title <player> <actionbar> <raw json yada yada>`

**Comment by Pikachu920** [comment]
Most enhancements are labelled low(est) priority just because they are much less important than fixing the bugs Skript currently has. Pretty much nothing besides bugs ever gets a priority higher than low, Anyways, about this issue: action bars aren't supported because spigot didn't support action bars until some recent version (1.11 or maybe 1.10) so if skript added support we would need to do one of three things:
1. use an action bar api for old versions like the one linked in the OP. unfortunately, most of these are badly coded and no longer maintained.

2. use nms to backport the features to older versions. this is basically a non-option because nms code is not allowed in skript

3. leave it only compatible with versions the api exists on. this is the most likely option but is annoying for people below that version especially since this fork aims to support 1.9+.

**Comment by Blueyescat** [comment]
Who cares about 1.9-1.11, nobody should use them.

**Comment by bensku** [comment]
It is acceptable for Skript not to support action bars on Spigot versions that do not support them. If people cared enough, they could backport those APIs; no idea about this one, but I've seen at least one 1.8 Spigot fork with a lot of improvements over 'vanilla' Spigot of that time.
