### ISSUE TITLE
Skript (not) in other languages

### ISSUE THREAD

**Issue by Nicofisi** [SkriptLang/Skript#1359]
I remember a few months ago on Discord we had a brief discussion about the support of multiple languages in Skript, so I thought I'd bring the issue up again here, once for good. Skript currently "supports" English and German. 

I'm not a German speaker, but I don't need to know the language to be able to quite surely tell that the support for it in Skript is very poor. None of the German aliases have been updated within the last few years. I have no idea how many people actually wanted the German support. Perhaps no one asked for it, and it was only a vision of Njol to add it since German was his native language. Nevertheless, apparently that guy was the only person who really contributed to keeping them kind of working. 

I have no clue whether we have any German people active here, but I'm pretty sure no one even considers updating it. That would require moving almost every string ever shown to users to aliases files. 

All major programming languages provide errors only in English - translating every new string *in a 
**programming language*** to even __a few__ languages would be a tedious job and would require a bunch of *very* regular contributors.. regular for the next few years. I don't think that sounds appealing if you consider how little people would benefit from this.

Actually, I forgot to mention the most important point - how do any translations make sense when the syntax, the actual language, can only be written in English?

---

Do you agree that most of the code related to the localization of Skript (= only German at the moment) should be removed? Not the whole aliases, obviously, but anything that was added with the sole purpose of supporting German.

If we reach a consensus here within the next few days, I'm willing to work on a PR :)

**Comment by iDarkyy** [comment]
Agreed.

**Comment by Blueyescat** [comment]
https://bstats.org/plugin/bukkit/Skript
![image](https://user-images.githubusercontent.com/19474570/42446023-9d8c6ba2-837d-11e8-9320-4e66d74611ff.png)
xD

I agree it should get removed.

**Comment by jaylawl** [comment]
Just a hunch here, but i believe that hint of german is in there because the original author of Skript, njol, spoke german, among other languages.

I'm german, but i haven't even ever considered programming anything (in any language) in german, or any other language for that matter. Remove dat shit (if it's beneficial to plugin performance).

**Comment by TheBentoBox** [comment]
I'm not sure if it affects performance but I definitely agree either way. If it's not going to be maintained in the first place then there's very little point in keeping it even if there WAS a more notable number of people using it (because of course if it's poorly implemented it's not doing its job). The fact that less than 1 in 200 people are using the alternative languages is just the nail in the coffin IMO.

**Comment by bensku** [comment]
We should improve support for localization, not drop it. Not because people use Skript in German, but because it could be very useful to, for example, solve syntax conflicts. If this was done in script-level, it would even be possible to shorten some very common syntaxes.

My suggestion is that until someone actually wants to do this, we're not touching localization stuff. That, or if localization breaks other things and fixing it would be too time-consuming.
