### ISSUE TITLE
Please help 1st time use using skript errors in console

### ISSUE THREAD

**Issue by axemwa** [SkriptLang/Skript#1371]
How do I fix these errors new to skript, thankyou.
https://pastebin.com/J1zUsEAA
Scripts: https://www.dropbox.com/s/yj7vcg4dbeuqmqa/scripts.zip?dl=0

**Comment by TPGamesNL** [comment]
You need SkQuery (https://www.spigotmc.org/resources/unofficial-skquery-fork-1-6-1-12.36631/) for the format effect, but next time if you have an error like this post it [here](https://forums.skunity.com/forums/skript/)

**Comment by axemwa** [comment]
I already have skQuery still not working :(

**Comment by Blueyescat** [comment]
Don't use that script, because uses skQuery for GUIs. It doesn't work as it shouldn't :)

**Comment by axemwa** [comment]
Sorry didn't quite understand what you meant I'm new to skript. Don't use what script, clearlagg or enchanted boots?

**Comment by Blueyescat** [comment]
The script that uses the format slot codes

**Comment by axemwa** [comment]
Errors are gone thanx!

**Comment by Pikachu920** [comment]
The issue tracker is for reporting bugs and feature requests

**Comment by Pikachu920** [comment]
in this context, issues means issues with Skript the plugin

**Comment by axemwa** [comment]
I understand but I stand by what I've stated I appreciate your help either way thankyou.

**Comment by Nicofisi** [comment]
@axemwa just please don't do this again lol. Join [skUnity's Discord](https://discord.gg/0l3WlzBPKX7WNjkf) or [Skript Chat (Discord)](https://discord.gg/V4qFVnh) or [skUnity Forums](https://forums.skunity.com/forums/) next time. Also I have no idea what most of other plugins do, but definitely most of other non-plugin projects don't use the issue tracker for reporting questions either. Have a nice day though :)

**Comment by axemwa** [comment]
@Nicofisi No! Like I said if I have to go to another site to make a report I won't that's just rediculous, I just won't use the plugin anymore. And yes most other plugins do use the tracker not their own site and I can actually prove it but can't be bothered, all the plugins I use I report issues on the tracker and authors are happy to help!

**Comment by Nicofisi** [comment]
Well, I scrolled through a few of your other issues in different repositories and they look like actual legit issues with the plugins to me. Remember though that Skript is a scripting/programming language, and I know no other language on whose issue tracker help requests related to the usage of the language are welcome. Every language has a separate forum/gitter chat/discord/something for that :)

This issue tracker is for reporting problems with the language, your issue is not a problem with the language nor a feature request, it's a user error. And like I linked you to, there are plenty of places where you can get help after literally registering within 20 seconds :) It would take you way less time to register than to actually reply to me that you won't register.. 

In the places that I linked you to, there is way more active people, also including the people who are here, and you would receive help within 1-5 minutes. Please reconsider your decision about leaving or at least don't be like some people who start being like "omg skript community is so toxic" everywhere lmao. Again, have a nice day.

Can this be locked?

**Comment by axemwa** [comment]
Nah it **does** take too long I already have way too many sites that I'm registered on and I don't really use skript anyway, it was only the 1 script file, thanks anyway
