### ISSUE TITLE
1.13 support

### ISSUE THREAD

**Issue by bensku** [SkriptLang/Skript#1395]
See also #1385 - new features we can add to Skript once it runs on 1.13.

New aliases are still work in progress, but not *that* incomplete. Updating Java code ready for 1.13 has also started.

- [x] Update new aliases system for 1.13
- [x] Purge references to Material entries from Java code, use aliases instead for cross-version compatibility
- [x] Remove the few usages of numeric ids outside of aliases system
- [x] Update biome mappings
- [x] Update other things that used to rely on deprecated APIs (IDK what exactly)
- [x] Update click events to work correctly with Mojang's bug fix
- [x] Make variables containing items from 1.12 to be correctly migrated

... and while doing these things, support for 1.9+ must kept. I expect that to be quite annoying.

**Comment by TheBentoBox** [comment]
I said this in Discord after my testing but just so it's here for conversation and ease of access: the vanilla change to click handling in 1.13 is that blocks now ALWAYS override your off hand if they're in your main hand. Items still fall through based on context (if you are full on hunger with food in your main hand, it will attempt to use your off hand), but if you have a block in your main hand your off hand will not be used, even when right clicking in a situation where the block can't be placed.

This is good because by far the largest difficulties in programmatically determining which hand was used in a click event were surrounding blocks since there are complicated and specific situations which determined if the block was placed or not. With items in the main hand it's much more straightforward to tell if they're going to be used when compared to blocks. And to aid with that, here's a list of useable items and the situations in which their event will succeed when in the main hand to aid in updating the determining code (which is in `checkUseOffHand` in EvtClick). Some shout if you notice one I missed or any mistake:

- **Bow**: if the player has any type of arrow (normal, spectral, tipped)
- **Empty bucket**: if they click on water or lava... I guess? Doesn't fire a click event, bit weird. [PlayerBucketEvent](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerBucketEvent.html) may help.
- **Water bucket**: if `isBlockInHand()` on the interact event is true OR (1.13) if they're right clicking on any fish (can carry fish in water buckets in 1.13)
- **Lava bucket, Flint and Steel, OR (1.13) Bucket of Fish**: if `isBlockInHand()` on the interact event is true (I assume placing the liquid/fire counts as a block place event, too? That'd make it easier but not sure if that works here)
- **All hoes**: when clicking grass, dirt, grass paths, OR coarse dirt (turns the latter back into dirt)
- **Leash**: when clicking on a leashable entity (may need to be determined manually). [PlayerLeashEntityEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/PlayerLeashEntityEvent.html) may help.
- **Shears**: when right clicking a sheep with wool (`!e.isSheared()`), snow golem that still has its pumpkin, (`!e.isDerp()`), or a mooshroom.
- **Ender pearl OR shield**: if it's not on cooldown (`!player.hasCooldown(material)`)
- **Spawn egg**: if they clicked a block
- **Any food**: when hungry
- **Trident**: if it has Riptide, only when it's raining or the player is in water. Otherwise, always.
- **Egg, splash potion, snowball, fishing rod, eye of ender, book and quill, written book, empty map, both golden apples**: always

You'll still need special checks like seeing if they clicked an interactable block while not sneaking, but there should be less bugs and falsely reported events as far as which hand performed the action.

**Comment by Pikachu920** [comment]
so do the new aliases have a way to get a Material from an alias, then?

**Comment by bensku** [comment]
Yes.

**Comment by jaylawl** [comment]
Any ways how non-java-coders could pitch in?

**Comment by Pikachu920** [comment]
yes, contribute to the skript-aliases repo. it is the main thing holding aliases back right now, there's a bit of a tutorial in the read me over there

**Comment by TheIntelloBox** [comment]
1.13 builds are ready. :D https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-development-builds.328883/

**Comment by melinstagibson** [comment]
are you sure about the 1.9+ support you want to keep?
might sound a bit selfish but i kinda agree with a support-latest-version-only-policy which some devs have.

i mean you can always download an earlier version.
just in case it holds you back too much, i wouldnt mind postponing/scrapping backwards compatibility ^^

**Comment by Nicofisi** [comment]
This might be worth checking (in general and specifically for 1.13) - https://github.com/SkriptLang/Skript/blob/80c6f13e4d43f17e7f668867906806b39cd6e802/src/main/java/ch/njol/skript/expressions/ExprRemainingAir.java#L101-L106
20 ticks as a default amount of air? it's 1 second

**Comment by bensku** [comment]
20 air is still default state as far as I know. Minecraft just doesn't reset to default immediately when exiting water, as it used to do.

**Comment by Nicofisi** [comment]
@bensku but wouldn't it mean that one has only 1 second of air after diving into the water before they start getting damaged? Sorry if I misunderstand what this value is

**Comment by bensku** [comment]
Oh. Yeah, that is correct. I had thought it was represented in same way as player health, but that is of course a mistake.

**Comment by TheLimeGlass** [comment]
No that's how it was back in older versions. I'm pretty sure the air has been changed to be longer and also when you gain air it's delayed. Rather than gaining all air back when you get air, it takes like 5 ticks to gain each air bubble.

**Comment by bensku** [comment]
Skript now compiles against 1.13. Still needs some work to get it running.

**Comment by jaylawl** [comment]
@xGlenor @Nicofisi already explained this to you in the other issue that you opened.

**Comment by xGlenor** [comment]
forgot, I'm sorry

**Comment by Nuker321** [comment]
oo.. When will the stable version be on 1.13?

**Comment by Snow-Pyon** [comment]
@Nuker321 there isn't even a stable version of Spigot for 1.13 yet. Please be patient and just wait for it.

**Comment by Pikachu920** [comment]
@Nuker321 it's not like there is a timeline for these things -- all the devs work on the things that interest them when they have time and want to.

**Comment by bensku** [comment]
There are currently no stable versions of Skript out for Minecraft 1.9 or later. We do have one in plans, but I really have no idea how soon.

First *usable* 1.13 release will be not marked as stable, but for some users it might be good enough.

**Comment by xGlenor** [comment]
@bensku  when it will be available

**Comment by Blueyescat** [comment]
he can't see the future

**Comment by TheBentoBox** [comment]
Be patient. Stop asking. When it's ready for testing, you'll see the release.

**Comment by redbrain1014** [comment]
Hello. I'm new to GitHub. Cannot code Java, but can try to do some other things. How can I help?

**Comment by redbrain1014** [comment]
Also, you might want to check out #1385 as it seems like it has some support for 1.13 information as well.

**Comment by jaylawl** [comment]
@redbrain1014 You can propably help here: https://github.com/SkriptLang/skript-aliases

**Comment by melinstagibson** [comment]
Soooo it has been nearly a month now since the "compiles against 1.13" comment and while im aware i should be patient i cant really afford to wait longer.
Can i pay someone to resolve this? A non-backwardscompatible 1.13 version would already be fine, no need to import variables either. Any volunteers? rather ask here first before i move on and deal with configuring replacements

**Comment by jaylawl** [comment]
@melinstagibson the best person you could pay to move along development is @bensku (logically thinking, i'm not sure whether he accepts donations like that though). Porting Skript to 1.13 is a massive undertaking and if you'd pay an outsider ... i'd assume there'd be a LOT of working hours to pay for.

**Comment by bensku** [comment]
Spigot does not have a stable 1.13 release, and even Minecraft 1.13 is quite unstable (1.13.1 is better, apparently). Skript or no, hosting a public 1.13 server that is not a protocol hack right now would be a gamble.

That being said, Skript runs on 1.13, and all the available aliases are enabled without errors. And alpha release will likely be published once transportation category is ready too. Using that on a public server would be - in theory - possible, provided that you really do not care about what happens to your variables and take frequent backups.

**Comment by redbrain1014** [comment]
Hello. I'm new to GitHub. Cannot code Java, but can try to do some other things. Is there anything left I can do?
Also, you might want to see issue #1385 ...

**Comment by bensku** [comment]
Everything should be somewhat functional now, but the result is quite buggy. I'll spend a few days trying to fix the worst of it, and then probably release something.

**Comment by bensku** [comment]
Tracking additional functionality at #1385
