### ISSUE TITLE
Kicking a player causes 'handleDisconnection() called twice'

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#1423]
version : dev-35b BUT problem not see in newer release note.

The kick effect cause the trigger of "on quit" twice

and in some case we can see in console : ...WARN] handleDisconnection() called twice

**Comment by Pikachu920** [comment]
iirc this was a spigot issue

**Comment by TheLimeGlass** [comment]
Test without SkQuery 3.5.2

**Comment by Matocolotoe** [comment]
I have SkQuery 3.6.0 and I use it for several things, can't it just be fixed ? :/

**Comment by Snow-Pyon** [comment]
@Matocolotoe if it happens to be skQuery, it can't be fixed on our end.

**Comment by Matocolotoe** [comment]
@Snow-Pyon 
Tested with skQueryLime 3.6.0, the issue still happens : when a player is kicked, every code executed after an "on quit" event is executed 2 times

**Comment by Pikachu920** [comment]
you need to test without, not with. also we don't accept issue reports from old versions of skript or 1.8

**Comment by Matocolotoe** [comment]
actually i tested without but if you want

**Comment by Nicofisi** [comment]
Please list all the plugins you have along with the server version. Also, what doesn't work for you in the latest release?

**Comment by Pikachu920** [comment]
your original comment said you tested with it 😛

**Comment by Matocolotoe** [comment]
Plugins (33): §aSkript§f, §aGameBox§f, §aSkQuery§f, §aNametagEdit§f, §aExtrasSK§f, §aBattleship§f, §aGemCrush§f, §aCitizens§f, §aFastAsyncWorldEdit§f, §aMaxBans§f, §aWildSkript§f, §aKizunaAI§f, §aOpGuard§f, §aUltimateTNT§f, §aPermissionsEx§f, §aViaVersion§f, §aMP-GameBundle§f, §aAntiBot-Ultra§f, §aWorldEdit§f, §a2048§f, §aPlotSquared§f, §aProtocolLib§f, §aMultiverse-Core§f, §aLibsDisguises§f, §aSkellett§f, §aSkinsRestorer§f, §askRayFall§f, §aAttributeHider§f, §aCustomPayloadFixer§f, §aArmorStandTools§f, §aGadgetsMenu§f, §aAuthMe§f, §aTuSKe

Server version : Spigot 1.8.8
(And in the latest release a lot of things do not work, like text variables who are not recognized as some, it's hard to explain, so I must use Skript2.2dev25 because I won't update my server to 1.9)

**Comment by Blueyescat** [comment]
@Matocolotoe You can use dev37c on 1.8 and it will work but not officially supported. Also delete WildSkript and ExtrasSK because they are dead and old addons so you shouldn't use them anytime.

**Comment by Matocolotoe** [comment]
But I use these addons for important things
Can't it just be fixed properly ? I don't understand why, sorry if i'm annoying :/

**Comment by Pikachu920** [comment]
we can't fix something that isn't broken in our codebase

**Comment by Matocolotoe** [comment]
so what's the addon that causes this ?
i tried without skQueryLime

**Comment by bensku** [comment]
Appears to be Spigot bug according to their issue tracker. The solution is, I'm afraid, to update to newer Minecraft version.

**Comment by Matocolotoe** [comment]
@bensku yes this is a Spigot bug and it is still there
https://www.spigotmc.org/threads/handledisconnect-called-twice.74171/
https://hub.spigotmc.org/jira/browse/SPIGOT-854
