### ISSUE TITLE
Call to getSingle() on a non-single expression in EffMessage

### ISSUE THREAD

**Issue by JustDylan23** [SkriptLang/Skript#1454]
https://hastebin.com/yisetunera.bash
I was trying to get all indexes of a variable, instead of it working it gave a massive console error
```vb
set {wands::tool::%name of player's tool%::lastuse::%player%} to now
```
this is how the variables are saved
```vb
!message all indexes of {wands::tool::*}
```
I executed this using the effect command
@TheLimeGlass told me to report this and reference him.

**Comment by Nicofisi** [comment]
Could you please provide some code reproducible without addons?

**Comment by Pikachu920** [comment]
I'm pretty sure this a dupe, but I can't find the original issue

**Comment by Nicofisi** [comment]
Thanks @Pikachu920, commited.

Side-note: I imagine now when the effect supports non-single expressions we don't need a separate handling for `ExpressionList`s (current code for reference)
https://github.com/SkriptLang/Skript/blob/44d7c85005c281478307caa5bce4dcbf97ba0657/src/main/java/ch/njol/skript/effects/EffMessage.java#L75
since their getArray method should handle the thing on its own well enough, is that correct?
https://github.com/SkriptLang/Skript/blob/01ef3f48f0b7501f7ff1ef3cd8acf07511833885/src/main/java/ch/njol/skript/lang/ExpressionList.java#L96-L109

**Comment by Pikachu920** [comment]
that part is done so we can parse the json if the expr is a variablestring

**Comment by Nicofisi** [comment]
Oh I see, never mind then
