### ISSUE TITLE
Bug: "all permissions" expr returns a single value

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1456]
Skript dev37c
paper 1.12.1
Reproduce:
```
command /test:
    trigger:
        
        loop command sender's permissions:
            send loop-value
```
This code will send an error message claiming that `command sender's permissions` is a single value. However when using `send command sender's permissions` it will print a list that looks exactly like the contents of a list variable.
Also, in the internal docs the expression is referred to as a list.

**Comment by xXAndrew28Xx** [comment]
Looks like `isSingle()` in https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprPermissions.java is improperly implemented.

**Comment by Nicofisi** [comment]
The ExprPermissions is improperly implemented @TheLimeGlass, PropertyExpressions are supposed to return exactly one (nullable) property per player - AKA if there is one player, then there should be exactly one permission. A way to fix this: make ExprPermissions a SingleExpression (accepting only one player in the syntax, this is confusing now since multiple players can have permissions that completely cancel out).

Does this solution sound okay?

Otherwise the ExprPermission should at least be made a `PropertyExpression<Player, String[]>` (the `[]`), but disclaimer here, I have no idea if this is supported, and even if it is, in my opinion would be a worse solution

**Comment by TheLimeGlass** [comment]
I didn't make this shit, I attempted to fix it and convert to a property. I was the one arguing that this should never have been added.

**Comment by Snow-Pyon** [comment]
@TheLimeGlass it was you, since you converted it in a property expression but who cares about who did it.

**Comment by Nicofisi** [comment]
@TheLimeGlass that's correct. Like you've just noticed, you made it a property expression. And this is what caused this particular issue - this expression for the reason above probably shouldn't be a property one, just a single one. I only mentioned you to let you know for the future 🌵

**Comment by xXAndrew28Xx** [comment]
@Nicofisi Yeah that solution seems ok. I wish Skript has some class that let you easily make property expressions that worked like how we want it to in this case with multiple objects for each thing the property is coming from.

**Comment by TheLimeGlass** [comment]
You want me to fix someone's.shit expression or remove it? Because all I want is to remove this syntax.

**Comment by xXAndrew28Xx** [comment]
@TheLimeGlass I don't know what you're going on about or how you misread it but your converting of this expression caused this bug, not anyone else's fault as the bug was not present before. Not that it mattered that you were the one that did it anyways, some realtively small changes can fix it.

**Comment by Nicofisi** [comment]
> I made the suggestion in the original pull request thread, it was an example of a PropertyExpression for the guy who originally added this...

Maybe you misread something, we're saying that this *should **not*** be a PropertyExpression.

Unless we are misinterpreting something, then please link us to that PR
