### ISSUE TITLE
Coal ID's issue

### ISSUE THREAD

**Issue by ProfCube** [SkriptLang/Skript#1459]
Hi, idk if I considered this a bug, but a miscalculation probably but I noticed that when putting the Minecraft name **COAL** when used in the game I get Charcoal instead of coal. But when I put the ID 263 I get COAL in stead of Charcoal. I have tested around it but thats the only way I can get coal.

**Comment by TheBentoBox** [comment]
Labeling similarly to other alias issues. Hard to say if this is a "bug", really.

This will be fixed with the next major update when we release the new alias system. To fix this temporarily, try going into your `aliases-english.sk` file and finding the line that says `[<any>](_| )coal = 263:0-1`. Replace this with `<any>(_| )coal = 263:0-1` (i.e. removing the square brackets around `<any>`), then do `/sk reload aliases` and see if your problem is fixed.
