### ISSUE TITLE
Bug: can't use arithmetics with n-th element out of %objects%

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1464]
Skript dev-37c
Spigot 1.12.1

No console or parse errors

Reproduce:
```
command /test:
    trigger:
        
        add 1, 2, 3 to {_test::*}
        
        set {_a} to 1st element of {_test::*}
        set {_b} to 2nd element of {_test::*}
        set {_c} to 3rd element of {_test::*}
        
        send "%{_a}%"
        send "%{_b}%"
        send "%{_c}%"
        
        set {_a} to ((1st element of {_test::*}) * 2)
        set {_b} to ((2nd element of {_test::*}) * 2)
        set {_c} to ((3rd element of {_test::*}) * 2)
        
        send "%{_a}%"
        send "%{_b}%"
        send "%{_c}%"
```

The first set of returns will be fine, the latter set will only return `0`
I have tried using many variations of parenthesis `()`, but to no avail

**Comment by Snow-Pyon** [comment]
Can someone else confirm this?

**Comment by Blueyescat** [comment]
@Snow-Pyon i can confirm

**Comment by Blueyescat** [comment]
This is because
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprElement.java#L109-L111
Return type of a variable expression = object, so **`first element of 1 and 2 + 3`** works fine. Is it actually possible to fix this? Maybe with the variable type hint thing..
