### ISSUE TITLE
[Suggestion] New aliases in docs

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1471]
Hello. So I talked to Snow about this today. He informed me that the new Skript for 1.13 does not include the aliases file like previous versions do to not wanting people to mess with them. Totally understandable. For myself, I don't generally change them, I use them more for reference. 

So I had two suggestions.
1) Create a command, that a person could run, which would generate an uneditable aliases folder strictly for reference.
or
2) Add the new aliases to the docs. 
He liked the docs idea and told me to suggest it on here. So there ya go :)

**Comment by TheBentoBox** [comment]
Forgot to comment but if aliases aren't gonna be easily accessible then this is definitely necessary, people shouldn't have to open the JAR to see the alias for something. And even if aliases do end up in the plugin folder (as a read-only version or otherwise), having them in the docs as well makes complete sense and should eventually happen regardless.

Another thing that could be nice, even if a bit strange, is a built-in Skript command to tell you the name of a specific material, e.g. `/skript alias tool` would send you the name of the item you're holding (same as `send "%type of player's tool%"` would), then  `/skript alias block` (same as `send "%type of player's target block%"`), and maybe even `/skript alias target` for getting the Skript name of an entity (same as `send "%player's target%"`). I think there's a lot of value to having aliases be accessible as possible both in-game and out.

**Comment by jaylawl** [comment]
Why will the aliases be hidden?

**Comment by ShaneBeee** [comment]
Thanks @TheBentoBox 
I do like that idea of the command. 
With Minecraft adding SEVERAL new blocks/items, not having the aliases easily accessible is going to make things quite tricky. AND I KNOW you guys are going to get 10,000 people asking you where they are ;) I mean, I KNOW where to find them, but not everyone does. 

I think the other reason I like the idea of them being in the docs, is because everything else is there, so it just makes sense to throw them in there as well.

**Comment by bensku** [comment]
Per-script aliases are still (going to be) usable, *and* users can add custom aliases files to plugins/Skript/aliases folder. The reason for not allowing modifications to default aliases is that updates become quite painful once people start doing it. And I expect that we're going to need to push updates quite often to address bugs.

I suppose that we could extract aliases as "read-only" for viewing. This is not a replacement for proper documentation web page, but it avoids making the current situation worse.

**Comment by Anarchick** [comment]
It's possible to make `/skript aliases update [version]` and everyone will update their default aliases (If aliases are into .JAR I don't know if it's possible)

**Comment by sovdeeth** [comment]
No longer relevant as aliases are being phased out.
