### ISSUE TITLE
bed missing/not work .

### ISSUE THREAD

**Issue by UzumakiYT** [SkriptLang/Skript#1565]
```
		give bed to player
		give red_bed_item to player
		give red_bed to player
```
aliases

**Comment by ShaneBeee** [comment]
if you do red bed without the underscore it'll work

**Comment by UzumakiYT** [comment]
ok works, thanks

**Comment by ShaneBeee** [comment]
You're welcome :)

**Comment by TheBentoBox** [comment]
Yeah, no underscore support and I don't plan on adding it at the moment, aliases are much more complicated now with many more optional parts due to the block states so supporting an underscore in place of every space would make the amount of aliases to parse enormous. Every space/underscore would multiplicatively double the number of aliases available for each entry, and there are some long aliases with many spaces.

Just as an example, `{waterloggable} {openable} {trapdoor position} {directional} {wood type} trapdoor¦s` would end up generating 32x as many aliases as it already does (which is a lot) if it supported underscores (2^5 since there's five potential spaces).

**Comment by ShaneBeee** [comment]
@TheBentoBox Oh come on you dont want to see something like this:
```
[15:59:25 INFO]: [Skript] Reloading the aliases...
[15:59:29 INFO]: Loaded 398571638 aliases in 13hours
[15:59:29 INFO]: [Skript] Successfully reloaded the aliases.
```
;)  (ps im joking)
