### ISSUE TITLE
Removes 2 instade of 1

### ISSUE THREAD

**Issue by ham1255** [SkriptLang/Skript#1574]
```
on every 1 seconds:
    if {reboot_started} is true:
        stop
    if {reboot_Time_seconds} is higher than 0:
        remove 1 from {reboot_Time_seconds}
    if {reboot_Time_seconds} is 0:
        wait 1 seconds
        remove 1 from {reboot_Time_mins}
    if {reboot_Time_seconds} is 0:
        set {reboot_Time_seconds} to 59    
```

skript code 
![image](https://user-images.githubusercontent.com/34905970/46298922-4d34f680-c5b1-11e8-9707-4be7723b9108.png)

**Comment by ham1255** [comment]
i removed extra if {reboot_Time_seconds} is 0: and add it to the another one and it skeep do the same !
spgiot 1.13.1
skript aplha4
skript file

**Comment by ham1255** [comment]
https://hastebin.com/muxidupopu.sql

**Comment by TheBentoBox** [comment]
This is a bug in your code since it's not written very well. When `{reboot_Time_seconds}` is 1, it will `remove 1` from it to set it to 0, then the next `if` statement will immediately run and schedule removing 1 from the minutes, but before that can happen your next `every 1 second` event is already called (since you're waiting a second)` and `{reboot_Time_seconds}` is still 1 so it removes 1 from the minutes again. I don't think this is the best way to do a timer but with how you're going about it your code should look like this:
```
on skript load:
	set {reboot_Time} to 23
	set {reboot_Time_seconds} to 59
	set {reboot_Time_mins} to 59
	delete {reboot_started}

every 1 second:
	{reboot_started} isn't true
	if {reboot_Time_seconds} > 0:
		remove 1 from {reboot_Time_seconds}
	else:
		remove 1 from {reboot_Time_mins}
		set {reboot_Time_seconds} to 59
```

In the future, you should report issues like this on the [skUnity Forums](https://forums.skunity.com/) if you're not positive it's an issue with Skript itself. This issues section is for reporting bugs in the plugin or requesting new features.

Additionally, your code was formatted incorrectly in your post. I fixed it, but please take a look at the source so you can know how to format code in [Markdown](https://guides.github.com/features/mastering-markdown/) in the future.
