### ISSUE TITLE
The weird 'is blocking' condition

### ISSUE THREAD

**Issue by Nicofisi** [SkriptLang/Skript#1578]
https://github.com/SkriptLang/Skript/blob/7cd7a4511c2fafb12e10742b9b5c2819c860fa01/src/main/java/ch/njol/skript/conditions/CondIsBlocking.java

Don't you guys think it's a bit counter intuitive? "victim is blocking" hmm.. does anyone have an idea for a better syntax?

Even the Spigot javadocs for this method are hella confusing:
```
Check if the player is currently blocking (ie with a shield).
```

"ie with a shield" and otherwise what with?? hmm

**Comment by TheBentoBox** [comment]
"i.e." basically means "that is", so it's just specifying that it means with a shield; the wording doesn't imply that there's an otherwise case where it's not a shield. The reason that was added to the docs at all, though, is because you used to block with swords, so the meaning of that method changed somewhat.

I can see it sounding a *tad* awkward but I don't think it's a real issue. The way I'd word that sentence as a normal statement is "I want to know if the player *is blocking*", which is the same wording as the condition (`if the player is blocking`).

**Comment by Nicofisi** [comment]
Oh, my bad about the `i.e.`, thought it meant 'for example' lol

Anyway, honestly I think the syntax should have the `[with [a] shield]` since shields are in every version that this fork supports. My first thought when I saw this condition was that it somehow checks whether the victim is, hmm, counterattacking? Well forget it, but still, I wouldn't ever say that someone "is blocking" without mentioning the shield

**Comment by TheBentoBox** [comment]
The general idea is that "e.g." means "for example" and "i.e." is used to specify something about the previous statement but yeah, some people use them interchangeably which isn't really correct.

As for the syntax, I'd definitely like to hear more opinions but I never thought of it as counterattacking. It does specifically use the word "blocking" which is how you'd describe what a shield does; blocking isn't the same thing as counterattacking. I'd also find "with a shield" to be redundant since as you said the only thing in the game that lets you block (in our supported versions) is a shield so it's implied by the `is blocking` that they're using a shield. You don't have to say "I'm walking *with my legs*" for people to know how you're walking! 

That all being said, regardless of if others find it confusing or not it can't hurt to have your proposed optional syntax tacked on, just so people who want to add it for clarity can do so (and who knows if they'll add other ways to block in the future).

**Comment by Nicofisi** [comment]
@TheBentoBox I meant I understood 'player is defending' as 'player is counterattacking', not 'player is blocking' ;)
