### ISSUE TITLE
on block break not working

### ISSUE THREAD

**Issue by titustitus98** [SkriptLang/Skript#1579]
Hi i am undergoing an issue with skript that started ever since i have updated my server to 1.12.2 and to the latest version of skript: in the following code there is a part where i have "on block break" event that triggers a whole lot of things but for some reason it doesen't do anything and i can't figure out why and it shows no errors on console or on reload. 
Code: https://pastebin.com/0uNMk7Nm

**Comment by ShaneBeee** [comment]
1) You should post the exact version of Skript you are using... saying "latest" is really not helpful, because everyone has a different version of "latest"
2) I dont think this is an error with Skript itself but possibly how its written.

If you need support for your scripts please feel free to join one of the Skript help discords
Skript-Chat: https://discord.gg/V4qFVnh
SkUnity: https://discord.gg/0l3WlzBPKX7WNjkf

**Comment by titustitus98** [comment]
the thing is it worked before i updated my server

**Comment by ShaneBeee** [comment]
Downgrade to Skript 2.2Dev37c 
2.3-Alpha1-4 are strictly meant for testing, finding/reporting bugs, they aren't meant for productions servers are they are still quite buggy, as stated in the release notes

**Comment by titustitus98** [comment]
ok thanks

**Comment by titustitus98** [comment]
works now

**Comment by Pikachu920** [comment]
@bensku feel free to repopen if you think this is an issue with aliases
