### ISSUE TITLE
Skript treating entities as item types

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#1631]
```
on sneak toggle:
	broadcast "%target entity%"
	if target entity is not an armor stand:
		broadcast "nope"
	else:
		broadcast "yup"
```
Always broadcasts nope even when the entity is an armo(u)r stand. I thought this was fixed a while back but it seems to not be.

Tested Skript version was 2.3-beta1

**Comment by Snow-Pyon** [comment]
![image](https://user-images.githubusercontent.com/23110519/47610760-acace780-da33-11e8-8589-a8b99791cfa5.png)
As you can see, Skript is treating it as an item, thus the comparison failing.

Also debugged #1630, and it is the exact same issue: the size expression treating `all chickens` as `raw chicken` (the item) and since items are simple literals, the init check fails.

Same happens if you do `size of all armor stands`.

**Comment by TheBentoBox** [comment]
I suppose the best way to fix this short-term would be an alias update? i.e. Renaming the armor stand alias to `armor stand item¦s`, same with the chicken ones. The ideal solution is that Skript should know what type it's looking for based on the context, but I imagine that's not an easy fix.

**Comment by bensku** [comment]
If I remember correctly, Skript used to solve this by converting items to entities as needed. Such a solution should still be possible to implement.

**Comment by Snow-Pyon** [comment]
The thing is that it won't fix it for things such as the amount expression, we're probably better of changing the aliases.

**Comment by bensku** [comment]
Are you sure those are broken? The comparison condition in particular is so general that parser may have trouble figuring out wanted data type. Simpler expressions taking entities might just work.

**Comment by bensku** [comment]
This particular problem has been solved. @TheBentoBox if you encounter any issues like these, they can probably be fixed by adding relatedEntity to conflicting item alias. README in aliases has contains how this can be done.

This fix restores previous behaviour of Skript, except now it is based on aliases. Probably no additional Java code is needed for future naming conflicts that we might encounter.

**Comment by TheBentoBox** [comment]
Cool, makes sense. I think there are some others that could be improved in this way (ender crystals and item frames) so I'll take a look at those later!

**Comment by TheLimeGlass** [comment]
Related https://github.com/SkriptLang/Skript/issues/332
