### ISSUE TITLE
wierd bug

### ISSUE THREAD

**Issue by aglarcz** [SkriptLang/Skript#1647]
hi, on latest skript:
```
on place of a spawner:
    if player doesn't have permission "antipleb.spawner":
        cancel event
```
- triggering even when trying to place soul sand.. no idea why?

**Comment by Efnilite** [comment]
What is latest Skript? use `/ver Skript` and tell what the version is since `latest` may mean the version from 2014 from bukkit ¯\_(ツ)_/¯

**Comment by aglarcz** [comment]
2.3 beta 1

**Comment by Nicofisi** [comment]
What's the Minecraft version?

**Comment by aglarcz** [comment]
1.13.2 - paperspigot 409

**Comment by ShaneBeee** [comment]
I can confirm this.
Skript 2.3 beta 1
Paper 1.13.2

Whether i use on place of soul sand or spawner, it cancels both of them

**Comment by bensku** [comment]
@TheBentoBox Aliases issue, probably.

**Comment by TheBentoBox** [comment]
@bensku I believe this is actually caused by the issue Snow described [here](https://github.com/SkriptLang/Skript/issues/1567#issuecomment-434221354). Due to this issue, blocks (at least in conditional events like this) are passing compaarison checks with other block types if they share at least one alias group. In `z-block-placement.sk`, we have soul sand and monster spawner in the same `special torch sides` alias group, which is kinda required since I believe it's used in the code.
