### ISSUE TITLE
Issue with wheat (item)

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1664]
[18:35:28] [Server thread/ERROR]: [Skript] can't understand this condition: 'player have 64 wheat' (wq1.sk, line 520: if player have 64 wheat:')

code:
```
on rightclick on player:
  if name of event-entity is "&eGornik":
    if {qf::%player%} is "0.41":
      if player have 64 wheat:
        remove 64 wheat from player's inventory
        add 16 diamond to player's inventory
```

skript version: beta-2 (latest)
server paper-424 (1.13.2)

**Comment by TheBentoBox** [comment]
Yeah, the aliases here could use some improvement. It's a bit strange because there's no "right answer" about how aliases should be structure; should just `wheat` refer to the *item*, or the *block*? Maybe neither, and you always have to specify if you mean the wheat item or block? Or should it refer to an alias group (such as `[any] wheat = wheat item, wheat plant`) and then if you want to reference a specific one (just the item or block) you have to append "item" or "block/plant" to the alias? This applies to many other items too and they're all valid answers.

Regardless, I'll take a look at the wheat aliases and any others that may have similar issues as soon as I can. Open to feedback based on the above examples.

**Comment by TheBentoBox** [comment]
The `item` part of the wheat item alias is now optional.
