### ISSUE TITLE
Errors in a non-existent script

### ISSUE THREAD

**Issue by Vulqa** [SkriptLang/Skript#1667]
### Question

When i reload all the scripts i have 30 errors about banners, but i don't have the script "derocation.sk", is this normal ?
Exemple of errors: http://prntscr.com/lf65ob

Server's version: 1.12.2
Skript's version: 2.3-beta2

**Comment by Vulqa** [comment]
@ShaneBeee Where i can found it ? Because i have only these files http://prntscr.com/lf69go

**Comment by ShaneBeee** [comment]
its hidden in the skript.jar file
The error has been fixed by @TheBentoBox already
Im assuming it will be done in the next update. 
Alternatively what you can do for now is this
1) Download the aliases here 
https://github.com/SkriptLang/skript-aliases/archive/master.zip

2) Unzip this in your plugins/skript folder, and rename it "aliases"

3) Open your skript config.sk file, and add this line to the very bottom
```
load default aliases: false
```

This should solve the issue for now :)

**Comment by TheBentoBox** [comment]
This was meant to be fixed for this release actually, or so I thought; the devs possibly forgot to update the submodule when building the release JAR? Not sure if that's necessary or if it pulls the latest aliases automatically every time you build.

**Comment by ShaneBeee** [comment]
> This was meant to be fixed for this release actually, or so I thought; the devs possibly forgot to update the submodule when building the release JAR? Not sure if that's necessary or if it pulls the latest aliases automatically every time you build.

I just tested with the latest Aliases and it loads perfectly fine, so my assumption is they forgot to update the module

**Comment by Snow-Pyon** [comment]
I'll reupload the binaries with the latest aliases later, sorry for the troubles.

**Comment by TheBentoBox** [comment]
This was fixed but accidentally never marked as completed.
