### ISSUE TITLE
[Suggestion] Extra functions for Conditions and Events.

### ISSUE THREAD

**Issue by Mwexim** [SkriptLang/Skript#1681]
### Conditions

**Or, Or Construction**

`if arg-1 contains or “hello” or “goodbye”`
If arg-1 contains “hello” -> Returns true
If arg-1 contains “goodbye” -> Returns true
If arg-1 contains “hello” and “goodbye” -> Returns false

So one of the two (or more if identified) statements are correct, it will return true. But if both (or all) the statements are correct, it will return false. If for example three statements are identified, 1 of them must be correct, not two or three.

### Events

**Priorities**
`on leftclick with priority 1:
      Send “Hello”
on leftclick with priority 4:
      Send “Bye”
on leftclick with priority 2:
      Send “Goodbye”`
The messages will show up in this order: Hello, Goodbye and then Bye.
If two priorities have the same value, the one who comes first in the Skript should be triggered first.
The values must be integers.
EDIT: Sorry but I couldn’t order the events below eachother. Hopefully you can understand those. If you can’t, don’t hestitate to ask me.

Hopefully this will get added :D
Kind regards,
Mwexim

**Comment by Pikachu920** [comment]
```
if arg-1 contains "1" and "2":
if arg-1 contains "1":
if arg-1 contains "1" or "2":
if arg-1 doesn't contain "1" and "2":
if arg-1 doesn't contain "1":
if arg-1 doesn't contain "1" or "2":
```
should all already work. Are you experiencing something different?

**Comment by CHarcoalToast** [comment]
What you mentioned is correct, but is not exactly the same as what I proposed.

The Nor, Nor/Neither construction already exists, this would be just a new syntax and not very usefull, but the or, or construction doesn’t exists.
If you use `if arg-1 contains 1 or 2` this will happen:
Arg contains 1 -> It will pass because it is true
Arg contains 2 -> It will pass because it is true

Arg contains 1 and 2 -> It will pass because it is also true
And that is the difference. At the Or, or construction, only one of the values may be true.

**Comment by Snow-Pyon** [comment]
I am not exactly understanding what you're proposing here, you should be able to use both `or` and `nor` in any cases, to put an example:
```ruby
# text-argument being "hey, what's up?"
if text-argument contains "hi" or "hey":

# true when: it contains hi (not the case) or hey.
# false when: it doesn't contain any of the given texts.

# another example, this time with "hi" as text-argument:
if text-argument isn't "hey" nor "what's up":
```

**Comment by bensku** [comment]
We should mind the English grammar when adding new syntaxes. For exclusive disjuction (XOR), finding a good syntax might be challenging. Suggested syntaxes don't look like natural English to me.

**Comment by CHarcoalToast** [comment]
I removed the Nor section because this is already implemented but the Or, Or section (also known as the XOR or Exclusive Or) is not implemented yet and could be a handy syntax to use.

Also the comments on this topic were only about the Nor section, but under that section there's another feature for events ;) You can read that too

**Comment by CHarcoalToast** [comment]
Also @Snow-Pyon I think you disarrayed the two ideas for the Conditions.

**Comment by Blueyescat** [comment]
Why not just use two conditions?

Event priorites feature is already suggested for multiple time:. https://github.com/SkriptLang/Skript/issues/197

**Comment by CHarcoalToast** [comment]
The Exclusive Or will just be a QoL change but could be very handy. And can you tell me how you can do this condition in two conditions?

**Comment by Blueyescat** [comment]
```vb
if arg-1 doesn't contain "hello” and “goodbye”:
    if arg-1 contains “hello” or “goodbye”:
```
