### ISSUE TITLE
Skript error with Skript v2.3-alpha5

### ISSUE THREAD

**Issue by KleeSup** [SkriptLang/Skript#1708]
Whats gone on with Skript v2.3-alpha5?!?
If I reload all my Skripts that spams me full with errors!
Error:
https://pastebin.com/eNv47b7P
Please HELP!!!

**Comment by TheBentoBox** [comment]
1. It looks like you either don't have WorldGuard installed or you have the wrong version. Skript now relies on WorldGuard 7 (and therefore WorldEdit 7, too). Update your versions of these plugins or install them if you don't have them.
2. You're not using the latest version of Skript. The latest release can always be found [here](https://github.com/SkriptLang/Skript/releases). It's especially important to stay up-to-date when we're in an alpha/beta phase since obviously the point of these releases is that they're buggy and being worked on more rapidly.
3. Try to be wary in the future of if what you're reporting is either a bug with Skript itself or a feature suggestion. If it's not either of those things it belongs on the forums, not here.
