### ISSUE TITLE
Skript can't safe variables to 'default' database???

### ISSUE THREAD

**Issue by KleeSup** [SkriptLang/Skript#1710]
I dont't have configure a database but Skript says (spam) they can't save variables to Default database while I reloading my Skript!
Error:
[Skript] Skript cannot save any variables to the database 'default'. The server will hang and may crash if no more variables can be saved.

Can anyone help me please?!?
Sorry for my bad english :/

**Comment by ShaneBeee** [comment]
You need to follow the new issue format and include some more information.
For example, which spigot/paper version you are using. Which version of Skript.
How to reproduce the error. Which addons you are using.
The more information you can provide, the more help we can give. 
This tiny bit of info really gives us nothing to work on.

**Comment by Drc-DEV** [comment]
The way skript handles variables is laggy, and also the way it handles schedules is really annoying. 
On PaperSpigot 1.12.2 using 2.2-dev36 for example, using "while" or "wait" or "every" will make your server hang from time to time and it will show "Skript::Task: ch.njol.skript.effects.Delay$1 (Single)" in the timings.
Regarding variable saving/loading, it throws the error the OP is mentiong every 2-3 minutes or so if you have a lot of scripts. 
I think that instead of adding features, a really serious performance update is needed, because these 2 problems are really making me and other developers try to remove as many scripts as we can, forcing us to use Java instead. I mean, nothing wrong with learning java instead, but converting all the scripts in java plugins takes a lot of time, which most of us don't have. 
Saving time and fast bug fixing and coding is all Skript is about, but if it comes with the price of having a laggy server, it is not worth the effort.

**Comment by HYPExMon5ter** [comment]
Variables have been improved in 2.2-beta-1 I believe, or a later beta. Try upgrading

**Comment by TheBentoBox** [comment]
No response, and as bensku said more recent releases should be more stable regarding variables.
