### ISSUE TITLE
How to put itemdata ?

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#1718]
### Question
Something like this doesn't work anymore in the latest beta4
on break of crops:7:
on break of 59:7:

**Comment by Snow-Pyon** [comment]
Item id and sata values have been removed in aliases rework. You need to use the actual alias for the item now (e.g. `fully grown wheat plant`).

You can find all the aliases here: https://github.com/SkriptLang/skript-aliases

**Comment by Sodies** [comment]
what if is halfly grown wheat plant?

**Comment by Snow-Pyon** [comment]
`four stage wheat plant` (@TheBentoBox may aswell change it later to make it more intuitive? It is kinda strange at moment).

**Comment by Sodies** [comment]
> `four stage wheat plant` (@TheBentoBox may aswell change it later to make it more intuitive? It is kinda strange at moment).

There are also some broken events. Not sure where is this coming from:
on region enter/exit event

**Comment by TheBentoBox** [comment]
It's `stage four`, not `four stage`, which I think makes more sense, but I'm open to suggestions. Note, however, that there is no "half grown" plant for any of the eight-stage ones (which is the majority of them) because there is no middle stage with an even number of stages (e.g. both four and five are equally in the middle from stage one to eight so they both are "half grown").

Feel free to make suggestions, preferably as issues in the skript-aliases repo so they're tracked.
