### ISSUE TITLE
Is REGION event no longer support in bensku?

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#1719]
### Question
Looks like I can't no longer use on region enter/exit event. It work in the previous bensku skript. Did it change to other names?

**Comment by Sodies** [comment]
> No sodies
> it's exists but need worldedit and worldgaurd that is 7.0.0
> but it's not supported for 1.12.x or lower
> only 1.13.x

So I need spigot 1.13 to make the event to work?

**Comment by TheBentoBox** [comment]
I don't believe the new WG and WE *only* work on 1.13. Try updating them.

**Comment by Sodies** [comment]
> I don't believe the new WG and WE _only_ work on 1.13. Try updating them.

i updated both we and wg. and using 1.12.2 jar spigot still doesnt work for the event

**Comment by bensku** [comment]
WorldGuard 6 is not supported, and would be hard for us to support. I don't think WG 7 works on 1.12, unless that changed recently @TheBentoBox. To fix this, well, you could try a region plugin that didn't break API with their 1.13 version. Skript supports a few options.

**Comment by DankPrison** [comment]
@bensku @TheBentoBox WG 7 does not work on 1.12 and below and is still in beta. At this rate will take months. Please add support for WG 6 so I can actually enjoy bug fixes in that exist over buggy dev37c and I'll donate some money. Hard work pays off.

**Comment by DankPrison** [comment]
@Nicofisi Never said it was, but that's his own fault for tying to support 1.13 not mine. Most people don't even care about 1.13 it's garbage. I want 1.12.2 support. Not be forced to use crap 1.13 to enjoy new skript versions. What a joke and waste of time.

**Comment by TheBentoBox** [comment]
There’s still old versions you can use just fine on 1.12. There have been huge refractors made to get the plugin to work on 1.13 so it’s not as simple as just having two different versions. I also don’t get your aversion to 1.13 or why it’s “garbage” but to each their own I guess. 

Regardless, being rude in the issue tracker is also a joke and waste of time and won’t be tolerated, so I’d stop there. The literal entire point of this fork is to keep Skript updated to the latest Minecraft versions since it was abandoned by the original dev. If you’re not going to keep your server up to date then you can’t expect full support, especially when there ARE already options to get it to work (other protection plugins) and when it working isn’t our fault (it’s due to WG not working — Skript itself works fine on 1.12 because we DID put in that effort, it’s just that WG isn’t compatible).
