### ISSUE TITLE
Bug with Enchanted golden apple and golden apple

### ISSUE THREAD

**Issue by DrakeSun** [SkriptLang/Skript#1739]
```
on pick up of enchanted golden apple or ender pearl:
	wait 1 tick
	limitySchowek(player)

function limitySchowek(p: player):
	if amount of enchanted golden apple in {_p}'s inventory is greater than 2:
		set {_posiadane} to amount of enchanted golden apple in {_p}'s inventory
		set {_s} to {_posiadane} - 2
		remove all enchanted golden apple from {_p}'s inventory
		add {_s} to {schowek::koxy::%{_p}%}
		add 2 enchanted golden apple to {_p}'s inventory
		send "&c&lLIMIT &7Osiagnieto maksymalny limit &7&lkoxow" to {_p}
	if amount of ender pearl in {_p}'s inventory is greater than 1:
		set {_posiadane} to amount of ender pearl in {_p}'s inventory
		set {_s} to {_posiadane} - 1
		remove all ender pearl from {_p}'s inventory
		add {_s} to {schowek::perly::%{_p}%}
		add 1 ender pearl to {_p}'s inventory
		send "&c&lLIMIT &7Osiagnieto maksymalny limit &7&lperel" to {_p}
```

**PROBLEM**
The problem is that if an item that I raises is a golden apple, not an enchanted golden apple, then it does the same what in case of a enchanted golden apple

**ERRORS**
There is no

**SERVER VERSION**
1.12.2

**SKRIPT VERSION**
2.3-beta4

**Comment by TheBentoBox** [comment]
Is this due to all of the work recently around supertypes @bensku and @Snow-Pyon ? I know some stuff was reverted so I'm not totally sure what the current status of that is but you can see [here](https://github.com/SkriptLang/skript-aliases/blob/master/foodstuffs.sk#L44-L45) that the aliases don't conflict nor does the [grouped golden apple alias](https://github.com/SkriptLang/skript-aliases/blob/master/foodstuffs.sk#L73) so this sounds like the same issue of them passing comparisons via sharing a common supertype.

**Comment by bensku** [comment]
This appears to work on 1.13. Might be that on 1.12 damage values get ignored or something nasty like that.
