### ISSUE TITLE
Issue with Returning Items from a Function

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#1747]
### Description
Functions that return multiple items (e.g. 2 diamonds) in reality return ```<none>```

### Steps to Reproduce
```
function test(c: number) :: item:
    set {_gem} to diamond
    return {_c} of {_gem}
    
function test2(c: number) :: item:
    return {_c} of diamond

command /testfunction:
    trigger:
        give player test(1) #Should give the command sender 1 diamond
        send "test(): Attempting to give %player% %test(1)%"
        give player test(2) #Should give the command sender 2 diamonds
        send "test(): Attempting to give %player% %test(2)%"
        give player test2(1) #Should give the command sender 1 diamond
        send "test2(): Attempting to give %player% %test2(1)%"
        give player test2(2) #Should give the command sender 2 diamonds
        send "test2(): Attempting to give %player% %test2(2)%"
        #In total, the command sender should recieve 6 diamonds, 3 from test() and 3 from test2()
```

### Expected Behavior
The player should receive 6 diamonds

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/19924575/49838448-b0c77580-fde5-11e8-8cd0-733ef2e425a8.png)

Note: After executing /testfunction, the player only recieves 3 diamonds (from test2())

### Server Information
* **Server version/platform:**       1.12.2 (Paper)
* **Skript version:**                2.3-beta4

### Additional Context
This issue didn't occur in Skript 2.2-dev37c, and only occurred when I updated the version of Skript (2.3-beta4)

**Comment by Blueyescat** [comment]
Your description was wrong, it is not related to multiple items, but can confirm the same with 1.13.2

---
```vb
# {x} = 2
# {y} = diamond

function test() :: item:
	broadcast "&62 diamonds"
	broadcast "&6%class of 2 diamond%" # skript-mirror addon
	return 2 of diamond

function test1() :: item:
	broadcast "&a%{x} of {y}%"
	broadcast "&a%class of {x} of {y}%"
	return {x} of {y}

function test2() :: item:
	broadcast "&c%2 of {y}%"
	broadcast "&c%class of 2 of {y}%"
	return 2 of {y}

function test3() :: item:
	broadcast "&b%{x} of diamond%"
	broadcast "&b%class of {x} of diamond%"
	return {x} of diamond
```
![image](https://user-images.githubusercontent.com/19474570/50017763-1bdb9c80-ffde-11e8-99f0-636b4b4912ea.png)

First of all, shouldn't the [X Of](https://skriptlang.github.io/Skript/expressions.html#ExprXOf expression) return item type instead of item stack if it is an alternative for the item type to be able to enter non-literal expressions?

And these functions will work when you make the return type multiple (items) because `item` refers to item stack and **`items` refers to item type**, this is also a bad thing. So they will also work when you make the return type `item type`.

Not sure about why `{x} of diamond` works and others don't... Why it doesn't work when the return type is `item stack` and the return value is also an item stack, except `{x} of diamond`...

**Comment by TheBentoBox** [comment]
Really good investigation @Blueyescat , weird bug for sure

**Comment by bensku** [comment]
Huh, this one was hard to track down. In the end, it turned out this was caused by two completely different bugs.
