### ISSUE TITLE
1.13 aliases 2.0 minecraft:brain_coral failing parse

### ISSUE THREAD

**Issue by BlightedBlue** [SkriptLang/Skript#1754]
### Issue
I'm trying to boot up my 1.13(.0) server with Skript 2.3-beta4, SkQuery-Lime (newest version from Spigot Forums as of the 16th of December, 2018) and Skellett.

Steps to reproduce are unknown. Most likely just running any skript 2.3 beta with 1.13(.0)

### Expected Behavior
Expected behaviour is just to load normally, without stack traces regarding the waterlogged state of blocks.

### Errors / Screenshots
Here's a pastebin of the console errors I'm getting on boot: https://pastebin.com/R1qqLbj6

### Server Information
* **Server version/platform:**       Spigot 1.13(.0) (git-Spigot-fe3ab0d-162bda9)
* **Skript version:**                2.3-beta4

### Additional Context
Skript functions normally on 1.13.2, and this issue doesn't prevent the server from booting up, it just causes a leap in RAM that exceeds the allocated RAM for my server.

**Comment by Blueyescat** [comment]
No reason to use 1.13 you know, it is buggy, not recommended, not supported.

**Comment by BlightedBlue** [comment]
It's a requirement for something I'm doing. @Blueyescat
I know it's not well supported.

**Comment by Snow-Pyon** [comment]
It is supported, I haven't said anything about that since he may (or may not) have a reason to use that version (e.g.: a plugin not working properly on 1.13.2 or just issues when updating, things like that). And either way, if we support 1.9.0, why would we be against supporting 1.13.0?

**Comment by TheLimeGlass** [comment]
Your url you provided is invalid, but we understand the issue.

**Comment by BlightedBlue** [comment]
Maybe add a version check when loading the waterlogged state aliases?

**Comment by TheBentoBox** [comment]
I specifically didn’t write the aliases to support 1.13.0 because it’s a bad, unstable version. It is simple dangerous to use it over 1.13.2 because your world can easily get corrupted and there’s no reason not to update to 1.13.2. 

What are you possibly doing that could REQUIRE you I use 1.13.0 instead of 1.13.2? Because in all honesty it would be stupid of me to specifically make an alias change to support a version with as many dangerous bugs as 1.13.0 and I’m not going to do it without a really convincing reason.

**Comment by TheLimeGlass** [comment]
Well it's a bug. If it's not going to be fixed then Skript should be disabled on 1.13

**Comment by Snow-Pyon** [comment]
No one said it isn't going to be fixed, Simba said that he doesn't want to do it himself and that's fine, we could accept a PR to it or let another member fix it.

**Comment by TheBentoBox** [comment]
I'm not saying I'm absolutely refusing to do it if it's the decision of the devs that they want to support 1.13.0, I'm just saying I'm of the mind that that would be a poor decision and that yes, if the choice is between fixing this or not supporting 1.13.0 at all (as in disabling the plugin), then disabling the plugin is smarter because we shouldn't encourage people to use a blatantly buggy and dangerous version.

@BlightedBlue I see you leaving responses on posts here but you're not saying anything or answering my question -- I'd like to know why you specifically need to be on 1.13.0 as opposed to 1.13.2. Odds are you actually don't, but if you can present a situation where someone NEEDS to be on 1.13.0 instead of 1.13.2 then I'll be much more inclined to both fix this immediately and fix other 1.13.0-specific issues in the future. But neither 1.13.1 nor 1.13.2 introduced any breaking changes so there's simply no reason you should be unable to upgrade.

**Comment by bensku** [comment]
I have proposed to explicitly drop support for old minor Minecraft releases in #1588. Fixing this one should be possible, but Minecraft has had a *lot* of minor releases after 1.9. Someone needs to explicitly volunteer to test with them if we want to claim that they're "supported".

@TheLimeGlass Skript is generally not disabled on versions that are even halfway usable. On 1.8, for example, Skript is utterly broken, but with right config option, Skript will run. On 1.13, Skript might be perfectly usable, provided that you don't use corals or provide custom aliases (yes, that is possible).

**Comment by bensku** [comment]
Lowering priority, as we have more important bugs to solve in future. Use 1.13.2, it is more stable anyway.

**Comment by Wealthyturtle** [comment]
Closing this issue as it Skript's README file specifically states that old patch versions, e.g. 1.13.0 are **not** supported by Skript, see
![image](https://user-images.githubusercontent.com/19924575/66879781-61983580-eff2-11e9-997d-c3d05b802a1d.png)
And I don't see any particularly good reason for specifically supporting 1.13.0
