### ISSUE TITLE
Comparision issues

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1768]
```
on rightclick with stick:
	if player's tool is 1 stick named "&6Villager" with lore "&bKliknij prawym!":
		loop all entities in radius 6 around {locauto}:
			if "%loop-entity%" is "villager":
				teleport loop-entity to player
				remove 1 stick named "&6Villager" with lore "&bKliknij prawym!" from player's inventory
				send "&aGotowe!"
				stop
```
So:
if "%loop-entity%" is "villager" <- WORKS
if loop-entity is villager <- DOESN'T WORKS but no errors anyway

**Comment by iOshawott** [comment]
set {pktime::%loop-index%} to "%{pktime::%loop-index%}%" <- works

set {pktime::%loop-index%} to {pktime::%loop-index%} parsed as text <- ERROR! Parsing as text is useless!! (why? lol, I need it ;-;)

**Comment by Snow-Pyon** [comment]
None of those cases need you to convert the expressions into strings, you're probably comparing it wrongly and the fact that it works after "stringfying" them is just a coincidence. 

You're better off joining one of the Discord servers and sort these issues out with help of the users.

**Comment by iOshawott** [comment]
> None of those cases need you to convert the expressions into strings, you're probably comparing it wrongly and the fact that it works after "stringfying" them is just a coincidence.

How it can be wrongly done if "stringfying" it fixes? OMG, most of those scripts works on my second server with dev-37c and mc 1.10... I just copied those skripts and paste them on 1.13.2 so... lol? why? I don't get it : /

XD what?

**Comment by Snow-Pyon** [comment]
Because the string representation isn't the same as the object's one. For example, if you do a comparison like this:
```vb
if event-block is log: 
```
Wouldn't work since you're trying to reference `any log` but you're actually referencing `oak log` there, but Skript doesn't know it unless you specify it. Meanwhile when comparing it like this:
```vb
if "%event-block%" contains "log":
```
Works because the string representation of all the log blocks contain "log" in them.

And you would have to expect some scripts to not work at all when a version bump was done, remember that there was a whole alias overhaul and that could have changed many things.

So, as said, try to resolve those issues in one of the Discord servers with help of the users. I'll close the issue since this seems to be more of an user error than anything.

**Comment by iOshawott** [comment]
Its stupid

**Comment by iOshawott** [comment]
@Snow-Pyon 
btw 
event-block is log <- works
event-block contains "log" <- doesn't works, no errors
