### ISSUE TITLE
Skull Bug with Skript 2.3-beta6

### ISSUE THREAD

**Issue by KleeSup** [SkriptLang/Skript#1772]
The changelog of script 2.3-beta6 says that the skull error has been removed, but a new bug has occurred. Although there is no console error, but something else, because if you give yourself a head or format it into an inventory, then appears in place of the player's head, a normal skeleton skull

My Code:
format gui slot 4 of player with ("mhf_chest" parsed as offline player)'s skull named "&6&lMinigames" with lore "&8➥ &4&oIn Arbeit!" to do nothing
give player's skull to player

And I have a second question:
It is possible to use the new item aliases like "stone sword" in old Skript Versions like Dev37c ("stone_sword" in Dev37c)? The new item forms drops errors!

Sorry for my bad english
Please Help!

**Comment by TheBentoBox** [comment]
Regarding the last one, I intentionally didn't include underscores as an alternative in the new aliases due to the absurd amount of extra aliases it creates. It'd at LEAST double the amount of aliases, as you can multiply the numberr of alternatives it would add for each alias is `(number of spaces ^2) - 1`. It'd probably end up taking 10-15 seconds just for Skript to parse aliases.

If we want to support that, it'd be miles better for Skript, when it accepts an item alias, to just replace all underscores with spaces at parse time.

**Comment by KleeSup** [comment]
Ok, else I wait for Bugfixes insteat of using Dev37c

**Comment by weberlepecheur** [comment]
This syntax for skull works fine in beta6
`....with skull of ("MHF_ArrowLeft" parsed as offline player) named....`
