### ISSUE TITLE
Use asynchronous script reloading

### ISSUE THREAD

**Issue by carlodrift** [SkriptLang/Skript#1780]

**Comment by Pikachu920** [comment]
this is already supported though it is still beta. you can turn it on in the config

**Comment by bensku** [comment]
It's very unstable, though. Not like FAWE - it does not have a risk of corrupting your world - but Skript might crash.

**Comment by TheBentoBox** [comment]
This shouldn't have been closed because this really isn't "already supported". Perhaps there's another issue for it but there are a number of issues with the current implementation:

1. Unstable af like bensku said. It does seem to work ok for me in basic tests but I really haven't gotten that far into it.
2. I get log handler errors when reloading any scripts while the server is already running with async loading enabled. This is very likely a skript-mirror issue but it's worth mentioning.
3. The biggest issue of all: a lot of people control a lot of very important stuff with scripts so we can't afford to have the server actively running while the scripts load -- what we really need is async script RELOADING, not loading, and it should be a separate config option. You'll also not if you re-read the title that that's also what this issue is asking for. I've tested reloading scripts with async loading enabled and it seems to freeze the server all the same as without it enabled. I can take the +1 minute restart time, it's those regular multi-second hard freezes while the server is active that are the real killer.

**Comment by bensku** [comment]
Reloading should be asynchronous too, unless it got broken relatively recently. However, some tasks need to be done in server thread due to Bukkit.

**Comment by ham1255** [comment]
how I do turn it on?

**Comment by TheBentoBox** [comment]
Put `asynchronous script loading: true` in your config somewhere. Feel free to test and report back but I wouldn't use it on a live server yet.

**Comment by Matocolotoe** [comment]
That would be awesome if it was stable
