### ISSUE TITLE
bark block can't be checked

### ISSUE THREAD

**Issue by zeibo** [SkriptLang/Skript#1782]
**Ver. 1.13.2 | beta 2** (I can't use beta 6, it'll make my server crash lol)

I can set a block to an oak bark block, but I can't check that "if the blcok is an oak bark block".

that's my code
`on break:`
` 　 if event-block is an oak bark block:`
`　　if player is in region "sawmill":`
`　　　set event-block to stone`
`　　　wait 5 second`
`　　　set event-block to oak bark block`

**Comment by ShaneBeee** [comment]
there were LOTS of problems in the older beta builds.
Trying a higher beta may solve this issue. 
the devs aren't going to fix an older beta version (ie beta 2) since there have been 5 versions since that may have fixed this issue. 

You need to set up a test environment with the newest beta build, test it and if the problem persists then report it.
But it serves no purpose reporting an issue on an older version.
