### ISSUE TITLE
Looping entities and prepositions

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1798]
```
loop all entities in radius 6 around {locauto}:
			if loop-entity is a villager:
```
Why "loop-entity is villager" doesn't works and gives no error, but when I add "a" in front of "villager" it starting to works? It makes me kinda confused ; b

**Comment by Snow-Pyon** [comment]
Skript is treating the EntityData (villager) as something else and thus the comparison fails, it's hopefully an easy thing to fix.

**Comment by TPGamesNL** [comment]
Skript parses 'villager' as event-villager (just like it parses 'player' as event-player). Because not using an article in this context is incorrect English (and because the way Skript parses this currently (comparing the loop-entity with the event-villager) is a valid interpretation), I'm closing this.
