### ISSUE TITLE
Entities take damage after cancelling the explosion event

### ISSUE THREAD

**Issue by PerkusMaximus** [SkriptLang/Skript#1833]
### Description
When cancelling the `on explosion` event, entities seem to take damage, it didn't seem to do this before.

### Steps to Reproduce
```
on explosion:
	cancel event
```

### Expected Behaviour
I expected the explosion event when cancelled to completely cancel it, including the damage and sound from explosions.

### Server Information
* **Server version/platform:**       Spigot-1.13.2
* **Skript version:**                2.3.1

**Comment by PerkusMaximus** [comment]
Correct.

**Comment by bensku** [comment]
Does this still occur with latest Skript?

**Comment by SiebeDW** [comment]
Its still happening, you can view it in this video: https://streamable.com/rb9mp
But like @Blueyescat said this could be related to Spigot.

**Comment by Wealthyturtle** [comment]
Can confirm this still occurs on Skript 2.4-beta8

**Comment by ShaneBeee** [comment]
I wouldn't exactly label this as a bug, since its not a bug in any Skript code, this is an issue with Spigot. This has been reported to Spigot and md_5's response was as follows:

> This is basically a wontfix for me, because the explosion is called in two separate separate stages, and the blocks+event is only called in the latter stage.
Without completely changing the behaviour of the Minecraft server I don't see a way in which to combine these phases, that is explosion damages blocks before entities - somewhere, someone relies on this behaviour.
You can use EntityDamageByEntityEvent and the damaged entity will be the frame, and the damager will be the TNT.

**Comment by Wealthyturtle** [comment]
Oops my bad
