### ISSUE TITLE
doesn't contain

### ISSUE THREAD

**Issue by noy98** [SkriptLang/Skript#1838]
### Description

"doesn't contain" does not workd
### Steps to Reproduce

if lore of clicked item does not contain "hello"
### Expected Behavior

none

### Server Information
* **Server version/platform:**     1.12.2  
* **Skript version:**              2.3.2

**Comment by TheBentoBox** [comment]
This is because Skript's lore expression returns a list, and checking if the list contains a value will only return true if the exact value you pass in is within the list.

I'll pass to devs to see how they want to handle this; on my server, I implemented a `(has|doesn't have) lore` condition with skript-mirror which iterates the lines and checks for the provided text. Maybe something similar could be done in vanilla Skript.

**Comment by Snow-Pyon** [comment]
What about adding a new condition like:
```
(any|all) of %texts% contain %texts%
```
could be handy in this kind of situation.

**Comment by bensku** [comment]
Yeah, a new expression would be useful.
