### ISSUE TITLE
loop dropped items

### ISSUE THREAD

**Issue by chistian95** [SkriptLang/Skript#1848]
### Description
When looping dropped items, you can't get it's name, type or lore of loop-value. It always says "<none>"

### Steps to Reproduce
```
command /test:
	trigger:
		drop 1 dirt named "TEST_ITEM" at player
		wait 10 ticks
		loop all dropped items:
			set {_i} to loop-value's name
			broadcast "%{_i}%"
					
on item spawn:
	broadcast event-item's name
```

### Expected Behavior
To be able to gather loop item's name, and other data (metadata value doesn't work either)

### Errors / Screenshots
I see no errors in the log

### Server Information
* **Server version/platform:**      Paper-1596 (1.12.2)
* **Skript version:**                Skript 2.3.2

**Comment by TheBentoBox** [comment]
Because the thing you're looping is the dropped item entity itself, not the item it contains. For the dropped item to have a name you'd have to give the entity a name. The item and the entity are different things.

To get the item within the entity, use `item of %entity%`, so you'd change your line to `set {_i} to name of item of loop-value`.

**Comment by chistian95** [comment]
Okey I feel really dumb right now. Your solution works like a charm. Thanks :D

**Comment by TheBentoBox** [comment]
No worries, very easy mistake
