### ISSUE TITLE
give player minecart with TNT

### ISSUE THREAD

**Issue by TeAm6AZLIK** [SkriptLang/Skript#1907]
### Description

`!give player minecart with TNT`

Throws a error.

### Expected Behavior

Should give the player a minecart with TNT

### Errors / Screenshots

https://i.imgur.com/1b231St.png

### Server Information
* **Server version/platform:** git-Paper-493 (MC: 1.13.2)
* **Skript version:** 2.3.5

### Additional Context

When you use any minecart, minecart with TNT is working.

**Comment by HAHAYOUDEAD** [comment]
It's probably because of `case sensitive: false` in skript settings. TNT in aliases is written in upper case, if you change it manually to lower case it would work.

**Comment by TheBentoBox** [comment]
@HAHAYOUDEAD Case sensitive being false means it SHOULDN'T care about it being in upper-case, and I don't think that setting applies to aliases anyway.

[This alias should work](https://github.com/SkriptLang/skript-aliases/blob/master/transportation.sk#L32) and it's not version dependent. Not sure what's wrong here.

**Comment by HAHAYOUDEAD** [comment]
Ok, this option is not related, but it's something with case sensitivity, because alias `minecart[s] with tnt¦s` works fine, and `minecart[s] with TNT¦s` does not work outside alias file itself.

**Comment by TheBentoBox** [comment]
I wouldn't be surprised if the parser forcibly lower cases the input when the player enters an item type but the aliases aren't lowercased when parsed from the alias files, so even if you type it in the scripts as `TNT` the parser tries to parse `tnt` with case-sensitivity and there's no matching alias.

If that's the case, this could be fixed both alias-side and code-side; I'd argue it should be fixed in both places. If the aliases need to be in lowercase to be usable, the alias parser should lowercase them as it reads them.
