### ISSUE TITLE
Enhancement | Compatibiltiy with WorldEdit + cuboids

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#194]
Hello again!
I'm using Bensku's Skript since the 1.8 fix, and it's really great.

What I need now is support for WorldEdit (schematics), and cuboids.

Example:
`paste schematic "wooow" at location of player`

```
loop blocks between {location1} and {location2}:
    set loop-block to tnt
```

Could you add it?
I think it's not that hard and would be really useful.

Thank you!

**Comment by TheBentoBox** [comment]
SkStuff has support for WorldEdit schematic pasting. Your second example (the cuboid stuff) [is already support](https://www.skunity.com/expressions#Blocks).

**Comment by TrademarkTM** [comment]
The cuboid stuff is broken for 1.8+ (skQuery).
Also, I don't want to add 43576487 addons to Skript. I'm using it to add more cool stuff to plugins, not to remake them entirely.

I'm already using 3 addons, and I think that's enough...

**Comment by TheBentoBox** [comment]
The cuboid stuff is part of vanilla Skript, not SkQuery, it says so right on the documentation I linked. SkQuery also works fine on 1.8.

While it's up to Bensku what he wants to add, it does you no good to be dramatic. There's only about 10 or so somewhat worthwhile addons to install, all of which are lightweight and make Skript more powerful. The point of them is so you can add stuff to Skript as you need it, instead of EVERYTHING being in vanilla Skript. You're limiting yourself for no good reason by being stubborn about using addons. Three is nothing.

Also, installing an addon does not equate to "remaking plugins entirely". There's a very popular and good addon that already has the effect you want. And vanilla Skript doesn't tend to have hooks with most plugins anyways, stuff like that gets left for addons so Skript doesn't have a ton of soft dependencies.

**Comment by TrademarkTM** [comment]
As far as I know, this is not a cuboid: http://prntscr.com/cjlqfs
My code:
```
command /a:
	trigger:
		set {a} to player's targeted block
		
command /b:
	trigger:
		set {b} to player's targeted block

command /c:
	trigger:
		loop blocks between {a} and {b}:
			set loop-block to stone
```
Also, I'm using skQuery and it works fine. The cuboid expression causes a big error in Console.

"soft dependencies lol"
Skript works fine with/without worldguard but can loop blocks in a region (GriefPrevention/WG and some other plugins). Why not to add support for WorldEdit too? Who uses WorldGuard, actually HAVE TO use WorldEdit.

**Comment by TheBentoBox** [comment]
That's what a soft dependency is. It works fine without it but has features for it.

Not much else to say, different opinions right? Certainly not going to be against Bensku adding it but I think it's better to leave most plugin support for addons and Bukkit API support for vanilla Skript. There's not much that can be done if people are going to refuse to use addons that solve their problems.

**Comment by bensku** [comment]
You can make pull request for this if you wish...

**Comment by FranKusmiruk** [comment]
As said before, we have decided to move hooks off Skripts, and are currently not looking into adding more.
