### ISSUE TITLE
NPE when clicking outside the inventory.

### ISSUE THREAD

**Issue by Runakai1** [SkriptLang/Skript#1944]
So basically I am working on my script and everything is working fine. Yesterday I got an error saying exactly what the console error below does. I tried removing all the addons and see there, it still randomly occurs. It does not break anything at all, no server crash or internal server error. It just outputs an error.

It randomly occurs. I tried spamming the command and clicking the items in the inventory like crazy, didn't occur again. Even if I was doing nothing the error occurred once. The Error did not occur when I was using 2.3.5. 

Error: https://pastebin.com/Rk1JkFbs

Running 2.3.6 Skript on 1.13.2 Paperspigot

the only thing that could have caused the issue:

`event-slot != air`

**Comment by Blueyescat** [comment]
Happens when you click outside the inventory, because the inventory will be unknown. Also index of the slot will be -999, this should be handled too.

Also the latest change of [InventorySlot.java](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/util/slot/InventorySlot.java) is in 2.3.2.

**Comment by FranKusmiruk** [comment]
Thought we had checks for this already, guess that isn't the case.

**Comment by TheBentoBox** [comment]
Should be fixed in the latest releases.
