### ISSUE TITLE
The items not adding to chest.

### ISSUE THREAD

**Issue by OverBrave** [SkriptLang/Skript#1953]
### Description
The items not adding to chest.

### Steps to Reproduce
"add 1 stone to location of event-block"
or
"loop all items in victim's inventory:
	add loop-item to {_olsandık}"

### Expected Behavior
Adding items to the chest.

### Server Information
* **Server version/platform:**       1.13.2 PAPER
* **Skript version:**                2.3.6

**Comment by FranKusmiruk** [comment]
The first case is wrong since you can't add items to locations, only to inventories (adding items to blocks/players works as well since Skript handles it under the hood but that's about it). As for the second case, you either didn't provide the full code or that variable you've used there isn't set.

That said, unless you've got an actually valid case where this happens, I'll close the issue.

**Comment by OverBrave** [comment]
on rightclick on chest:
	if {sandık.ozel::%location of event-block%} is set:
		delete {sandık.ozel::%location of event-block%}
		chance of {@sanscik1}%:
			add {@miktar1} {@esya1} named "{@name1}" with lore "{@lore1}" to location of event-block
			message "{@sans2}"
		chance of {@sanscik2}%:
			add {@miktar2} {@esya2} named "{@name2}" with lore "{@lore2}" to location of event-block
			message "{@sans2}"
		chance of {@sanscik3}%:
			add {@miktar3} {@esya3} named "{@name3}" with lore "{@lore3}" to location of event-block
			message "{@sans3}"
		broadcast "{@acti}"

**Comment by FranKusmiruk** [comment]
That looks like an user error as I explained above. Ask for support in one of the Discord servers or the forums.
