### ISSUE TITLE
on inventory close

### ISSUE THREAD

**Issue by noy98** [SkriptLang/Skript#1957]
### Description

on inventory close event does not work

### Steps to Reproduce

on inventory close:
	if uncolored inventory name of current inventory of player contains "GUI설정":
		set {_splited::*} to uncolored inventory name of current inventory of player split at "-"
		set {_name} to {_splited::2}
		delete {gui.item.%{_name}%::*}
		set {_loop} to 9*{gui.line.%{_name}%}
		loop {_loop} times:
			add 1 to {_INT.%player%}
			set {gui.item.%{_name}%::%{_INT.%player%}%} to slot {_INT.%player%}-1 of current inventory of player
		send "{@p} &e&l%{_name}% &f&lGUI가 설정 되었습니다."

### Errors / Screenshots

it has to send message but does not work

### Server Information
* **Server version/platform:**    1.12.2   
* **Skript version:**             skript 2.3.6

**Comment by Blueyescat** [comment]
It doesn't send the message because the conditions aren't met. Run this to debug it, it will send the correct message for sure:
```vb
on inventory close:
	broadcast "%player% - %uncolored name of player's current inventory%"
```
Note that **`inventory name`** is not from Skript.

Also you didn't add your code into a code block, we can't see the indentations. https://guides.github.com/features/mastering-markdown/

So after all if you see that it is not a Skript bug, please close the issue.
