### ISSUE TITLE
Floor skull

### ISSUE THREAD

**Issue by DDuart** [SkriptLang/Skript#1967]
### Description
floor skulls doesn't work

### Steps to Reproduce
```vbs
on rightclick:
  if clicked block is skull:
    broadcast "ok"
```

### Server Information
* **Server version/platform:**       paper 1.12.2
* **Skript version:**                newet skript

### Additional Context

https://github.com/SkriptLang/Skript/issues/1965

**Comment by Efnilite** [comment]
@DDuart can you like post helpful stuff in an issue for once? What doesn't work? Does it not broadcast? 
What kind of skull is it??

**Comment by DDuart** [comment]
look at previous issue: https://github.com/SkriptLang/Skript/issues/1965

**Comment by MadPanCake** [comment]
I don't want to trash the issue post, but @DDuart, you should know that Skript developers don't get paid, they do Skript because they want to, for some reasons. It's their hobby or maybe they like the fact people use it and they feel passionate to improve Skript. That means they can't work on Skript all day because they probably have school, work to do and many other things, that's why they might not have enough time, or might just not want to test everything you say them for you. It's _you_ who is reporting the issue, so _you_ should provide necessary data. Respect Skript developers, and their time.

Good luck with fixing your issue too :)

**Comment by bensku** [comment]
Missing information, and OP didn't provide it in comments.
