### ISSUE TITLE
Decoding variables.csv

### ISSUE THREAD

**Issue by razethion** [SkriptLang/Skript#2018]
We were previously using a skript to create notes for players that we can refer to for any case. This was saving to the variables.csv file, and we would get variables like so:

jeepnote::qpeety::1 | string | 802254455354206279204D616C7573692061742031302F362F31372031323A323620504D
jeepnote::qpeety::2 | string | 8023424144206279204B6F737461735839382061742031302F382F313720373A303120504D

As I have coded a new notes plugin, we would like to move all of these notes to our new file format - however that string seems to be encoded and we need to decode it. How can I parse this text into plaintext?

**Comment by razethion** [comment]
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/variables/FlatFileStorage.java#L229-L244

Figured it out - it's hexadecimal

**Comment by FranKusmiruk** [comment]
If you're a developer, you could use Skript's API to do it.

Using `Variables.getVariable("jeepnote::*", null, false)` would return a Map<String, Object> where the key would be something like `jeepnote::qpeety::1` and the Object the String you're looking for. That might make porting them easier.

Otherwise, yeah, it's just hex-encoded strings.

**Comment by razethion** [comment]
@FranKusmiruk thatll save me some hell in google sheets. Thanks!
