### ISSUE TITLE
shoot {_firework}

### ISSUE THREAD

**Issue by Remixful** [SkriptLang/Skript#2036]
`shoot firework from {_loc}`

```
set {_firework} to firework
shoot {_firework} from {_loc}
```

The former works but not the latter.

### Server Information
* **Server version/platform:**      Paper-624 (MC 1.13.2)
* **Skript version:**                2.3.6

**Comment by TheBentoBox** [comment]
That's because you're setting the variable to the firework item, which can't be shot. If you'd like to dynamically shoot an entity type based on a variable, you could parse it as entity type either when setting it or when shooting it. For example:
```
set {_firework} to "firework rocket" parsed as entity type
shoot {_firework} from {_loc}
# OR
set {_firework} to "firework rocket"
shoot ({_firework} parsed as entity type) from {_loc}
```
However, the firework rocket alias could do with a `relatedEntity` tag to tie it to the firework rocket entity, which may additionally fix this issue, so I'll add that.

**Comment by TheBentoBox** [comment]
The latest releases for 1.14 should include the `relatedEntity` tag I described.
