### ISSUE TITLE
Help! When I type a custom skript command it shows unknow command!

### ISSUE THREAD

**Issue by CatCerYT** [SkriptLang/Skript#2057]
Hi, I want to say I'm no Skript expert.
And here is my skript: [https://pastebin.com/J9LZkRRW] 
Yes I have skript addons (same effect without them)
Skript version (2.3.6 and 2.3.5 both did not work)
I get no errors while loading the script. 
I even made a skript with only command and a trigger that broadcasts a message but that also didn't work. I would appreciate if someone would help me.

**Comment by Moderocky** [comment]
This isn't really the correct place for asking for help with a skript. You should probably ask on either SkUnity forums (a large unofficial skript community) or on one of the many skript discords. You can find both of these via google.

**Comment by TPGamesNL** [comment]
You should also look at console for startup errors or errors while running the command

**Comment by ShaneBeee** [comment]
When creating a new issue, there's a template for a reason.
Rather than deleting the template like you did, you should actually fill in all the info it is asking for, this way people can properly help you.

My guess is you are using an outdated version of Spigot. (We would know this is you followed the template you deleted)
Or you are probably using an outdated addon. 

If you watch your console when your server starts up you are most likely going to see an error with Skript loading, which is why your commands aren't working.

**Comment by CatCerYT** [comment]
Thanks for the help I found in the console errors while loading the scripts.

**Comment by SiebeDW** [comment]
Copy & paste the erros here
