### ISSUE TITLE
Firework support

### ISSUE THREAD

**Issue by Isabaella** [SkriptLang/Skript#206]
Hi, 

could you add fireworks? skQuery's are broken.

~ Bella

**Comment by JKGamerxD** [comment]
Afaik in the Gatt's SkQuery fix it's still working :P

**Comment by bensku** [comment]
Too much stuff to do, but maybe at some point.

**Comment by bensku** [comment]
Aliases rework added firework items, do we want to support playing effects too?

**Comment by Blueyescat** [comment]
Of course

**Comment by Snow-Pyon** [comment]
as long as you can shoot those, I'd say it's fine, that's what most people wants so.

**Comment by TheLimeGlass** [comment]
SkQuery's were broken because when Gatt edited the syntax, his system transformed the syntax marker symbol into an unknown symbol, thus the syntax forever being unreachable. My SkQuery edit fixed this a long time ago (Back in 2016) but this commit above merges it into Skript. (With SkQuery being compatible)

**Comment by Wealthyturtle** [comment]
Could someone close this issue? Firework support is already in Skript as of Skript 2.4+ :P
