### ISSUE TITLE
Data values not properly saved in database

### ISSUE THREAD

**Issue by xbxymax** [SkriptLang/Skript#2111]
There are problems when I try to use variables to store an item with a data value
Like storing a clown fish
`!set {test} to clownfish` 349:1
Close the server and restart after storage
`!give {test} to player`
What I got was a raw fish 349:0

Worse, it loses some NBT data
`set {test} to clownfish with nbt "{xbxy:""i35"",display:{Name:""fish""}}"`
When I restart the server, it will become
` {test} = raw fishwith with nbt "{display:{Name:""fish""}}"`

I also tested the enchanted golden apple, which will turn into a normal golden apple when rebooted

**Comment by CrazyWords1** [comment]
Skript version ?

**Comment by xbxymax** [comment]
skript 2.4
paper spigot 12.2

**Comment by bensku** [comment]
Data values should generally be persistent. That sounds like a bug.

Arbitrary NBT data cannot be saved, because Bukkit doesn't support NBT.

**Comment by xbxymax** [comment]
Currently you can store any NBT as long as it doesn't have a data value
I want to fix this without changing it, because I have a lot of NBT in my data...

**Comment by TheBentoBox** [comment]
I just want to note that ItemMeta DOES take not of NBT. It does not make it accessible or modifiable but if an item has custom NBT on it the ItemMeta will not be equivalent to meta for the same item but without the custom tag(s).

I don't really think this is an issue on our end but if we're doing anything conditional surrounding the serializing of item meta as it relates to data values that could be a potential cause of this sort of problem. But the fact that the name is still being saved implies otherwise.

**Comment by xbxymax** [comment]
The last version of skript I used was dev32
That's when I started storing NBT in the database.
The sudden upgrade to skript 2.4 has a lot going for it.
So I changed a lot of code, a few hundred kilobytes.
Maybe I should change my ways

**Comment by xbxymax** [comment]
I noticed that v2.4-alpha3 still has this problem...

**Comment by TPGamesNL** [comment]
A test example to replicate on newer Minecraft versions (because fishes and golden apple don't use data values anymore): double oak wood slab

**Comment by TPGamesNL** [comment]
`ItemData#blockValues` is transient, yet it is the only field containing a difference between 'double oak wood slab' and 'oak wood slab'

**Comment by Moderocky** [comment]
I believe(?) this has now been fixed upstream.
