### ISSUE TITLE
Try / Catch

### ISSUE THREAD

**Issue by Vrganj** [SkriptLang/Skript#2118]
### Description
Add a try scope, like an if / else. This could be used to check if a part of a script can't be used because it's an unknown effect, expression...

```vb
on mine:
    try:
        cancel drops
        give player drops of block with tool
    catch:
        send "No TuSKe :("

**Comment by TheBentoBox** [comment]
If possible this is a really neat idea. Interested in hearing what others think.

**Comment by Vrganj** [comment]
If possible, add an expression in the catch to see the error.

**Comment by Blueyescat** [comment]
Not a duplicate, but will use the same system. https://github.com/SkriptLang/Skript/issues/1449 - https://github.com/SkriptLang/Skript/issues/2037

And probably the other suggestions make more sense, because they don't allow whole a section to run. In the example given, if no TuSKe, `cancel drops` will not work but the next line will work. Yeah the other suggestions are more user friendly...

**Comment by TheBentoBox** [comment]
I was also thinking specifically of #1449 and do mostly agree that it makes more sense. Would like to see which one devs prefer between those two.

**Comment by TheBentoBox** [comment]
Adding tag to get attention to that. I personally lean towards #1449 like Blue, for what that's worth. I don't think it's worth implementing both this and that one but either of them could exist alongside #2037.

**Comment by bensku** [comment]
Try/catch is usually not what you use for conditionally loading code. At least, you're not supposed to use it for that.

**Comment by Vrganj** [comment]
Well, this one wouldn't only check if an addon was loaded, it would check for other errors too.

**Comment by bensku** [comment]
Checking for parse errors seems pointless. Unless I'm missing something, shouldn't you just fix them?

Checking for runtime errors would, IMO, be out of scope of Skript. Besides that, it would be *almost* impossible to implement with current Skript.

**Comment by Vrganj** [comment]
An expression to check if a plugin is loaded would be cool.

**Comment by Moderocky** [comment]
Yeah, I saw the addons one when I posted #2037, but I felt it needed to extend further than addons, since there are quite a few syntaxes (both in skript + addons) that require a particular plugin.

While it'd be cool to be able to just `try:` things, I feel like that would end up getting used to do unwise/deprecated things.

**Comment by Moderocky** [comment]
At the current time of writing we think try/catch is out of scope for Skript itself (but we may be able to provide an alternative soon) and the requested behaviour should already be covered by parse-if.
