### ISSUE TITLE
skript error when trying to install

### ISSUE THREAD

**Issue by NxthyWlz** [SkriptLang/Skript#2147]
hi there, i am new to skript and wanted to try it on my bungee network.
however, when i install skript(i have done it without other plugins and updated my java to the latest 64 bit) i get this error:

https://pastebin.com/74mgG1xF

i have tried and looked everywhere for other users with this issue and no luck. i have tried the discord but its the same story there. i hope someone could please help.

p.s skript is brand new install from jar with no files on, i did a full server restart, reload and tried loading with plugman but no luck there either

minecraft and spigot version 1.12.2 with the latest version of skript. i have also downgraded but no luck

**Comment by FranKusmiruk** [comment]
1. It's weird that it didn't load with a full restart but it won't load with plugman nor /reload either way, same goes for addons. I just mention this so you're aware, Skript isn't compatible with those kind of plugin reloading methods.
2. Did you install it on the bungee plugins folder? If so, it won't work since Skript isn't a bungeecord-compatible plugin, you've got to install it on each server individually.
3. Try increasing your stack size? Not sure why it'd throw a SOE specifically for you but see if that helps. The default stack size is 512kb, try increasing it to 1024kb with the flag `-Xss1024k`.

**Comment by NxthyWlz** [comment]
Yeah I didn’t think it would but I restarted every time. Just thought I’d
try those too. I didn’t put it in the bungee folder, it is on one of the
servers and I’m not sure what the third thing means I’m kind of new to
this, but the thing you’re talking about is set to xm1G

**Comment by NxthyWlz** [comment]
Also, I’d like to add I was using 32 but java on my 64 bit machine but I
changed to 64 but but now my plugins don’t seem to have the java logo and I
can’t open them with java, even though
nothing would happen if I did. Skript still doesn’t work but it does on my
single test server off the bungee network

**Comment by NxthyWlz** [comment]
It works now. I didn’t really do anything except redowbload the Sam version
of java but yeah. It works 😂😂
