### ISSUE TITLE
Database issue from entities

### ISSUE THREAD

**Issue by LoXR** [SkriptLang/Skript#2161]
### Description
In my server console it is spamming (every 10 seconds like it says)
[Skript] Cannot write variables to the database 'default' at sufficient speed; server performance may suffer and many variables will be lost if the server crashes. (this warning will be repeated at most once every 10 seconds) As I think its to do with Iron Golem farms being so much for it it to keep up with.

### Steps to Reproduce
Have a mobstack plugin, and an Iron Golem farm and watch it all go down. It'll drain the TPS but not fully.

### Expected Behavior
Be compatible and not so draining on server performance.

### Errors / Screenshots
No Errors or screenshots.

### Server Information
* **Paper version git-Paper-630**
* **Skript version 2.4-alpha3:**

**Comment by TheBentoBox** [comment]
Why would this have to do with iron golem farms? Skript has no interaction with them or mob stack plugins. The issue is that you're saving too many variable too rapidly across your scripts. If another plugin is interacting with Skript and saving way too many variables then we have no control over that, but it's most likely an issue on your end. You should look for ways to optimize the amount of variables you're saving. If you need help ask on the skUnity forums or one of the multiple Skript Discord servers.
