### ISSUE TITLE
List variable index goes lowercase

### ISSUE THREAD

**Issue by ghost** [SkriptLang/Skript#2163]
I didn't put this as a bug report, because it probably is a feature of Skript.

But anyway, I have a string with value of a player's name with some case variation (upper & lower) in it. When I put it in a list variable, for example `{_test::%{_playername}%}` it will go fully lower case when looping through it with %loop-index%. For example from _MdsCool_ it will be _mdscool_

Is there any way to stop this from happening?
I have already tried editing the config "case sensitive" option.

**Comment by TPGamesNL** [comment]
When you parse it as an offline player it will have the right case again

**Comment by MdsCool** [comment]
> When you parse it as an offline player it will have the right case again

The problem with that is when I put parsed offline player in the list it will revert back to a UUID.

**Comment by Matocolotoe** [comment]
All stuff in variables name become in lower case, you will have to work on what you get from the index

**Comment by FranKusmiruk** [comment]
> When you parse it as an offline player it will have the right case again
I don't recommend doing this, parsing offline players could be an extensive operation and thus hurt your server's performance. I'd recommend stop relying on the index to save the names. It's just not meant to be this way, you could use something like `set {_test::%uuid of player%::name} to player's name` and then `set {_test::%uuid of player%::value} to something`.

I'll leave the issue open since we do have an option to make variables case-sensitive and their string representation not following that doesn't make sense.

**Comment by Matocolotoe** [comment]
> When you parse it as an offline player it will have the right case again

Only if the player is online

**Comment by TheLimeGlass** [comment]
```vb
on script load:
	set {_lime} to "LimeGlass" parsed as offlineplayer
	set {_test::%{_lime}%} to true
	broadcast indices of {_test::*}
```
`case sensitive` option in config.sk does nothing being true or false. It'll always be lowercase.
