### ISSUE TITLE
Bugs with default variables

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/Skript#2174]
### Description
Default variables don't have (or keep) their default value in some cases.

### Steps to Reproduce
```
variables:
	{list1::%player%} = 0
	{list2::%object%} = 0

command /delete:
	trigger:
		delete {list1::*}
		delete {list2::*}
		message "&7&oDeleted"
```

#### Functions:
```
function test(p: player):
	broadcast "function variable ({list1::%{_p}%}): %{list1::%{_p}%}%"
	broadcast "function variable ({list2::%{_p}%}): %{list2::%{_p}%}%"

command /test:
	trigger:
		test(player)
```
returns
![image](https://user-images.githubusercontent.com/29547183/130412138-cd1353d4-f925-4aab-b015-5c6d4d1ebedb.png)

#### Commands / join events:
```
command /test: # same behaviour as join event
	trigger:
		broadcast "command expr ({list1::%player%}): %{list1::%player%}%"
		broadcast "command expr ({list2::%player%}): %{list2::%player%}%"
		set {_p} to player
		broadcast "command var ({list1::%{_p}%}): %{list1::%{_p}%}%"
		broadcast "command var ({list2::%{_p}%}): %{list2::%{_p}%}%"
```
returns
![image](https://user-images.githubusercontent.com/29547183/130412391-8d831a19-c20e-4f3f-9681-4a22847acb49.png)

#### Damage events:
```
on damage:
	attacker is a player
	broadcast "dmg expr ({list1::%attacker%}): %{list1::%attacker%}%"
	broadcast "dmg expr ({list2::%attacker%}): %{list2::%attacker%}%"
	set {_p} to attacker
	broadcast "dmg var ({list1::%{_p}%}): %{list1::%{_p}%}%"
	broadcast "dmg var ({list2::%{_p}%}): %{list2::%{_p}%}%"
```
returns
![image](https://user-images.githubusercontent.com/29547183/130412793-6a290c76-42ba-46f1-9ae5-06080446894d.png)

#### Deleting:
```
command /test:
	trigger:
		broadcast "cmd expr ({list1::%player%}): %{list1::%player%}%"
```
returns
![image](https://user-images.githubusercontent.com/29547183/130413112-90abb5d4-b7b6-4643-9099-a06d39f22aa7.png)
If you delete the specific index of that list (`delete {list1::%player%}` instead of `{list1::*}`), it will keep its default value.

### Expected Behavior
It should always return the default value of that variable, even if it's deleted, and for all expressions.

### Server Information
* **Server version/platform:** Paper 1.16.5
* **Skript version:** 2.6-beta2

**Comment by TheLimeGlass** [comment]
Did a long debug session. I'll tackle this again. Leaving this for notes as I need to take a break;

- It's not in the setting of the default variable. The ScriptLoader sets the default variable to `list1::<player>` and `list2::<object>` fine in the database. (The <> are TypeHints which helps the Variable/VariableString later)
- It's somewhere in this hell https://github.com/SkriptLang/Skript/blob/d09320866fa15bd6f2fc77b13f3e0cfd2c46ef36/src/main/java/ch/njol/skript/lang/VariableString.java#L201 which also goes through the SkriptParser. So Good Luck.
- The VariableString merges a bunch of crap into the `strings` List<Object> field so you have to loop through it and check if it's a String or an Expression because a user can do `{var::%player%::%string%::example}` which would set the List up to be String, Expression, Expression, String. (I'm unsure if it adds a String object `::` between the expressions). I just did a read through, next attempt will be runtime debugging.
- Default Variables don't set themselfs to the database until they're modified, so it returns the Variable object, also while keeping the TypeHint in the database until the script removes it from the default `variables:`.
-
