### ISSUE TITLE
%{%player%.etc.etc%}% displays as "<none>"

### ISSUE THREAD

**Issue by MINE64BUTTER** [SkriptLang/Skript#2178]
**My script is the following:**
```
every 1 second in "world":
	loop all players:
		set action bar of loop-player to "&7Stamina: &e%{%loop-player%.stamina.value}%&7/&6%{%loop-player%.stamina.max}%"
```
It shows no errors, and the value is set earlier in the code, but it displays as none.
Full code attached:
[Stamina.txt](https://github.com/SkriptLang/Skript/files/3304847/Stamina.txt)

**Comment by ShaneBeee** [comment]
This is an issue tracker for issues related to the Skript plugin, not a place to get help with your code. 
If you are needing support on how to write your code please use the skUnity forums or one of the many Skript discords.

The reason your variable is showing as none is because it was never set (see your join event) (hint: a variable can't be less than, greater than, equal to zero if it was never set)
