### ISSUE TITLE
Last Damage Cause Enhancement

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2192]
### Description

Currently, when you use the ```on death``` event, there are currently only a few event values available, like ```victim```, ```attacker```, ```event-damagecause``` and ```event-projectile```.

This does not allow for the accounting of some vanilla minecraft death messages, like for instance ```Player_A was burnt to a crisp whilst fighting Player_B```. With Skript at the moment, you can only "detect" that Player_A's death was caused due to fire damage, but not be able to find out about Player_B's involvement.

Therefore, my suggestion is to add a new event value to be able to get the last **player** damage cause, from attack, sweep attack, projectile, etc. Currently, Skript has a ```%livingentity%'s last damage cause``` expression, which can be modified to allow for ```%livingentity%'s last player damage cause```. That way, custom death message Skripts can now handle these damage cases.

**Comment by TheBentoBox** [comment]
As far as I can tell (someone correct me if I'm wrong) but this isn't possible because the Bukkit API doesn't have a separate getter/setter for the last damage caused specifically by a player as opposed to any entity. [See here](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html).

Additionally, your thinking here seems misguided. These sorts of complex death messages aren't only caused by players. If a player was burnt while fighting a zombie, it would give a similar sort of message (`Player was burnt to a crisp whilst fighting Zombie.`). So any script trying to recreate those sorts of messages would be inaccurate if they only did so for player-caused deaths.

If someone can point me to a bit of API I'm missing that allows for this I'll reopen it but otherwise if you really need this you should track it yourself.
