### ISSUE TITLE
Missing %minecraft name%'s for kelp and daylight detectors

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#2197]
### Description
The %minecraft name%'s for kelp and daylight detectors are missing

### Steps to Reproduce
(requires skript-mirror, but you get the idea)
```
import:
    org.bukkit.Material
    org.bukkit.inventory.ItemStack

function getMissing():
    loop ...Material.values():
        loop-value.isLegacy() = false
        set {_i} to new ItemStack(loop-value)
        minecraft name of {_i} is not set
        add "%loop-value%" to {_missing::*}

    broadcast "%{_missing::*}%"
```

### Server Information
* **Server version/platform:**       paper 1.13.2
* **Skript version:**               2.3.6

**Comment by ShaneBeee** [comment]
Aliases probably have been updated since then. As has been posted a few times now, bug reports are only accepted for latest versions of Skript.

When trying alpha-3 with 1.14.2 this is the outcome I get
``
> test
[13:48:25 INFO]: BAMBOO_SAPLING, POTTED_BAMBOO, POTTED_CORNFLOWER, POTTED_LILY_OF_THE_VALLEY and POTTED_WITHER_ROSE
```

**Comment by TheBentoBox** [comment]
Dangit GitHub

**Comment by TheBentoBox** [comment]
Technically (as Shane said) the aliases you're reporting issues with are already fixed but there are others missing that Shane mentioned here so marking this as the completed issue for tracking those on next release.

**Comment by ShaneBeee** [comment]
> Dangit GitHub

sorry that is my bad, I shouldn't have added (fixes <num>) to my PR, sorry about that
