### ISSUE TITLE
Week support in timespans

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#2220]
timespans should support week, month, and year, instead of just seconds, minutes, hours, and days.

**Comment by Blueyescat** [comment]
month is indeterminate

**Comment by Wealthyturtle** [comment]
This could be possible if Skript made the assumption that all months are 30 days and all years are 365 days although that may be slightly inconsistent

**Comment by Blueyescat** [comment]
It is better to left them to the user, but Skript needs some easy to use timespan utilities.

**Comment by TPGamesNL** [comment]
Something like `(ticks|seconds|minutes|...) of %timespan%` would be nice.

**Comment by TheBentoBox** [comment]
At the very least it could support weeks. Something in the config to determine the level at which timespans reach would be useful (i.e. allowing it to go up to weeks or years instead of the current days). As has been said, months are not a viable static unit of measurement. Years aren't quite either with leap years.
