### ISSUE TITLE
[Documentation] Banning a player doesn't automatically remove them

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2344]
### Description

When banning a player via skript's ban effect, the player will not automatically be kicked off the server. Instead, the player's ban will only really be noticeable once logged off

### Steps to Reproduce

```
command /test <player>:
    trigger:
        ban arg-1
```
Try running ```/test <your username>```, you will not be kicked off, but once you relog your ban will take effect

### Expected Behavior

The ban effect should include kicking the player off the server

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta5

**Comment by TheBentoBox** [comment]
This isn't a Skript issue, that's how bans work. You'll see plugins like Essentials are also [manually kicking the player](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandban.java#L58) after adding them to the ban list. These are separated by Bukkit intentionally so that you can ban someone without kicking them immediately so it takes effect from their next login onwards.

If you're using Skript to write a ban system and want your banned players to automatically be kicked, then you can just `kick player due to "%your ban reason%"`.

**Comment by Wealthyturtle** [comment]
Sorry. Did not know that that was intended behaviour... in that case, could the description of the ban effect be updated from “Bans/unbans a player or an IP address.” to “Bans/unbans a player or an IP address. Note that banning a player will not automatically remove them from the server, use the kick effect for that behaviour” or something along those lines? That way, it’ll be more clear @TheBentoBox

**Comment by TheBentoBox** [comment]
Sure, that seems like a fair change.
