### ISSUE TITLE
On villager trade return. 

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2348]
Welcome back again. A suggestion ehm. On villager trade return:
    Cancel event
Every 1 Minecraft day:
    Make villagers trade avaible again
    (Make Trade number 2 of clicked villager to unlocked?)
As clear said. Villager's trade should be cancelened and avaible after 1 Minecraft day.

**Comment by Pikachu920** [comment]
when would this event go off?

**Comment by Misio12320** [comment]
... When this code wont get wrote in scripts this event. E.g Might I would like to let villagers restore their trades at night.

**Comment by ShaneBeee** [comment]
> Welcome back again. A suggestion ehm. On villager trade return:
> Cancel event
> Every 1 Minecraft day:
> Make villagers trade avaible again
> (Make Trade number 2 of clicked villager to unlocked?)
> As clear said. Villager's trade should be cancelened and avaible after 1 Minecraft day.

Im a bit confused as to what exactly are you suggesting here. Is there some event equivalent in the Bukkit/Spigot API you are referring to?

I recommend using Skript-mirror to deal with Villager stuff, because the Villagers and their new trading system is quite convoluted and in my opinion, wouldnt fit well in Skript itself.

**Comment by FranKusmiruk** [comment]
@ShaneBeee as it has been said before, Skript's goal is to support pretty much everything the Spigot API supports, that includes the villager API as well. Though, there are issues open about supporting the villager trading stuff so if this isn't asking for anything that has been already asked before, I may close it.

**Comment by ShaneBeee** [comment]
> @ShaneBeee as it has been said before, Skript's goal is to support pretty much everything the Spigot API supports, that includes the villager API as well.

I understand that, hence why I said "in my opinion" as I feel this case in particular doesn't fit well. 
One could argue that "Skript's goal is to support pretty much everything the Spigot API supports" isn't true. It seems more like "Skript's goal is to support pretty much everything the Spigot API supports expect for what Snow doesnt want" ... Im not trying to argue here, but I've seen several suggested turned down because **you** don't see it fitting. 

Again, it was just my opinion I was expressing.

**Comment by Misio12320** [comment]
True. Well Skript is more for players not for entities and something ike this', for thing like this there are addons which allow do this'
