### ISSUE TITLE
Pre-flattening aliases break when one MC ID maps to multiple Bukkit materials (wheat, skull, etc.)

### ISSUE THREAD

**Issue by INTmAker** [SkriptLang/Skript#2394]
### Description
Skript aliases! Wheat aliases do not work!

### Steps to Reproduce
on break:
send "%event-block%" 

### Expected Behavior
 It should throw out "rise wheat" not CROPS when I break it. Same problem with skull.

### Errors / Screenshots
No console errors!

### Server Information
Spigot 1.12.2 latest
Skript 2.4-beta3

**Comment by ham1255** [comment]
get skript 2.4-beta5 cuase beta3 is old

**Comment by ham1255** [comment]
https://github.com/SkriptLang/Skript/releases/download/2.4-beta5/Skript.jar

**Comment by INTmAker** [comment]
Same problem

**Comment by INTmAker** [comment]
Please fix that

**Comment by awaffle1** [comment]
2.4-beta3 is so recent there really isn't a difference anyways. Will test this out later

**Comment by TheBentoBox** [comment]
Will investigate.

**Comment by TheBentoBox** [comment]
I've spoken with bensku about this and this is due to a single bug in how aliases work right now: they are unable to handle when one Minecraft ID maps to multiple different Bukkit materials. Currently there is no way to address this from the alias configs and it is handled in the code case-by-case. Hopefully the devs can address that limitation or make those overrides configurable in the future.

Point being, this isn't something I can fix and isn't an issue in the aliases themselves.
