### ISSUE TITLE
Quit/Disconnect event being cancellable

### ISSUE THREAD

**Issue by KingAlterIV** [SkriptLang/Skript#2444]
### Description

The quit/disconnect event is apparently cancellable.

### Steps to Reproduce

```
on quit:
	cancel event

on disconnect:
	cancel event
```
### Expected Behavior

A message related to "Event cannot be cancelled"

### Errors / Screenshots

https://i.imgur.com/NKeTXdo.gifv
https://i.imgur.com/3del7GB.gifv

### Server Information
* **Server version/platform:** 1.14.4, Paper-136       
* **Skript version:**2.4-beta5                

## Edit
May have figured it out. The PlayerKickEvent is linked with the PlayerQuitEvent and Skript is thinking that the PlayerQuitEvent is cancellable because the PlayerKickEvent is cancellable.
https://i.imgur.com/mm02je4.png
https://i.imgur.com/i0z8rcw.png

**Comment by ham1255** [comment]
hmm does skript output error when someone leaves?

**Comment by TheLimeGlass** [comment]
Njol acknowledged this 6 years ago https://github.com/SkriptLang/Skript/blob/5701dad3f600e91ed61c8086f34ec0c0f0a1c3eb/src/main/java/ch/njol/skript/effects/EffCancelEvent.java#L76

**Comment by Blueyescat** [comment]
After discussing about this with @OfficialDonut on Discord:

PlayerQuitEvent already includes kicks (probably it didn't on really old versions), so Skript doesn't actually need to listen to PlayerQuitEvent and PlayerKickEvent in the same time for the `on quit` event. The only benefit of that would be being able to use kick event related things in `on quit` **if it was actually a kick**, meaning `cancel event` in `on quit` is actually a correct thing because it fine works if it is a kick event; meaning this is not an issue.

However who would want to use the quit event to do something when a player is kicked? Did anyone even know this? Also there is no a condition to check whether it is kick.

If we remove `PlayerKickEvent` from the `on quit` event, everything should be fine.
