### ISSUE TITLE
Suggestion with suggestions 

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2482]
Hey. I have a suggestion:
1. On first death:
Event for first time after death of Ender dragon e.g.
2. On first time world enter: 
When entering first time another world than the first time joined (e.g nether) Add also:
Reset first join, reset first death of Ender dragon, on first time world enter. To reset these things for 1 or all players by command.

**Comment by Wealthyturtle** [comment]
> Hey. I have a suggestion:
> 
> 1. On first death:
>    Event for first time after death of Ender dragon e.g.
> 2. On first time world enter:
>    When entering first time another world than the first time joined (e.g nether) Add also:
>    Reset first join, reset first death of Ender dragon, on first time world enter. To reset these things for 1 or all players by command.

No. Those suggestions are out of Skript's scope.

By your logic, that means we should also have a ``first kill`` event, ``first mine`` event, ``first build`` event, etc. which is not possible.

We have a ``first join`` event, because it is supported by Spigot/Paper (see https://papermc.io/javadocs/paper/1.14/org/bukkit/OfflinePlayer.html#getFirstPlayed--), but we don't have any other ``first`` events.

**Comment by Misio12320** [comment]
Arlight them sorry for took your time. I haven't think about these "first time" things. I have searched everywhere in docs how to do on first time death of entity and haven't found so I came here and suggested, lol. Sorry gamer
