### ISSUE TITLE
Anvil Slots not settable

### ISSUE THREAD

**Issue by Runakai1** [SkriptLang/Skript#2493]
As the title already says Anvil slots are not settable using plain vanilla skript.

```
command anvil:
	trigger:
		open anvil inventory to player
		set slot 2 of player's current inventory to stone
		
command anvil2:
	trigger:
		set {_} to anvil inventory
		set slot 2 of {_} to stone
		open {_} to player
```

Anvil2 doesn't even open the inventory
However, anvil opens it but doesn't set the slot.

Using PaperSpigot and beta7 Skript.

**Comment by Blueyescat** [comment]
As far as i know, you can't set slots of a virtual anvil inventory neither the player can use it, at least without NMS.

---
About the second issue, seems correct. Opening an inventory stored in a variable doesn't work.
```vb
command /test:
	trigger:
		set {_x} to chest inventory
		send "%{_x}%" # chest inventory
		open {_x} to player
```

**Comment by Wealthyturtle** [comment]
Can someone test if ppening an inventory stored in a variable doesn't work?

**Comment by TPGamesNL** [comment]
Code above doesn't work because the variable is set to the inventory type 'chest inventory', not to a newly created inventory. Opening an inventory type directly was added in https://github.com/SkriptLang/Skript/pull/3765 (tested with code above, works), but I'm still closing as that wasn't what this issue was about.
