### ISSUE TITLE
Support for minecraft's native IDs and data

### ISSUE THREAD

**Issue by bluelhf** [SkriptLang/Skript#2547]
### Description

Since Skript aliases are mapped to Minecraft's IDs anyways, I think it'd be a great (yet time-consuming) enhancement to allow players to use minecraft's native IDs as a replacement for aliases.

**Comment by ShaneBeee** [comment]
I'm curious why you feel this should be added?
In my opinion it serves no purpose, but I would love to hear a case as to why this would be needed.

Here is why I vote no, you can easily create your own aliases within a script using your own aliases, ex:
```vb
aliases:
	my item = minecraft:stone

command /test:
	trigger:
		give player 1 of my item
```

**Comment by bluelhf** [comment]
@ShaneBeee
- It would clear confusion about aliases for people who've been using the native alias system for a while 
- Skript wouldn't have to deal with mapping arbitrary strings to IDs
- Aside from the big ID changes in the introduction of blockstates, IDs have stayed fairly similar for many versions, and I believe they will in the future => less work for Skript developers

**Comment by ShaneBeee** [comment]
> Skript wouldn't have to deal with mapping arbitrary strings to IDs

Are you meaning abolish the alias system all together?
Personally I think this will never happen. If you look at the aliases, theres a lot of really weird specific things, ex: stairs, because they have many states, including up/down, direction, waterlogged. That said a user would have to know all the different block state types, ie:
```vb
set block at player to minecraft:oak_stairs[waterlogged=true,half=top,shape=inner_left]
```
etc...
Ps, I had to spend a few minutes going thru the aliases to figure out block data for stairs, this just goes to show it wouldnt be a very easy system to deal with for users.

IF you were suggesting the addition of this (on top of aliases), I would understand, but straight up abolishing the alias system I feel would be a no go. 
At the end of the day, it would break every single script out there, plus it would make using items extremely difficult.

**Comment by Wealthyturtle** [comment]
Abolishing the current alias system is definitely not a good idea... however if you mean adding Minecraft native IDs as an alias to Skript, e.g. ``minecraft:diamond = diamond``, then I think that's valid

**Comment by bluelhf** [comment]
@ShaneBeee I don't mean abolishing the current system. Sorry for any confusion!

**Comment by ShaneBeee** [comment]
> @ShaneBeee I don't mean abolishing the current system. Sorry for any confusion!

No need to apologize, but thank you for the clarification.

**Comment by bensku** [comment]
I'm not sure if this is a good idea, because Minecraft ids change between versions.
