### ISSUE TITLE
Rework of the website

### ISSUE THREAD

**Issue by Olyno** [SkriptLang/Skript#2561]
The rework of the [Skript's website](https://skriptlang.github.io/Skript/index.html) will contain these issues:
 - [x] #611
 - [x] #1253
 - [x] #1429
 - [x] #1598
 - [x] #1184
 - [x] #2425

Please post your suggestions or ideas about this rework here.

(This issue is a improvement and continuity of #2506)

**Comment by noftaly** [comment]
idk if this is valid, but: #2543

**Comment by Olyno** [comment]
> idk if this is valid, but: #2543

I don't really know if it's possible so I will add it if we can do it

**Comment by Olyno** [comment]
Website available here: https://olyno.github.io/skript-website/

**Comment by bensku** [comment]
Looks great! Aside that, there are a few issues you could look at:
1. [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Folyno.github.io%2Fskript-website%2F) reports a rather low score on mobile, and can't reach 100 even on desktop. Since better mobile support was one of goals of this change, I feel this is quite important. Current website scores 100 on both mobile and desktop, and is currently usable (but ugly) on mobile (except Safari).
2. Core functionality does not work without Javascript. Core functionality does not include search or other dynamic content.
3. [External links](https://olyno.github.io/skript-website/documentation/events/) to documentation pages do not work (tested on Firefox 70, Linux). This is probably most critical of the issues, and I suspect it is related to issue 2.

**Comment by Olyno** [comment]
> PageSpeed Insights reports a rather low score on mobile, and can't reach 100 even on desktop.

Page speed has been fixed:
 - Mobile: 90
 - Desktop; 100

I think not I can make a better performance than that because the new website requires images that the old doesn't.

> Core functionality does not work without Javascript.

Agree, but it's what I call a modern website. The main issue you have when you don't use these tools (as ReactJs, VueJs or here SvelteJs) is that you must copy paste the same thing everytime you need it. The strength of theses technologies is what we call ``reusable components``. You create a component and can reuse it everywhere you need it. Each components can have values insides when render, and takes only 1 line to add. When you edit 1 component, it edits everywhere you use it (so a big gain of time).
That's the reason why I will not remove Javascript here because it will be stupid. You require a lot of time Javascript (as documentation pages) in this website.

> External links to documentation pages do not work

What do you mean? I don't see what you mean. Do you have any screenshot to show me what you are talking abouit please? It could be more easily for me to see what's wrong here.

**Comment by bluelhf** [comment]
@Olyno Maybe use the latest github release and parse the redirect url to get the version to show in the "Download latest" button instead of manually setting it?

(Use `https://github.com/SkriptLang/Skript/releases/latest/`, wait for it to redirect, then split the url by `/` and get the last element)

**Comment by Olyno** [comment]
> @Olyno Maybe use the latest github release and parse the redirect url to get the version to show in the "Download latest" button instead of manually setting it?
> 
> (Use `https://github.com/SkriptLang/Skript/releases/latest/`, wait for it to redirect, then split the url by `/` and get the last element)
> 
> Oh, and replace `Bukkit platform` with `Spigot and Paper platforms` in the description of Skript on the main page

I will have a look in, thanks for your suggestion!

**Comment by bensku** [comment]
@Olyno My suggestion would have been to use server side rendering. It seems you did exactly that, because the site now works without Javascript. It also loads much faster and external links to it appear to be working.

All in all, I think the website is ready. We can start figuring out how we'll be replacing the current site with it. Thanks for great work!

**Comment by APickledWalrus** [comment]
A few things I noticed:
- The main description should be updated, especially now that the website includes tutorials (description says it does not).
- The text on the color picker is not completely within the white box (it is a little below) and some text is moved it seems (see below)
- The color picker seems to be cut off by the scrollbar.

![image](https://user-images.githubusercontent.com/29044720/71646149-1caaa380-2cb1-11ea-92d5-8998137d84b8.png)

**Comment by Olyno** [comment]
> The text on the color picker is not completely within the white box (it is a little below) and some text is moved it seems (see below)

Unlucky for me, the color picker is a ``component`` that I didn't create, so I can't edit it

The other things will be fix soon!
