### ISSUE TITLE
SUGGESTION: More Random Things

### ISSUE THREAD

**Issue by ThatOneN00b** [SkriptLang/Skript#2577]
I Was thinking, you should add more random features! E.G:  `give player a random item` or `set {_block} to a random block excluding bedrock`

**Comment by ShaneBeee** [comment]
this is already a thing:
`random element of all items`

**Comment by Misio12320** [comment]
But his suggested alias is better and easier than yours @shanebeee

**Comment by Wealthyturtle** [comment]
Closing this issue as you can already select random items/blocks, and it would be laggy to select a random block or item. Do you know how many items there are? Not just the base items, but their variants too.

**Comment by bensku** [comment]
Randomization doesn't get slower when there are more options.

**Comment by TPGamesNL** [comment]
It could be an idea to something like `[a] random %*type%`, which would work for some types with a small amount of values, such as boolean, gamemode. cat type, biome, color, enchantment etc. This could also be created for stuff like items or integers.

**Comment by Misio12320** [comment]
> It could be an idea to something like `[a] random %*type%`, 
Which is much harder to understand. 





> such as boolean, gamemode. cat type, biome, color, enchantment etc. This could also be created for stuff like items or integers.

If talking about this. Teleport player on random biome,spawn random cat type, give player x with random enchantment

**Comment by Wealthyturtle** [comment]
Sorry, what I meant to say was that for random items, it doesn't really make sense. There's so many items and blocks in Minecraft that it really isn't logical. 

For example, using the hypothetical ``random item`` expression might give you a diamond one time, and another time give you a feather, or a bat spawn egg. It's even worse for the hypothetical ``random block``, since it could also give you "bad" blocks like op said - bedrock, or heck even the nether portal and end portal block.
