### ISSUE TITLE
event "at time" , need to be rewrite

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#2661]
### Description
The event "at time" work but not as expected

### Steps to Reproduce
```cs
at 23:55:
	broadcast "step1"

at 23:59:
	broadcast "step2"
```

### Expected Behavior
If I do "set time to 23:59", the broadcast "step2" is not executed, but if I do "set time to 23:55", the first broadcast is send, then the second.

The problem is that WE HAVE TO set the time lower or equal to the minor time event.

So the calcul of the event "at time" should be fix to allow this 

### Server Information
* **Server version/platform:**       Paper1.14.4
* **Skript version:**                Skript2.4Beta10
* **Other plugins/addons:**                  None

**Comment by ham1255** [comment]
https://github.com/SkriptLang/Skript/releases/tag/2.4.1

**Comment by Wealthyturtle** [comment]
This occurs for basically every situation where you can set the condition for an event to fire...

If you damage an entity, the on damage event will also not fire. The reason why it fires if you set the time to 23:55 is because after a few seconds it will reach 23:59, which will then properly fire the event, because the time was incremented by the server automatically as per Minecraft mechanics.
