### ISSUE TITLE
add tempban effect in 2.5

### ISSUE THREAD

**Issue by Jayderp** [SkriptLang/Skript#2667]
how it works:
tempban %player% [(by reason of|because [of]|on account of|due to) %string%] (with (length|duration)|to (durate) the length of) %timespan%

**Comment by Jayderp** [comment]
it will temporarily ban the specified player for the length of a specified timespan, if there is no timespan it will return an error

**Comment by ShaneBeee** [comment]
In my opinion, rather than adding a new effect, I would like to see an optional time span added to the current ban effect.

ex: 
Current ban effect:
`ban %texts/offline players% [(by reason of|because [of]|on account of|due to) %text%]`

Proposted change:
`ban %texts/offline players% [(by reason of|because [of]|on account of|due to) %text%] [for %timespan%]`

**Comment by Jayderp** [comment]
> In my opinion, rather than adding a new effect, I would like to see an optional time span added to the current ban effect.
> 
> ex:
> Current ban effect:
> `ban %texts/offline players% [(by reason of|because [of]|on account of|due to) %text%]`
> 
> Proposed change:
> `ban %texts/offline players% [(by reason of|because [of]|on account of|due to) %text%] [for %timespan%]`

good idea

**Comment by Zulfen** [comment]
yeah sounds good
