### ISSUE TITLE
Log Handlers Error

### ISSUE THREAD

**Issue by qtt509** [SkriptLang/Skript#2671]
Occurs when opening a server
why is this?

![캡처](https://user-images.githubusercontent.com/58448722/70013598-915bc680-15bb-11ea-8e67-f295dc2a679b.PNG)

**Comment by ShaneBeee** [comment]
1) When creating a bug report, please dont delete the template, actually fill it in. We need to make sure we get all the proper info when trying to triage a bug.

2) This issue is caused by using an older version of skript-mirror, please update to skript-mirror 2.0.0
https://skripttools.net/dl/skript-mirror+2.0.0-SNAPSHOT.jar

**Comment by qtt509** [comment]
Thank you ..!
