### ISSUE TITLE
Item aliases of blocks are not working in 2.4

### ISSUE THREAD

**Issue by ghost** [SkriptLang/Skript#2672]
### Description
1. All the aliases for item version of blocks like doors, banners, etc (like _iron door item_) are not recognise as item in all 2.4 versions (alpha1 to beta10)
2. All the aliases for block version of items like doors, banners, etc are not recognise  as item in all 2.4 versions (alpha1 to beta10) **after** a reload of the script, not at startup.

### Steps to Reproduce
```
command cmd:
    trigger:
        give dirt to player
        give iron door to player
        give iron door item to player
```
=>
```
[Skript] 'iron door item' can't be added to a player because the former is neither an item type, an inventory nor an experience point (test.sk, line 5: give iron door item to player')
```

```
sk reload test
```
=>
```
[Skript] 'iron door' can't be added to a player because the former is neither an item type, an inventory nor an experience point (test.sk, line 4: give iron door to player')
```

### Expected Behavior
Give a dirt block and two iron doors.

### Errors / Screenshots
![unknown](https://user-images.githubusercontent.com/16658055/70087101-ecb9a300-1613-11ea-86f8-963f41327a1f.png)

### Server Information
* **Server version/platform:**       Spigot and PaperSpigot 1.14
* **Skript version:**                2.4-alpha1 to 2.4-beta10

### Additional Context
An other user did this test with 2.4-beta5 on Spigot 1.14.4 and had the same result.

**Comment by ShaneBeee** [comment]
Have you tried this on the latest release? (Skript 2.4)

Also to note, `iron door item` is not an alias for MC 1.13+ (only for 1.12.2 and below)


What I did notice though is this, If I use the following code:
```vb
command /test:
    trigger:
        give iron door to player
```
I get no errors and everything works fine.

If I use this code:
```vb
command /test:
    trigger:
        give iron door to player
        give iron door item to player
```
I get the following error:
```
[12:40:57 ERROR]: 'iron door item' can't be added to a player because the former is neither an item type, an inventory nor an experience point (test.sk, line 26: give iron door item to player')
```
This is due to that alias not existing. 
What I did notice which is odd, after reloading the script again, I get this error
```
[12:42:38 ERROR]: 'iron door' can't be added to a player because the former is neither an item type, an inventory nor an experience point (test.sk, line 24: give iron door to player')
[12:42:38 ERROR]: 'iron door item' can't be added to a player because the former is neither an item type, an inventory nor an experience point (test.sk, line 25: give iron door item to player')

```
It shouldn't be erroring for `iron door`
After delete the `iron door item` line, I still get this error:
```
[12:43:17 ERROR]: 'iron door' can't be added to a player because the former is neither an item type, an inventory nor an experience point (test.sk, line 24: give iron door to player')

```
Its almost as if adding an improper alias, causes other aliases to break. 
If I reload the aliases, then reload the script it works fine (as long as I never use an improper alias)
It seems there is some odd conflict somewhere.

**Comment by Tai1er** [comment]
No, I didn't test it with 2.4. I did my test two days ago and I didn't have time to post the issue.
The result is the same with 2.4.
