### ISSUE TITLE
Reload Error

### ISSUE THREAD

**Issue by qtt509** [SkriptLang/Skript#2678]
error when typing"/sk reload scripts"
why this is?

Minecraft: 1.12.2 Paper
Skript: 2.4

![캡처](https://user-images.githubusercontent.com/58448722/70370381-09065a00-190a-11ea-91d4-7b9ea6c22469.PNG)

**Comment by Wealthyturtle** [comment]
This error just indicates that your server froze because the Skript parser took too long to parse something. This could mean that the parser is stuck on some line(s) in your script(s) and therefore is freezing up the server. Try and look out for long lines within your scripts that could cause this issue.
