### ISSUE TITLE
give item to me does not work

### ISSUE THREAD

**Issue by GovindasOM** [SkriptLang/Skript#2710]
### Description
!give a diamond axe to me

^ does not work, while it is even an example on the documentation
![image](https://user-images.githubusercontent.com/16716020/71255106-b713fa00-2335-11ea-8fb5-0e7c16ed5a8f.png)

Error: 
me can't have anything added to it

### Server Information
* **Server version/platform:** 1.12.2 Paper
* **Skript version:** 2.4

**Comment by Runakai1** [comment]
I hope you're using this in in-game effects. Not as an skript effect in a file

**Comment by TPGamesNL** [comment]
> ### Description
> !give a diamond axe to me
> 
> ^ does not work, while it is even an example on the documentation
> ![image](https://user-images.githubusercontent.com/16716020/71255106-b713fa00-2335-11ea-8fb5-0e7c16ed5a8f.png)
> 
> Error:
> me can't have anything added to it
> 
> ### Server Information
> * **Server version/platform:** 1.12.2 Paper
> * **Skript version:** 2.4

Can confirm, a temporary workaround would be `inventory of me`.

**Comment by bensku** [comment]
Me refers to command sender, which may be console that cannot have items added to it. Not very intuitive, though.

**Comment by CHarcoalToast** [comment]
If its sole purpose is being used in effect commands, the ‘player’ expression always worked for me.

**Comment by Matocolotoe** [comment]
`give a diamond axe to me's inventory` works

**Comment by TheLimeGlass** [comment]
`give a diamond axe to me's inventory` works because Skript uses the CommandSender converter when referencing another separate expression, to convert the `me` to a Player for the inventory. It doesn't work directly using just `me`, because it would go through the EffChange class, and the change class doesn't utilize the converters, or comparators https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/effects/EffChange.java#L154-L161

Fixes include. A.) Making EffChange lookup converters B.) Make the changer of the ExprMe class the DefaultChanger entityChanger if the command sender is a player, but we can't determine if it's a player during parsing time. C.) Do the same thing as B, but to the CommandSender classinfo, or D.) Separate the `console` from the `me` expression since there is already a `console` literal.
