### ISSUE TITLE
Removing health from a mob doesn't show damage

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#2754]
### Description

When you use "remove x from entity's health", you can't see the entity taking damage.

### Steps to Reproduce

1. Load this script:
```
on rightclick:
	remove 2 from clicked entity's health
```
2. Click on a mob; you'll see nothing. If you repeat clicking, the mob will die.

### Expected Behavior

In 2.4.1, you saw the mob was taking damage. So there's a little bug. :)
### Errors / Screenshots

N/A

### Server Information
* **Server version/platform:**      Paper 1.15.1 build 43
* **Skript version:**                2.5; it does work on 2.4.1

### Additional Context

N/A

**Comment by TheBentoBox** [comment]
I don't see how this is a bug... you're not damaging the entity, you're just modifying the health. It's often really useful to be able to modify the health like that without the entity visibly taking damage.

If you want to damage it, why not just use `damage`?

**Comment by Wealthyturtle** [comment]
To be clear, this change happened because my patch changed the way HealthUtils handled damage application. In the past, it damaged the entity directly (behaviour you are expecting), which can cause issues in certain cases. Try using the damage effect instead, and if that still has issues please open another issue, thanks.

**Comment by Anoniempje1234** [comment]
The damage effect doesn't show the damage either.
