### ISSUE TITLE
Cannot write variables to the database ???

### ISSUE THREAD

**Issue by short509** [SkriptLang/Skript#2758]
### Question

A yellow warning message displays on the console.
Why is this?

![캡처](https://user-images.githubusercontent.com/27778635/72225449-f77b3680-35c8-11ea-82db-f8319d0ce036.PNG)

**Comment by ShaneBeee** [comment]
That means you are attempting to write way too many variables in a short amount of time.
Depending on your system, you should limit yourself to less than 1000 variables a second.

**Comment by short509** [comment]
> That means you are attempting to write way too many variables in a short amount of time.
> Depending on your system, you should limit yourself to less than 1000 variables a second.

Is this a problem?

![캡처](https://user-images.githubusercontent.com/27778635/72225691-a587e000-35cb-11ea-9b87-f39b0ba4dde7.PNG)

**Comment by ShaneBeee** [comment]
yes, because the size of your offline player count could be high and you are clearing too many variables. You should be deleting them not clearing them.

Anyways Im closing this as there is no issue here. If require assistance with this further please use either the forums (skUnity forums) or one of the discords for Skript assistance (you can find these on the main page of this repo)
