### ISSUE TITLE
Very High Timings

### ISSUE THREAD

**Issue by CaoTrongThang** [SkriptLang/Skript#2801]
My server is running on PaperSpigot 1.15.2 latest version (86)
Using Skript 2.5

Please fix this timings, look so scare :( 
https://timings.aikar.co/?id=df16669d5c724cfb879b6042e4b82da3#timings

**Comment by ShaneBeee** [comment]
There is absolutely no information here for us to fix any issue.

**Comment by TheDGOfficial** [comment]
Like said in the above, there is no information for any issue, and it probably not a **Skript** problem; but rather a problem in your **scripts**. If you want to find which specific scripts (and even triggers, lines) just open the `plugins/Skript/config.sk` file and change `enable timings: false` into `enable timings: true`.

It tracks your scripts and reports it to Paper's Timings V2, but remember to make it back `enable timings: false` after you get the timings link because it may cause extra overhead since your scripts are tracked for performance and reported into Timings V2, which will normally not the case since the config option is false by default.

You'll need a /sk reload config or server restart (_not reload_) to make config option changes update. Most config option changes should update after doing a /sk reload config but some of them may only update after a restart. I'll suggest a restart to make sure it updates.

You can then analyze the timings link and optimize linked scripts, triggers and lines yourself or post it here. If the problem is not in a simple script, I'll suggest getting help from forums and Discord, since this an issue tracker to track down actual issues in the Skript plugin, performance is also an issue but it generally caused by people abusing Skript and/or doing complex operations with it.

**Comment by Wealthyturtle** [comment]
Skript isn't causing much lag **past the first few minutes where the server starts up**. From experience, the task
```
Skript::Task: ch.njol.skript.Skript$2 (Single)count(1)  total(22.95% 4.606s, 418.72% of tick)
```
Is the Skript parser that parses all your scripts when Skript is loaded. This will often always result in the main server thread being frozen if your scripts are complex enough.

As TheDGOfficial and ShaneBeee have said, apart from the limited information given to us there's not much else. If you can get a better timings report that actually shows significant lag from Skript + enabled script timings, then we can actually examine further.
