### ISSUE TITLE
Trident Dupe

### ISSUE THREAD

**Issue by rudde0** [SkriptLang/Skript#2815]
Paper-99, Skript 2.4.1

https://youtu.be/gOj1fxeCRTs

**Comment by ShaneBeee** [comment]
So you delete the template, don't bother giving us code, or any useful info but a video?

Sorry but I have no clue what is going on here, not sure if this is a Skript issue, Spigot, Paper, MC, really no clue. 
Some details would be nice.

Next time you open an issue please fill out the template rather than deleting it, and provide some proper info.
