### ISSUE TITLE
Loop all items on chest

### ISSUE THREAD

**Issue by LeCraft2Ouf** [SkriptLang/Skript#2830]
Hello, I am trying to recover the contents of the trunk which is located under the panel, I am giving you my code: `on click:

	if target block is a sign:
		if line 1 of target block is "&6[BUY]":
			if block at block under clicked block is a chest or trapped chest:
				loop all items in block under clicked block:
					send "%loop-item%"`

Here is what he gives me instead of telling me the items in the trunk, he tells me which slot are to be used in the trunk.
![Capture](https://user-images.githubusercontent.com/29964590/75171403-dc552800-572b-11ea-8b2f-6b53e4b89cfc.PNG)

**Comment by Nicofisi** [comment]
Hmm I would say this perhaps is not a bug, this is probably just something that doesn't work intuitively, sorry! There is probably some syntax to get the items placed in those slots. Have you tried asking on some forums or on Discord?

*I could be wrong.*

**Comment by LeCraft2Ouf** [comment]
I asked on Skript-MC, I tested different code but it doesn't work, it also finds no solution.

**Comment by LeCraft2Ouf** [comment]
This returns "Inventory slot 0 of LeCraft2Ouf ":
`Loop 36 times:
    Send "%slot loop-number -1 of player's inventory%"`

`Loop all items in player's inventory:
    Send "%loop-item%"`

But this works:
`Loop 36 times:
   Set {_s} to slot loop-number -1 of player's inventory
   Send "%{_s}%"`

Incomprehensible.

**Comment by Wealthyturtle** [comment]
This has always been Skript behavior for a long time. This exists because when you loop items in an inventory you don't actually get an item - you get a slot (allowing you to grab the slot index + the item). If you want to send the actual item in chat or whatever, you'll need to either store it in a variable (forcibly converting it to an item) and print it back out, or pass it through a function, etc. I don't think that there's currently any syntax to get the item from a slot without using automatic converters.

**Comment by Virdex** [comment]
type of loop-item 

- daje ci nazwe itemu jak by coś
