### ISSUE TITLE
Format gui slot effect doesn't work when player in variable.

### ISSUE THREAD

**Issue by TUCAOEVER** [SkriptLang/Skript#2845]
### Description

Format slot doesn't work when the player is a variable.

### Steps to Reproduce

```bash
format gui slot of {_p} with black stained glasses # nothing happens, that's bad
format gui slot of "%{_p}%" parsed as player with black stained glasses # it works, that's good
```

### Expected Behavior

Both should work.

### Server Information
* **Server version/platform:** Paper 1.14.4 "latest"
* **Skript version:** 2.4 

### Additional Context
I could confirm it's an issue with Skript itself, not with the Tuske addon.

**Comment by JRoy** [comment]
You've provided no error, you've not followed the issue template. Additionally that doesn't look like skript syntax

**Comment by TUCAOEVER** [comment]
> You've provided no error, you've not followed the issue template. Additionally that doesn't look like skript syntax

No error.
Just difference between {_p} and "%{_p}%" parsed as player
Those syntax belong to skript.

**Comment by TUCAOEVER** [comment]
https://github.com/SkriptLang/Skript/issues/2823#issuecomment-588174655

**Comment by Nicofisi** [comment]
Edited OP to follow the template.

*By the way, for your information @TUCAOEVER, it's Paper, not PaperSpigot, it had a rebranding a long time ago.*

**Comment by ShaneBeee** [comment]
@TUCAOEVER 
could you please try to replicate this issue on a newer release of Skript.
Since 2.4 we have had 2.4.1, 2.5-alpha1 and recently 2.5-alpha2

All bug reports submitted, should be referencing either the latest stable release or the latest alpha/beta release, as issues may have already been fixed.

**Comment by ShaneBeee** [comment]
### Update:
I tried your code (had to modify it a bit since `glasses` is not a thing), here is what I used:
```vb
function gui(p: player):
    open virtual chest inventory with size 1 named "&aTEST GUI &62" to {_p}
    format gui slot of {_p} with black stained glass
    format gui slot 3 of {_p} with green stained glass

command /test1:
    trigger:
        set {_p} to player
        open virtual chest inventory with size 1 named "&aTEST GUI &61" to {_p}
        format gui slot of {_p} with black stained glass
        format gui slot 3 of {_p} with green stained glass

command /test2:
    trigger:
        gui(player)
```
### Environment:
Paper 1.15.2 + Skript 2.5-alpha2

### Results:
![](https://i.imgur.com/5Olq3Ag.png)
![](https://i.imgur.com/37JRzis.png)

### Summary:
As you can see, both commands worked just fine.
I'm closing this issue as I can not replicate this. I also know plenty of other people that use Tuske GUIs and have not seen this issue.
