### ISSUE TITLE
server lagg

### ISSUE THREAD

**Issue by AggerTV** [SkriptLang/Skript#2881]
### Description

I was told by my server host, to contact you, as skript takes out a lot of my servers usage.

### Expected Behavior

My server is extremely laggy

### Errors / Screenshots

a 1 hour long timings from my server
https://timings.aikar.co/?id=b847fbffa7be48569d08e14fcd57f863

### Server Information
* **git-Paper-1617 (MC: 1.12.2)**       
* **Skript version 2.4.1**

**Comment by ShaneBeee** [comment]
The thing with Skript is, its just a medium between the Skripter (you) and the server.
Skript by itself won't cause lag.

Looking at your timings, your lag is caused by using periodical events.
<img width="1580" alt="Screen Shot 2020-03-25 at 1 58 12 PM" src="https://user-images.githubusercontent.com/20008482/77584859-c65c9380-6ea0-11ea-8b67-ce6e4bc4ca6f.png">

This is more of a user error than a Skript issue.
For example, If I write some extremely inefficient code, of course my server is going to lag.
A prime example is users using periodical events, looping all players and setting their scoreboard lines to data from variables. Naturally the more players online = the more lag. 

There isn't much Skript can do about this. Its all about writing efficient code on your end.

**Comment by ShaneBeee** [comment]
Oops, I didn't see it was already closed (clearly im blind)

**Comment by Jayderp** [comment]
should've gone to specsavers
