### ISSUE TITLE
ExpSpawnEvent works before other events.

### ISSUE THREAD

**Issue by vhone** [SkriptLang/Skript#2915]
### Description

I would like to add some condition to FishingEvent as the code below.
But the ExpSpawnEvent works ahead of FishEvent, even though the experience is not dropped.
Also, when you catch fish, you get experience, but the ExpSpawnEvent doesn't work.

### Steps to Reproduce

```skript
options:
	ID: onFishingEvent

on unload:
	loop all fish hooks:
		kill loop-projectile
	delete {{@ID}::*}
	delete {{@ID}.hooker::*}
	
on right click:
	player is holding fishing rod
	set {_pu} to uuid of player
	set {{@ID}::%{_pu}%::used} to true
	
on fishing:
	set {_p} to player
	set {_pu} to uuid of player
	if {{@ID}::%{_pu}%::used} is set:
		clear {{@ID}::%{_pu}%::used}
		if {{@ID}::%{_pu}%::lure} is alive:
			if {{@ID}::%{_pu}%::bite} is set:
				if fxOnFishingCatch( {_p}, {{@ID}::%{_pu}%::lure} ) is false:
					cancel event
				else:
					clear {{@ID}::%{_pu}%::bite}
					clear {{@ID}::%{_pu}%::lure}
					set {{@ID}.hooker::player} to player
			else:
				fxOnFishingFail( {_p}, {{@ID}::%{_pu}%::lure} ) is false
				cancel event
		else:
			fxOnFishingThrow( {_p} ) is false
			cancel event
	else:
		{{@ID}::%{_pu}%::bite} is not set
		if fxOnFishingBite( {_p}, {{@ID}::%{_pu}%::lure} ) is false:
			cancel event
		else:
			set {{@ID}::%{_pu}%::bite} to true
			wait 1.6 seconds
			clear {{@ID}::%{_pu}%::bite}
	
on shoot:
	shooter is holding fishing rod
	set {_pu} to uuid of shooter
	{{@ID}::%{_pu}%::lure} is not alive
	set {{@ID}::%{_pu}%::lure} to projectile

on exp spawn:
	send "ExpSpawnEvent : exp=[%spawned exp%]" to console
	cancel event
	
on item spawn:
	send "ItemSpawnEvent : item=[%event-item%]" to console
	
function fxOnFishingThrow(p:player) :: boolean:
	send "fxOnFishingThrow" to console
	return true

function fxOnFishingFail(p:player,lure:projectile) :: boolean:
	send "fxOnFishingFail" to console
	return true

function fxOnFishingBite(p:player,lure:projectile) :: boolean:
	send "fxOnFishingBite" to console
	return true

function fxOnFishingCatch(p:player,lure:projectile) :: boolean:
	send "fxOnFishingCatch" to console
	return true
```

### Expected Behavior

Throw the fishing rod,
When a fish bites
I caught a fish.

### Errors / Screenshots

![캡처](https://user-images.githubusercontent.com/59043053/78917226-8ebd3080-7ac9-11ea-8efc-86eba4ce3f59.JPG)

### Server Information
* **Server version/platform:**        1.15.1 paper
* **Skript version:**                 2.5 alpha3

### Additional Context

ExpSpawnEvent works for reasons that are unknown without fishing.
Spawned exp was none.

**Comment by Wealthyturtle** [comment]
Hmm... that seems to be the case because the ExperienceSpawnEvent isn't actually a "real" event fired by Paper, but is actually being fired by Skript itself.

https://github.com/SkriptLang/Skript/blob/f0100a75ffacbe27ce7218ec5a86738642ecaeda/src/main/java/ch/njol/skript/events/EvtExperienceSpawn.java#L113

**Comment by Wealthyturtle** [comment]
I'm not sure if the ExperienceSpawnEvent can be reworked to fire after the PlayerFishEvent, as that might require a large-ish code rework (not entirely sure)

However, looking at the source code, if you cancel the exp event (which you did in your script), it will also cancel the fish event's exp, so that issue is on your side.

As for the ExperienceSpawnEvent firing even when there's no xp being dropped, I think it's a bit miseleading for Skript users, and it could be reworked to not fire at all if there's no xp being dropped from the various experience event sources.

**Comment by APickledWalrus** [comment]
This is a bug as there is exp being dropped, as can be seen by using `event-experience`
