### ISSUE TITLE
Getting the item name inside a chest.

### ISSUE THREAD

**Issue by 83y** [SkriptLang/Skript#2924]
I cant seem to get the item name inside a chest on 1.15 Skript it only gets the inventory slot and direction of the chest not the actual item name. This works on 1.12 Skript but not 1.15 Skript.

I have seen this post but I do not really understand it: https://github.com/SkriptLang/Skript/issues/2830

![Desktop Screenshot 2020 04 12 - 21 00 12 84](https://user-images.githubusercontent.com/55250446/79078495-a92d1f00-7d00-11ea-9a72-87c4bd37a083.png)

**Comment by ShaneBeee** [comment]
Which line are we looking at here?
Which version of Skript are you using?
`This works on 1.12 Skript but not 1.15 Skript.` <-- these aren't Skript versions, these are Minecraft versions.

Your issue report is missing some integral information, namely because you deleted the issue template rather than filling it in.

That said, I don't believe there is a Skript issue here, I just see this as user error.
