### ISSUE TITLE
Can't give item in slots 31-35

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2929]
### Description

When giving an item to a player with the `give` effect, which can't stack on existing items, and which has to go in slots 31-35, nothing happens.

### Steps to Reproduce

1. Fill your inventory with some random item and let slots 31-35 empty
2. `!give stone to player`

### Expected Behavior

The item should appear.

### Errors / Screenshots

No errors.

### Server Information
* **Server version/platform:** Spigot 1.14.4       
* **Skript version:** 2.5-alpha3               

### Additional Context

The following effect works : `set slot 31 of player to stone`

I investigated the problem further, and found that in the `ch.njol.skript.aliases.ItemType` class :
![image](https://user-images.githubusercontent.com/42092549/79586616-a9973280-80d1-11ea-9a3b-d6cdeaea4e1d.png)

Removing the `- 5` at L824 fixes it, but might cause other important issues with inventories since the code becomes really stupid (that's why I didn't open a PR) :
![image](https://user-images.githubusercontent.com/42092549/79586645-b451c780-80d1-11ea-88e3-ef371ec38752.png)

**Comment by ShaneBeee** [comment]
In my opinion this is a no from my.
Why? Because this is intended. 
IF you were to use Bukkit's `PlayerInventory#addItem()` the item would not go into the inventory.
Same goes for Minecraft's `/give` command. I believe the item would drop on the ground.

The inventory slots were intended to hold inventory items and not fill when giving an item to said player.

On top of that, if we were to open that up, what happens when the player's legging slot is free, and we attempt to give the player an oak log? Clearly it can't go in that slot. This would just end up giving us more trouble than anything else.
The only things that can go in most of those slots are armor items, therefor you should be setting the slots rather than adding to the inventory.

I'm going to close this as I feel its not something Skript should be doing, but if another dev feels they would like to open it, we can carry on another discussion at that point.

**Comment by situu11** [comment]
Still doesn't works...
