### ISSUE TITLE
How to get worldguard flag with skript?

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2988]
How can you get the flag of a worldguard region with skript? I think this should be implemented if not possible, yet.

**Comment by ShaneBeee** [comment]
WorldGuard stuff has been discussed many times, due to the different version between their regular WorldGuard and FAWE's WorldGuard, and also the differences between version 6 and 7, it doesn't make sense to expand on this.
Anything relating to WorldGuard should be done in an addon and not in Skript itself.
Snow has mention in the past he would prefer to remove WorldGuard support from Skript and move it to an addon.
That said, no this feature will not be added.
