### ISSUE TITLE
Sk-Perm throwing error when adding perms to player

### ISSUE THREAD

**Issue by JaguarPlugins** [SkriptLang/Skript#3017]
### Description
Conole is throwing a "Something went horribly wrong" error when adding perms to the player with Sk-Perms (and the player doesn't get the permission).

### Steps to Reproduce
add "sihnpet.queenbee" to player's permissions

### Expected Behavior
Player is given the permission sihnpet.queenbee

### Errors / Screenshots
[console error](https://gist.github.com/JaguarPlugins/6e6c67dfb261cd684e431a2071d92ddc)

### Server Information
* **Server version/platform:**       Paper Spigot 1.15.2
* **Skript version:**                2.4.1

### Additional Context
- Using **LuckPerms** as permissions plugin
- The sihnpet permission hasn't come with a plugin, it's one we've made to use in tandem with a pets plugin

**Comment by ShaneBeee** [comment]
1) This issue tracker is for Skript, not addons. Please report issues with addons to the respective developer of said addon
2) I'm the dev of SkPerm. SkPerm no longer works with LuckPerms due to LP changing their entire API, and I have looked thru their new API and can not figure out how to adapt it, therefor I will not be updating SkPerm to work with LP 5+
