### ISSUE TITLE
damage cause in on damage of player not working for campfire or lava fire

### ISSUE THREAD

**Issue by rudde0** [SkriptLang/Skript#3022]
```
on damage of player:
	if damage cause is drowning or contact or fire:
		send "damage cause is fire" to victim
```
Contact on sweet berries and drowning are working but fire is not working.

### Server Information
* **Server version/platform:** Paper 322
* **Skript version:** 2.5 Alpha 3

**Comment by Wealthyturtle** [comment]
Try ``burning``. It's different from ``fire``.

**Comment by rudde0** [comment]
same

**Comment by Wealthyturtle** [comment]
I'm not sure, did you try using both at the same time?
```... or burning or fire```?

**Comment by Wealthyturtle** [comment]
I was able to replicate a comparison issue though,

```
on damage of player:
	if damage cause is lava or contact:
		send "damage detected" to victim
```
Doesn't work for detecting lava damage

But
```
on damage of player:
	if damage cause is lava:
		send "damage detected" to victim
```
Works for some reason.

**Comment by APickledWalrus** [comment]
![image](https://user-images.githubusercontent.com/29044720/95028151-32982b00-066c-11eb-85de-61e5cd025e07.png)
Looks like there are some (major?) conflicts going on here. The two conditions are being parsed like
```
if the damage cause is equal to lava pop (visual effect) OR contact (damage cause)
if the damage cause is equal to lava (item)
```
There is a comparator for `DamageCause - ItemType`, so that's why the second conditions works.
