### ISSUE TITLE
Biome

### ISSUE THREAD

**Issue by Endergamer20011** [SkriptLang/Skript#3065]
Make an on biome change: and make an if biome change and make change biome to BIOME

**Comment by ShaneBeee** [comment]
How exactly would we do that?
There is no event for biomes changing, since biomes do not change, they're only changed when a plugin changes them. 

We can't really add events for every time a plugin modifies the server. 
Ie: Take block changes, plugins can change blocks, but no event is fired for this.

**Comment by Endergamer20011** [comment]
Okay, I didn't understand everything with Google translation, but can you make it possible to change the biome?

**Comment by Pikachu920** [comment]
you can do that already: `set biome at player to desert`

**Comment by Endergamer20011** [comment]
and we can do from one coordinates to another?

**Comment by Wealthyturtle** [comment]
At the moment you cannot set a range of coordinates to a particular biome, but you can loop the coordinates and set it manually inside the loop.

**Comment by Endergamer20011** [comment]
Okay thanks you
