### ISSUE TITLE
Skript 2.5 b2: testing event-entity is player does not work in survival mode when using on combust event

### ISSUE THREAD

**Issue by CraftyZombie** [SkriptLang/Skript#3336]
### Description
When using the "on combust" event, in survival mode, the test for "event-entity is a player" fails.

### Steps to Reproduce

1. Set the game mode to survival

2. Create a simple skript with the following:

```
on combust:
    if event-entity is a sheep:
        broadcast "Burning sheep!!!"
    if event-entity is a player:
        broadcast "Burning man!!!"
```

3. Create a fire and walk into it to initiate burning.

### Expected Behavior
The server should have broadcasted "Burning man!!!" when the player combusted. If the game mode is creative, this is what happens, but not in survival. 

### Server Information
* **Server version/platform:** 1.16.1 / Paper
* **Skript version:** 2.5 beta 2

**Comment by ShaneBeee** [comment]
I did some testing, this is not a Skript issue, this is actually a Bukkit issue.
Appears this event is not called for players. Im not sure if this is intentional or not.

**Comment by ShaneBeee** [comment]
Ok, after further testing, this does work:

Test Code:
```vb
on combust:
    broadcast "&aSkript event fired: %event-entity%"
    if event-entity is a player:
        send "&aSkript IS A PLAYER"
```

Result (when going in lava)
<img width="966" alt="Screen Shot 2020-08-26 at 9 47 37 PM" src="https://user-images.githubusercontent.com/20008482/91385496-e09af480-e7e5-11ea-8964-4eb5bbb818f4.png">


Further more, a player entering fire acted a little differently.

It appears the players "fire ticks" are at -20, and the event does not call until its at -1... ergo 1 second into the player being in said fire.

<img width="854" alt="Screen Shot 2020-08-26 at 9 50 43 PM" src="https://user-images.githubusercontent.com/20008482/91385726-66b73b00-e7e6-11ea-9a5e-f158aa8e347a.png">
<img width="854" alt="Screen Shot 2020-08-26 at 9 51 14 PM" src="https://user-images.githubusercontent.com/20008482/91385737-6ae35880-e7e6-11ea-99c2-8be53dc70226.png">


Im not sure why its done like this, but its out of Skript's hands, since the event is called late for some reason!

**Comment by TPGamesNL** [comment]
It's probably caused by Minecraft not actually setting you on fire until you are in fire for more than 1 second. If you step in fire for less than a second, it'll show that you're on fire, but the fire will stop as soon as you step out.

**Comment by CraftyZombie** [comment]
@ShaneBeee Thank you for looking into this.

So I went ahead and tested the code you provided:

```
on combust:
    broadcast "&aSkript event fired: %event-entity%"
    if event-entity is a player:
        send "&aSkript IS A PLAYER"
```

This code only works for me when the player is in creative mode, just like the original code I had posted. When in survival mode, the event never triggers.

I then tried removing the `player` test to see if the event itself was firing and it looks as if the `on combust` event never triggers in survival mode.

Does the following code trigger for you in both survival and creative mode?

```
on combust:
    broadcast "&aSkript event fired: %event-entity%"
```

**Comment by ShaneBeee** [comment]
I modified it a little bit:
```vb
on combust:
    broadcast "&aSkript event fired: %event-entity% :: %gamemode of event-entity%"
```
but yes, it gets called both in survival and creative mode. Only difference was in survival mode it took a second before the event was fired.

<img width="966" alt="Screen Shot 2020-08-29 at 6 32 17 PM" src="https://user-images.githubusercontent.com/20008482/91649190-0ca4b880-ea26-11ea-9c2a-18720fda536f.png">
<img width="966" alt="Screen Shot 2020-08-29 at 6 32 28 PM" src="https://user-images.githubusercontent.com/20008482/91649195-11696c80-ea26-11ea-9b3f-219df381a211.png">
