### ISSUE TITLE
Long aliases causing stack overflow error (I think)

### ISSUE THREAD

**Issue by Inversil** [SkriptLang/Skript#3390]
### Description
Once every 24 or so hours, skript refuses to load this skript.

### Steps to Reproduce
I have a multipurpose skript that breaks blocks in a 3x3 radius using a lore check. It only breaks the block types that belong to the tool. I couldn't really find a way to check for a wide variety of blocks other than making a long alias.
Even though it might use a bunch of extensions like SKbee and skUtilities (which I know you don't provide support for), it seems it's the main skript jar that's crashing, which is why I'm creating this issue thread. 

[customaxe snippet.txt](https://github.com/SkriptLang/Skript/files/5261148/customaxe.snippet.txt)

### Expected Behavior
No Regex crash in the compiler when loading the skript. 
When it doesn't get stuck crashing, the skript works fine and behaves as intended.

### Errors / Screenshots

This is the error that shows up when doing reloading skript after the crash. The same/a very similar error shows up when the skript works as intended, as well as when the initial turning point happens when it no longer works.
Crashing error: https://pastebin.com/nzdcT0j5
Loading and working fine error: https://pastebin.com/NMGdXiTy

### Server Information
Server: Paper versioon git-Paper-130 (MC: 1.16.1)
(the same thing also happens on both newer and older versions of paper)
Skript Version: 2.5-beta4

### Additional Context

none

**Comment by Inversil** [comment]
I removed a bit more unrelated code from the skript file

**Comment by ShaneBeee** [comment]
1) Your lines are insanely long, and Skript cant handle this. I wouldn't classify this as a bug, I would classify this as user error/inefficient coding.
2) Some of your aliases make no sense.
ex:
```vb
	woodtype = oak log, spruce log, birch log, jungle log, acacia log, dark oak log, stripped oak log, stripped spruce log, stripped birch log, stripped jungle log, stripped acacia log, stripped dark oak log, minecraft:oak_wood, minecraft:spruce_wood, minecraft:birch_wood, minecraft:jungle_wood, minecraft:acacia_wood, minecraft:dark_oak_wood, oak planks, spruce planks, birch planks, jungle planks, acacia planks, dark oak planks, crimson planks, warped planks, crimson stem, warped stem, stripped warped stem, stripped crimson stem, mushroom stem, red mushroom block, brown mushroom block, oak leaves, spruce leaves, birch leaves, jungle leaves, acacia leaves, dark oak leaves
```
most of this could be cut down, ex:
```vb
woodtype = any log, any bark, any leaves, any planks
```

3) There are already aliases for these blocks:
```vb
 minecraft:oak_wood, minecraft:spruce_wood, minecraft:birch_wood, minecraft:jungle_wood, minecraft:acacia_wood, minecraft:dark_oak_wood, 
```
https://github.com/SkriptLang/skript-aliases/blob/95dcc1eb0b206024576fd37a60283be0cb74734c/building.sk#L288

Personally I would just close this issue, since this isn't a Skript issue, this is just inefficiently written code. 
Im going to leave it open and mark it as "dev required" so the rest of the team can put their input before deciding whether or not to close.

**Comment by Inversil** [comment]
Yea this is definitely my fault. Is there a better way to check for a large selection of blocks? The wood isn't even really the problem. 
I looked around for ways to test for all blocks where the correct tool is a pickaxe, but I couldn't find anything like that.

**Comment by ShaneBeee** [comment]
After talking with the dev team on discord, I decided to close this.
The use of aliases in this manner is extremely inefficient. This is why the aliases have groups.

Please see the examples and link I gave you to see the currently written aliases and groupings for block types.

Also, if you are not already doing so, please ensure to use 64bit java. I know that 32bit java has a lot more issues with regex, but at the end of the day, a line with 2000+ characters is going to bring some trouble.

While yes this is technically a Skript issue, and shouldn't throw errors, we are marking this as a "won't fix" since this is an extremely rare case scenario due to inefficient coding.
