### ISSUE TITLE
Can't check if item has NO name applied - Beta 4

### ISSUE THREAD

**Issue by Leonardo-Fiori** [SkriptLang/Skript#3405]
I used this line of code to check if player had X regular diamonds (that had no special name or lore):
`if arg-player has arg-number of diamonds named "":`

After updating to beta 2, beta 3 i started to get this error when loading the skript:
`the 1st argument of diamond named "" is not an item type (atm_diamond.sk, line 233: if arg-player has arg-number of diamonds named "":')`

After updating to beta 4 the error is gone, **but the syntax is still not working**! I am trying to report this since a month... am I the only fool out there in the need to remove unnamed items from inventory in an efficient way?

### Steps to Reproduce
As simple as this code:
![image](https://user-images.githubusercontent.com/25549272/94337468-c756b500-ffea-11ea-9b1f-733332bf93d2.png)

### Expected Behavior
Only UNNAMED items should get removed

### Errors / Screenshots
There are no errors in beta 4
Here is a small video to explain what's happening https://youtu.be/rvMvsi-3akQ

### Server Information
* **Server version/platform:** Paper-199 1.16.3
* **Skript version:** 2.5-beta4

**Comment by ShaneBeee** [comment]
After investigating this more and more, I'm not sure if I would classify this as a bug.

The reason this "worked" before was due to an old bug. Therefor it wasn't supposed to "work", you were just relying on the product of another bug. This bug was fixed, therefor giving the illusion of a new bug, when in reality this isn't actually a bug.

I'm not sure that this can be "Fixed" without causing more comparison issues. 
I will leave this open and mark it as "dev needed" to see what the rest of the team thinks about this.

**Comment by APickledWalrus** [comment]
I think this is actually a bug.

The condition itself works fine. It only passes when you have an unnamed diamond in your inventory. It’s the removal part that isn’t working right, as it removes any item instead of an unnamed diamond.

**Comment by Leonardo-Fiori** [comment]
To me also the condition does not work that good, as you can see in the video https://youtu.be/rvMvsi-3akQ

Checking for a name to be "" is not that elegant solution... but what are the alternatives now? Looping 2 times the inventory every time the user needs to sell a single diamond? That's way less elegant.

Maybe it's time to add a new condition? "has arg-number of unnamed diamonds" 😄
