### ISSUE TITLE
Tab Complete the /skript command

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#3531]
/skript [reload|enable|disable] should have tab completions of all of the scripts
I did this with skbee:
```
on tab complete:
    event-string is "/skript" or "/sk"
    set tab completions for position 1 to "reload", "enable", "disable", "update" and "help"
    set tab completions for position 2 to all scripts
```

**Comment by TheDGOfficial** [comment]
Yes, it can be useful. Also, reload and disable should only tab complete enabled scripts, while enable tab completing only disabled scripts. It should require a permission however, since not every server admin may want to show their script file names. Should also support script names with space and starting with an existing argument (i.e /sk reload aliases test.sk conflicting with /sk reload aliases), witch may not be easy.

Also adding tab complete for script commands without an addon would be nice. Maybe tab complete default arguments? (i.e  ``command /hello <text=world>:`` will tab complete the first argument with "world") Or provide a tab-completer section that accepts a function name as parameter? (example function signature: ``function onTabComplete(sender: command sender, command: string, alias: string, args: strings) :: strings:``)
