### ISSUE TITLE
Please update the Bukkit Skript version to the latest

### ISSUE THREAD

**Issue by yandelplayz** [SkriptLang/Skript#3550]
A lot of server hosting websites allow Skript to be added as a plugin, but there are many that do not allow "external" downloads that are not from spiggotmc or bukkit this is a huge problem for server developers that the server host doesn't allow custom plugins, even though Skript is allowed as a plugin, its not the latest one, the latest version of Skript that is allowed on most server hosting is Skript 2.1.2, and is incompatible with versions like 1.16.x or 1.12.2 . so please update the Bukkit version to the latest possible.

**Comment by ShaneBeee** [comment]
That page on Bukkit is owned by Njol, and has no affiliation with us. 

Since your host oddly refuses to download plugins from sites other than Spigot/DBO, I recommend switching to a host that does not limit you.

**Comment by BluewyDev** [comment]
I'm an aternos moderator and not officially affiliated as an employee
Aternos would be the host he means.

It's not odd, aternos simply can't add plugins from github or others as aternos doesn't have anything to connect to like they have with spigot or bukkit. Spigot, with use of spiget for example let's aternos automatically fetch and update plugins. That's not possible with github.

**Comment by ShaneBeee** [comment]
> I'm an aternos moderator and not officially affiliated as an employee
> Aternos would be the host he means.
> 
> It's not odd, aternos simply can't add plugins from github or others as aternos doesn't have anything to connect to like they have with spigot or bukkit. Spigot, with use of spiget for example let's aternos automatically fetch and update plugins. That's not possible with github.

Theres a difference between can't and won't. This is a won't situation right here.
GitHub has an API for getting things from repos. 
https://developer.github.com/v3/repos/contents/

As I've already stated, we do not manage that page on Bukkit that OP is referring to.

**Comment by BluewyDev** [comment]
https://board.aternos.org/thread/40036-less-limits-to-where-the-plugins-can-come-from/?postID=138429&#post138429

The whole github stuff is explained in here by an actual employee
![unknown-10](https://user-images.githubusercontent.com/34064010/99377284-50d98380-28c6-11eb-88af-9ac9e09d0866.png)

**Comment by ShaneBeee** [comment]
Im not really sure why you are sending it to us here. 
Our resource is currently distributed and completely accessibly by literally thousands of users.

If Aternos chooses not to download from GitHub, that is an Aternos issue, and not an issue of the plugin developers. 

I've talked to many plugin developers who are consistently harassed by the Aternos community because "we can't get your plugins" ... this is 100% the choice of Aternos and how they choose to run things and where they choose to download from.

If Aternos wishes to download from GitHub, they most definitely can. All that picture tells me is "GitHub does not offer the data we need so we have chosen not to download from GitHub", so I repeat, this is the choice of Aternos.

If you have any further issues with this, please discuss this with the Aternos team, as this issue tracker is reserved for issues with Skript, the plugin itself, and issues with your server deciding it won't download it.
