### ISSUE TITLE
player in function

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#3567]
right now if you have something like
```
function hi(player: player):
    send "hi!"
``` 
you get an error, instead you have to `send ... to {_player}`
IMO if there's 1 player parameter, it should treat it as the player in the function, so you can do anything as you normally would in a command trigger or event, etc.

**Comment by ShaneBeee** [comment]
In another issue (the async one) you stated "We should do X because most languages do X"
But in this issue you're going in the opposite direction, stating that Skript should just assume what is in the parameter. 

Well, in any language, you would have to use the parameter object in your code as well,
example in java
```java
public void hi(Player player) {
    player.sendMessage("hi");
}
```
What happens when a new users tries to do something like:
```vb
function hi(player: text):
    send "hi"
```
Then they are still going to get the error for "no player in a function event"

In my opinion this goes totally against how functions work, and in my opinion it should stay the way it is. 

Again, my opinion is not a final decision on the matter. Lets see what others have to say.

**Comment by APickledWalrus** [comment]
I agree with Shane on this. I think it'd be better to keep it how it currently is.

**Comment by AyhamAl-Ali** [comment]
After discussing with the team, it's most likely not going to happen as it will cause more confusion therefore the issue will be closed.
