### ISSUE TITLE
logical operators

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#3583]
we should be able to use logical operators:
`if x or x:` would be `if (x || x)`
and `if x and x:` would be `if (x && x)`
so,
```
if player is op and {rank::%player%} is "admin":
```
```
if player has permission "donator" or {rank::%player%} is "donator":
```

**Comment by Mwexim** [comment]
This is due to the horrific way Skript conditions work. They are jot expressions, but rather separate structures. 

Achieving this would need one of the following two:
1. Regex-patterns, which would not be desired since they can clutter parsing, but this is a valid workaround.
2. Overhaul the conditions-system completely, but that’d require a huge rewrite. This has been suggested before, but it’s such a big change everyone would need to adapt to.

**Comment by ShaneBeee** [comment]
Closing in favour of #2207
