### ISSUE TITLE
Low Processor, Giant code = this?

### ISSUE THREAD

**Issue by danielzinh** [SkriptLang/Skript#3686]
Server Jar: PaperSpigot 1.16.4 Paper version git-Paper-400
Logs: Doesnt has any log.
Server Config: 3GB Ram DDR3 with an A4-7300 processor, 2c 4t (so weak)

issue/bug: i use an giant skript code (3k+ lines) and i have problems, when server starts, skript doesnt load the codes, i need to use the command /sk reload scripts to load the scripts, else he's doesnt load automatically, some times the server starts without the scripts (dont loaded automatically) and crashs after +-10 seconds.

its because of my low processor power?

important observation: the server run with an A4-7300 2c 4t, but is windows, run others programs, its a desktop pc.

Versions, all addons, skript version: https://prnt.sc/wkjm6w

**Comment by danielzinh** [comment]
important observation: the server run with an A4-7300 2c 4t, but is windows, run others programs, its a desktop pc.

**Comment by danielzinh** [comment]
Versions, all addons, skript version: https://prnt.sc/wkjm6w

**Comment by ShaneBeee** [comment]
1) When creating an issue, please fill in the template we provide.  This template asks for specific information to help us triage your issue. Deleting this template does not help us

2) Please edit your original message rather than spam responding to your own issue. Some people in the organization get emails for every reply here. I don't think anyone wants 3+ emails for one issue.
I have gone ahead and edited your original post to combine your replies.

**Comment by danielzinh** [comment]
> 1. When creating an issue, please fill in the template we provide.  This template asks for specific information to help us triage your issue. Deleting this template does not help us
> 2. Please edit your original message rather than spam responding to your own issue. Some people in the organization get emails for every reply here. I don't think anyone wants 3+ emails for one issue.
>    I have gone ahead and edited your original post to combine your replies.

Sorry, i will create an new issue!

**Comment by ShaneBeee** [comment]
Going to close this in favour of your new issue https://github.com/SkriptLang/Skript/issues/3691
