### ISSUE TITLE
Skripts doesn't loading automatically

### ISSUE THREAD

**Issue by danielzinh** [SkriptLang/Skript#3691]
### Description
When my server starts, most of the time the codes do not load automatically, only a few times that they start alone

### Steps to Reproduce
i don't know, but i have so much codes in my server, more than 3.5k lines.

### Expected Behavior
When server starts, load all codes at all times without problems

### Errors / Screenshots
there are no prints, the Skript plugin runs but the codes (most of the time) do not load any of them and the server runs out of codes, only a few times that the codes load alone

My config.sk https://pastebin.com/SSm7rJmW

My skript versions: https://prnt.sc/wmxxjh

Paper 1.16.4

**Comment by DeltaRays** [comment]
Hey, what do you mean with ‘the server runs out of codes’?

**Comment by danielzinh** [comment]
the plugin (Skript.jar) starts normally, but the codes no (only a few times it runs, but few)

**Comment by ShaneBeee** [comment]
re:
<img width="516" alt="Screen Shot 2021-01-23 at 3 04 50 AM" src="https://user-images.githubusercontent.com/20008482/105576465-c549fc00-5d27-11eb-940e-61fb87c63498.png">

It's really hard for us to reproduce an error/issue when your reproduction steps are "idk"

Skript is notorious for having issues when trying to parse a large amount of lines. It is highly recommended to break your scripts up into smaller scripts. 

I don't have much else to say here, since really all you've said is "why no load?"... personally I have had about 15 scripts on a server at once, all fairly large, without having a single issue.

My guess, is the loading issue is purely user error, with inefficient scripts.

**Comment by TPGamesNL** [comment]
Closing due to lack of response
