### ISSUE TITLE
Function referencing

### ISSUE THREAD

**Issue by honkling** [SkriptLang/Skript#3692]
Add the ability to reference functions with a `function` or `fn` type that can be stored in variables.
You could also possibly parse **strings** as functions, like `"hey_there" parsed as function`.

`[[the] (function|fn)] <.*>`

**Examples:**
```
function hey_there(p: player):
    send "Hey there pal!" to {_p}

function hey2(p: player):
    send "Howdy :)" to {_p}

function separate(f: function):
    {_f}()

on script load:
    if true is true:
        separate(hey_there)
    else:
        separate(hey2)
```

```
function hey(f: function) :: string:
    return "Hey :)"

command call <function>:
    trigger:
        send "&7Executing %arg-function%."
        set {_output} to arg-function()
        send "&7Output:%nl%%{_output}%"
```

EDIT: Added more elaborate examples, possible syntax, and clarified some bits.

**Comment by ShaneBeee** [comment]
Personally I vote no on this.

Your examples are extremely confusing because you are calling your functions without using the parameters at hand.
ex:
<img width="330" alt="Screen Shot 2021-01-23 at 3 01 20 AM" src="https://user-images.githubusercontent.com/20008482/105576390-4e146800-5d27-11eb-9675-a3ec58bf1dda.png">

I don't see how this would add any benefit to Skript other than confusing the already confused. 

In java, you don't reference methods using Strings, you just call the method directly. 
The only time you would use a String would be when using reflection, possibly because you don't have direct access to said method for whatever reason (think Spigot/Paper + NMS).

Since Skript would always have direct access, this just doesn't seem like an option that would solve any possible issue.

**Comment by TheLimeGlass** [comment]
Closing in favor of https://github.com/SkriptLang/Skript/issues/1265

Other issue has exact syntax proposal and alternative syntax suggestions.
