### ISSUE TITLE
Optimize variables RAM usage.

### ISSUE THREAD

**Issue by XfedeX** [SkriptLang/Skript#3701]
Right now, a variable is saved like:
`var1, string, 80393132372E302O302E31`
As you can see, the word string takes a considerable amount of space.
You can replace "string" with "s" , "boolean" with "b" , "double" with "d" , "location" with "loc" etc. to optimize memory usage. You can also mantain retrocomaptibility!

**Comment by ShaneBeee** [comment]
This has nothing to do with memory/RAM.
That is how variables are serialized and saved to disk.
When a variable is in RAM, its just its object as itself.

**Comment by bluelhf** [comment]
While XfedeX has many pointless issues, I do _kind of_ see the point behind this one:
For users with limited disk space, storing data in a more "pure" format (e.g pure byte data instead of comma-separated values) would be beneficial. Since the variable table is not designed to be edited either way, why keep it in a readable format?

@XfedeX The proposal to use less space to store the type is pointless because it likely wouldn't cause a significant improvement. Skript has many issues when it comes to variables, and the biggest one of them definitely isn't saving 5 bytes storing a datatype more efficiently.

**Comment by Moderocky** [comment]
While storing the data in a binary would be massively more efficient (both for speed and size), it’s also an incredibly difficult process - especially if you’ve never done it before - and can cause problems if users decide to try and edit or alter their new variables file.

**Comment by TheLimeGlass** [comment]
Switch your database to SQLite or MySQL to have your data stored in binary.

**Comment by DeltaRays** [comment]
Wasn’t there an idea to change the database type to a different one?

**Comment by WeeskyBDW** [comment]
Some DBMS are more optimized than other (or other storage methods)

**Comment by TPGamesNL** [comment]
Duplicate of https://github.com/SkriptLang/Skript/issues/1168
