### ISSUE TITLE
Use Bukkit#matchPlayer for player parsing

### ISSUE THREAD

**Issue by FranKusmiruk** [SkriptLang/Skript#3803]
## Description
It may also be a good idea to reconsider the player parsing using `Bukkit.matchPlayer` instead of just taking exact matches (although they should remain case insensitive).

 _Originally posted by @TPGamesNL in https://github.com/SkriptLang/Skript/issues/3802#issuecomment-795589597_

**Comment by TPGamesNL** [comment]
The parsing is applicable in two places, ExprParse and command arguments. Here's an example for command arguments:
```
command /pcmd <player>:
	trigger:
		message "Player: %arg-1%"
```

`/pcmd tp`: `TPGamesNL`
`/pcmd s`: `TPGamesNL`
`/pcmd o`:
![image](https://user-images.githubusercontent.com/29547183/110655602-7ebd3d80-81bf-11eb-9469-ea9ea6fa88aa.png)
(notice how it says *whose name starts with*, indicating how this was meant to work)

**Comment by AyhamAl-Ali** [comment]
I would prefer using **getPlayer** and a **custom matchPlayer** where we only check for starting of a name instead of any part matches, probably in all contexts not just COMMAND

*matchPlayer uses partial name not starting with*
![image](https://github.com/SkriptLang/Skript/assets/20037329/19802128-843b-49a1-bc1b-4d69263e5618)
