### ISSUE TITLE
Change default behaviour of the log commands config option 

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#3855]
I would like to see on my server not log some useless new command.
Feel free to add:
```
command test:
    log command: false
    trigger:
        broadcast "%player% executed command"
```
it should not send to ```console player [UUID of player]: /command```

**Comment by TPGamesNL** [comment]
There's a config option for this: https://github.com/SkriptLang/Skript/blob/da691e2d36b038a20ed14cf1f6ab01f471c11451/src/main/resources/config.sk#L122-L125
Is there any specific reason you want to have this per command?

**Comment by Misio12320** [comment]
> Is there any specific reason you want to have this per command?

Yes. The console spam me some useless messages when I want to try change something and its annoying and consume memory. My useful commands on server should log and useless not


> There's a config option for this:

Weird. But it logs every command and wrongly (may only for me) in format this what is said in issue. I mean per command log, not every.

**Comment by TPGamesNL** [comment]
IMO this config option should be disabled by default, since servers already default to logging command usage. 
Besides that, if you have important commands you want logged and you disabled logging of all server commands, you could always add a single line of code to the start of your command trigger to log it.
