### ISSUE TITLE
Skript fails at telling apart certain items.

### ISSUE THREAD

**Issue by HW2955** [SkriptLang/Skript#3869]
### Description

skript fails at comparing ex. stone and diorite (cannot tell them apart by their name "stone block" & "raw diorite" - returns stone block)
though when doing the same with *stone brick* and *cracked stone brick* it doesn't have a issue with it.
### Steps to Reproduce

`
on inventory click:
    if amount of stone block in player's inventory > 0:
        send "you have stone!" to player
`
even if we don't have *stone block* but have *raw diorite* it'll pass the check, i'm sure there is hella ton of different blocks, though as far as i'm aware comparing *stone brick* with *cracked stone brick* works just fine.
### Expected Behavior

`send "you have stone!" to player`
shouldn't be called if we have *raw diorite* in our inventory.
### Server Information
* **Server version/platform:** 
* **Skript version:** 
paper 1.12.2 (most likely can be reproduced on newers versisons as well since we're working with names, not ID's)
skript 2.5.3

**Comment by TPGamesNL** [comment]
This only happens on 1.12, because in that version materials like diorite and andesite were `minecraft:stone` with a data value

**Comment by HW2955** [comment]
well, in that case how would we go about workingaround that? since it doesn't happen on newer versions i highly doubt that this would be of any priority.

**Comment by TPGamesNL** [comment]
For simple comparisons you could use `if {_i} is stone` followed by `if {_i} is not diorite, andesite, ...:`. 
I don't think this should even be classified as a bug, since Minecraft 1.12 basically says that diorite is a different kind of stone, so with that reasoning this should be the expected result.

**Comment by ShaneBeee** [comment]
This is technically an alias issue.
The aliases for 1.12.2 are as follows:
```vb
unchanged building blocks:
	# Stones
	stone [block¦s] = minecraft:stone
```
```vb
old blocks before flattening:
	minecraft version = 1.12.2 or older
	# Stones
	[raw] granite¦s = minecraft:stone {Damage:1}
	(smooth|polished) granite¦s = minecraft:stone {Damage:2}
	any granite¦s = raw granite, polished granite

	[raw] diorite¦s = minecraft:stone {Damage:3}
	(smooth|polished) diorite¦s = minecraft:stone {Damage:4}
	any diorite¦s = raw diorite, polished diorite

	[raw] andesite¦s = minecraft:stone {Damage:5}
	(smooth|polished) andesite¦s = minecraft:stone {Damage:6}
	any andesite¦s = raw andesite, polished andesite

	any [natural] stone¦s = stone, any granite, any diorite, any andesite
```
the issue here is there is missing an alias for regular stone, 
for example, something like: 
`normal stone = minecraft:stone {Damage:0}`

Looking thru the aliases, there are probably a lot of these scenarios missing.

That said, as TP games stated, there are workarounds. You can also check the data value of the block I believe, like:
```vb
if block is stone:
    if data value of block is 0:
```
Not ideal, but it should work.
You could also create your own alias in the file:
```vb
aliases:
    regular stone = minecraft:stone {Damage:0}

on some event:
    if block = regular stone:
```

To finish off:
While Skript does **currently** support 1.12.2 and below, the dev team is planning on removing legacy support in the future. That said, I wouldn't expect a bug of this low of a priority to be looked at. 1.13 came out nearly 3 years ago, its beyond time to move on.

**Comment by HW2955** [comment]
So, i edited aliases though the issue persists, (unless im doing something wrong that is), as you said doing data of block is working, removing items from player inventory doesn't work (once again unless im doing something wrong, or there is top secret syntax to remove items by ID;DATA), worth mentioning that i asked same question in skript-help, though noone knows, nor has any idea how to do that.
---
probs im just doing stuff wrong lmao
