### ISSUE TITLE
Using a function as a list in a contain effect doesn't work

### ISSUE THREAD

**Issue by AzonFR** [SkriptLang/Skript#3874]
### Description
When using a function as a list in a contain effect it doesn't work
But we can use `if whitelist() where [input = {_p}'s name] is set:`

### Steps to Reproduce
```
function whitelist() :: texts:
  return "Azon_FR", "Azon_DC1", "Azon_DC2" and "Azon_DC3"

function connect(p: player, s: text):
  loop whitelist():
    broadcast "%loop-value% %{_p}'s name%"
    loop-value = {_p}'s name
    broadcast "&atrue"
  if whitelist() contain {_p}'s name:
    broadcast "&acontain"
  else:
    broadcast "&cdoesn't contain"
```

### Expected Behavior
It should send "contain" because whitelist() contain my name

### Errors / Screenshots
![](https://i.gyazo.com/17507be41b9213527145cc712e414399.png)

### Server Information
* **Server version/platform:** Spigot 1.8.8
* **Skript version:** 2.5.3 fork for 1.8

**Comment by bluelhf** [comment]
The issue tracker supports only 1.9.4 and above

**Comment by Matocolotoe** [comment]
> The issue tracker supports only 1.9.4 and above

This issue occurs in 1.9+ though :)

![image](https://user-images.githubusercontent.com/42092549/113470900-17f71100-9459-11eb-90b8-2ca1f94f5816.png)

```
function whitelist() :: texts:
  return "Giovanni75", "Azon_DC1", "Azon_DC2" and "Azon_DC3"

function connect(p: player, s: text):
  loop whitelist():
    broadcast "%loop-value% %{_p}'s name%"
    loop-value = {_p}'s name
    broadcast "&atrue"
  if whitelist() contain {_p}'s name:
    broadcast "&acontain"
  else:
    broadcast "&cdoesn't contain"
```

**Comment by TPGamesNL** [comment]
This happens because CondContains handles string differently from other objects, examples:
`("abc" and "def") contains "abc"` returns false, because `abc` does contain the text `abc`, but `def` doesn't.
`("abc" or "def") contains "abc"` returns true, because now `or` is used instead of `and`.

The reason this behaviour isn't noticed that much, is because it doesn't work properly for list variables, these are checked as a list of objects.
Related: #2439
