### ISSUE TITLE
Hex code in documentation is false

### ISSUE THREAD

**Issue by Toast732** [SkriptLang/Skript#3888]
After trying to use hex codes in skript following the documention, it gave me an error stating "Invalid use of quotes ("). If you want to use quotes in "quoted text", double them: "". (test.sk, line 47: send "<#55aaff>foobar" to player')"
The documentation only put one # instead of two #, after changing the line to say
send "<##55aaff>foobar" to player
Then it worked
![image](https://user-images.githubusercontent.com/55813762/114081674-dc09e480-987a-11eb-8ac2-b94450522993.png)

The documentation page in question:
http://skriptlang.github.io/Skript/text.html
![image](https://user-images.githubusercontent.com/55813762/114081781-fcd23a00-987a-11eb-9600-b14ce355ec86.png)

**Comment by AyhamAl-Ali** [comment]
Adding to this, the double hashtag 'thing' exists from a very long time ago, mostly from when Skript first released.

It is due to how hashtags are dealt with in Skript, since they are the `comments` tag when you want to use them as `non-comments` tag you will need to double them.

However, I think this can be reworked on to only parse `#` on line ends or line beginnings or check if they are not in quotation marks so we don't need to double them to use them as `non-comments` tag.

**Comment by Mwexim** [comment]
In skript-parser, I implemented it as such that if there are 3, 6 or 8 valid hexadecimal digits after a ‘#’ the parser would simply not parse it as a comment, but rather leave it there instead. 

However, this is very forced behaviour and might break current scripts that don’t use spaces between the hashtag and the actual comment.

**Comment by AyhamAl-Ali** [comment]
> In skript-parser, I implemented it as such that if there are 3, 6 or 8 valid hexadecimal digits after a ‘#’ the parser would simply not parse it as a comment, but rather leave it there instead.
> 
> However, this is very forced behaviour and might break current scripts that don’t use spaces between the hashtag and the actual comment.

I think this should be added to vanilla Skript parser and not just this but as I stated above it should only parse when supposed to like at `line endings and beginnings` but not in the line or strings.

But if this gets added it should be an option to toggle in Skript's config and it is set to `false` by default since it may break so many scripts (but very simple to fix).

**Comment by iamthewallrus** [comment]
> In skript-parser, I implemented it as such that if there are 3, 6 or 8 valid hexadecimal digits after a ‘#’ the parser would simply not parse it as a comment, but rather leave it there instead.
> 
> However, this is very forced behaviour and might break current scripts that don’t use spaces between the hashtag and the actual comment.

Only 6 digits should be valid. Each one is broken up into 3 parts. FF | FF | FF.
FF = 255, the maximum amount for an 8-bit display, which is the most common around the world
