### ISSUE TITLE
Incorect color/data value with banners

### ISSUE THREAD

**Issue by Arc13** [SkriptLang/Skript#389]
The data value and the color of a banner is not correct and is based on the rotation of the banner.

Exemple with these pictures of two same banners:
![2017-02-16_17 52 30](https://cloud.githubusercontent.com/assets/8174691/23031481/67887f88-f471-11e6-942c-dee12132037e.png)
![2017-02-16_17 52 43](https://cloud.githubusercontent.com/assets/8174691/23031482/678a3062-f471-11e6-94f0-d51f38e68fa6.png)

**Comment by TheBentoBox** [comment]
You are correct, this is an aliases issue. 

@tim740, the issue is that the data value only determines the color for the "banner" item in inventory, which has an ID of 425. However, the standing and wall banners, which have the respective IDs of 176 and 177, instead use the `Base` NBT tag to determine color. You should probably remove the color aliases for standing banner and floor banner, and only leave them for the ID 425 banner item.

**Comment by Syst3ms** [comment]
Shameless promotion, my addon, QuarSk, has full banner control, so you can check the color that way

**Comment by TheBentoBox** [comment]
You can also just check the color with SkStuff's NBT control.

**Comment by Arc13** [comment]
OK, thanks for your replies, I tried with QuarSk and it works like a charm, I will give a try to SkStuff.

**Comment by Snow-Pyon** [comment]
This will be easily fixeable when the aliases rework is done.
