### ISSUE TITLE
Cannot reload script with formatted strings

### ISSUE THREAD

**Issue by waveteams** [SkriptLang/Skript#3906]
### Description
I keep receiving a strange error when I try to reload may script. It says
`java.lang.NoSuchMethodError: net.md_5.bungee.api.ChatColor.of(Ljava/lang/String;)Lnet/md_5/bungee/api/ChatColor;`

### Steps to Reproduce
It started to occure when I modified strings (translated them, used unicode and color formatting)
(code will be below)

### Expected Behavior
It should not work like that. There shouldn't be any errors.

### Errors / Screenshots
https://pastebin.com/YzeuuE6H - Console log
https://pastebin.com/N0gZpiaD - Throws an error
https://pastebin.com/nDTWncz9 - Works perfectly

### Server Information
* **Server version/platform:** Spigot 1.12.2 | CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)
* **Skript version:** 2.5.3
* **Addons:** skbee-1.10.2, skellet, skquery-4.1.4, skript-mirror-0.19.1

**Comment by TPGamesNL** [comment]
A check for valid hex (e.g. regex) should be added to `Utils.parseHexColor(String)`: https://github.com/SkriptLang/Skript/blob/d09320866fa15bd6f2fc77b13f3e0cfd2c46ef36/src/main/java/ch/njol/skript/util/Utils.java#L591

Besides that, that method should never have been called, [because](https://github.com/SkriptLang/Skript/blob/da691e2d36b038a20ed14cf1f6ab01f471c11451/src/main/java/ch/njol/skript/util/Utils.java#L528) `Utils.HEX_SUPPORTED` should be false: https://github.com/SkriptLang/Skript/blob/da691e2d36b038a20ed14cf1f6ab01f471c11451/src/main/java/ch/njol/skript/util/Utils.java#L480
