### ISSUE TITLE
Set time in world variable

### ISSUE THREAD

**Issue by Envqu** [SkriptLang/Skript#3971]
I cannot use variable in 'set time of the world "%{world}%" to 24:00'
I tried 'set time in world {world} to 24:00' but it also not working.

![image](https://user-images.githubusercontent.com/70281617/117586602-7a5ac580-b119-11eb-90bf-329ccd2875f6.png)

Skript version: **2.5.3**
Server version: **1.16.5 Purpur**

**Comment by ShaneBeee** [comment]
This is not a bug.
The world expression expects a world literally, variables do not work here.
The world needs to be decided at parse time.

To use a world from a variable, you will need to use the world function `world("name")`

I don't know if this is intended behaviour and if its something we should change, so I will leave that open for team discussion.

**Comment by TPGamesNL** [comment]
The literal shouldn't be used here, you can simply do `set time of {world} to 24:00`. Alternatively, you can use the world function, but in this scenario (where the world is already in a variable), there is no need for that. 

I think this is merely a misunderstanding of the syntax, because the syntax does not contain `world`, except as a type.

**Comment by TPGamesNL** [comment]
After talking to snow, we decided it'd be best to add an expression to convert a string to a world, with (almost) the same syntax as the literal
