### ISSUE TITLE
Function Call with default value of a list of strings causes ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by sovdeeth** [SkriptLang/Skript#4049]
### Description
When calling a function with a single parameter that had a default value of a list of strings, and not inputting and value into the function, it caused an ArrayIndexOutOfBoundsException in the server console.

### Steps to Reproduce
I ran the following function using an effect command: !optionalListParameter()

```
function optionalListParameter(t: strings = ("1", "2")):
    broadcast "%{_t::*}%"
```
### Expected Behavior
It should have broadcast "1 and 2"

### Errors / Screenshots
Console log:
https://pastebin.com/32zhjFMZ

In-game chat:
![image](https://user-images.githubusercontent.com/10354869/120432609-059d3480-c32f-11eb-904c-ef51bc16b5e7.png)

screenshot of the skript file: 
![image](https://user-images.githubusercontent.com/10354869/120432705-29f91100-c32f-11eb-8dc5-5a3a2bc5db46.png)

### Server Information
* **Server version/platform:** 1.16.5 Paper
* **Skript version:**  2.5.3

### Additional Context
This could be related to a similar weird bit of parsing that I was investigating on the SkUnity discord, but wasn't sure if it was a bug or not. Here's an image of the relevant messages.
![image](https://user-images.githubusercontent.com/10354869/120432935-7ba19b80-c32f-11eb-9a37-3bcf4567a5d2.png)

**Comment by TPGamesNL** [comment]
I can confirm the AIOOB ([2.6-alpha1 stacktrace](https://pastebin.com/Fg9Vp6AB)).

The weird parsing is caused by
https://github.com/SkriptLang/Skript/blob/cb2181e8d72373930d16ecc6be0096f81b96116d/src/main/java/ch/njol/skript/lang/function/Parameter.java#L104-L122
1. The code doesn't check the `plural` argument
2. The code accepts strings without quotes (there's a comment that this behaviour should be removed in a future version, I think it's time we do this, see [commit](https://github.com/SkriptLang/Skript/commit/7dee254359c22415ac31a08f9b0150d3c1f050c1#diff-8c466cf22b435b99203c05e14c43f32465601bd77cdb69e699bf23cd1e0d4fe8R102-R108))
3. The code accepts strings with quotes even when the parameter type doesn't, for example `function test(i: number="abc"):` is accepted, where `{_i}`, expected to be a number, will contain the string when the function is executed. (see [commit](https://github.com/SkriptLang/Skript/commit/9fa83dde10f0b84fe362a152b1fa5dd1d6157b12))
