### ISSUE TITLE
Problem with newest Skript plugin

### ISSUE THREAD

**Issue by xoridah** [SkriptLang/Skript#4251]
### Skript/Server Version

```
 Skript: 2.6-beta2
 Server Version: Spigot 1.12.2
```

### Bug Description

So, i uploaded the skript 2.6-beta2 and i have some errors.

### Expected Behavior

So, the thing that was supposed to happen was that it didnt show errors and that it would work properly.

### Steps to Reproduce

Um, i did not do anything, after i uploaded the script plugin i check the console and then the errors showed up :c

### Errors or Screenshots

```
 https://pastebin.com/USL9jjwm
```

### Other

No

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by wallace4BR** [comment]
Looks like your java version is outdated

**Comment by APickledWalrus** [comment]
Java 16 shouldn't be required though

**Comment by wallace4BR** [comment]
> Java 16 shouldn't be required though

i guess it is
[23:30:34 ERROR]: #!#! Caused by: java.lang.UnsupportedClassVersionError: ch/njol/skript/module/worldguard6/WorldGuard6Hook has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by xoridah** [comment]
Yes, i remove plugin worldguard now its working thx!
