### ISSUE TITLE
Comparison of event-block and block

### ISSUE THREAD

**Issue by vhone** [SkriptLang/Skript#4340]
### Skript/Server Version

[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: git-Paper-127 (MC: 1.17.1)
[Skript] Skript Version: 2.6-beta3-nightly-4c9a3ab
[Skript] Installed Skript Addons:
[Skript]  - skript-reflect v2.2.2-dev (https://github.com/TPGamesNL/skript-reflect)

### Bug Description

If compare event-block and block, it comes out that they are different.

### Expected Behavior

The same two blocks are different when compared because they have different classes.
However, the actual two values are the same.

### Steps to Reproduce

```
on break:
	cancel event
	send "%event-block%" to console
	send "%block at event-block%" to console
	if block at event-block is event-block:
		send "same"
	else:
		send "different"
```

console print...
'grass block' at -187.5, 63.5, -22.5 in world 'world'
'grass block' at -187.5, 63.5, -22.5 in world 'world'

message is "different"

event-block class is ch.njol.skript.util.DelayedChangeBlock
block class is class org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
DelayedChangeBlock is introduced in https://github.com/SkriptLang/Skript/commit/7dbf5dcde1442895c1d9c6ed20a9992bd12e031f, probably for this reason:
> Fixed not being able to set the block in block break events

It fixes the issue, by making an effect like `set event-block to stone` (if event-block is a DelayedChangeBlock) execute on the next tick, after the block has been broken. I presume Njol tried using `on block break: set block to stone` or sth like that, and it didn't work. This is because you first need to cancel the event, otherwise the block still gets set to air, even if its type changed.

While DelayedChangeBlock fixed this issue, it also introduced a delay when setting blocks in break event (or other events that have DelayedChangeBlock for their event blocks, e.g. the block fade event).

This issue that their comparison fails can be fixed quite easily, in the Block - Block comparator, as this doesn't take these classes extending Block into account. The issue with the delays cannot be fixed unless we remove DelayedChangeBlock entirely. If we do, we'll be breaking scripts that don't cancel break events before changing the block, as their block setting effects will stop working. 

For now, just updating the Block - Block comparator should be enough (for a PR author, add BlockStateBlock as well)
