### ISSUE TITLE
effect command event

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#4360]
### Suggestion

Add a new event that runs whenever a user runs an effect command syntax could be
```applescript
[on] [player] effect command:
```
supported values would be ``event-string`` and ``event-player``
event-string would just be the full string so if I did `!broadcast ""` the event-string would be `broadcast ""`

### Why?

An option like this just feels like it's been missing for a while now. This opens room for more options within `effect commands` if you were to even have it run when an error accurse for example if I did `!this won't work` it would return an error normally but maybe we want to make "custom" effect commands without the use of a function

### Other

Slight edit to include the effect should also be cancellable to allow even further customization

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by Pikachu920** [comment]
> I like this idea, this can also help expanding the possibilities of effect commands such as spliting the message at `->` and make multiple line effect commands also, this can help customizing how the results look

this wouldn't be possible without adding support to evaluate effects which I don't think is a supported feature (though I don't know for sure since I'm less active these days)

**Comment by AyhamAl-Ali** [comment]
> > I like this idea, this can also help expanding the possibilities of effect commands such as spliting the message at `->` and make multiple line effect commands also, this can help customizing how the results look
> 
> this wouldn't be possible without adding support to evaluate effects which I don't think is a supported feature (though I don't know for sure since I'm less active these days). Plus, for most use cases couldn't you use `on chat:`?

I am not sure if the team would approve adding the evaluate effect (which I believe would be nice even if not recommended - like tuske's) but I can think of this event would be usable in some cases such as:
- Preventing specific OPs from using it
- Checking if executed effect command contains some text and cancel it
- Replacing some text in the command such as [uuid] with `uuid of me` for example
- Logging effect commands
- And possibly more ideas

> Plus, for most use cases couldn't you use on chat:

This would require an evaluate effect to replace effect commands with custom ones

**Comment by Pikachu920** [comment]
> * Preventing specific OPs from using it
If you want to more granularly control use of effect commands, you can disable the config option that allows ops to use them and instead grant the `skript.effectcommands` permission. This is actually sort of described in the config where it mentions that OPs are not granted that perm automatically unless the "allow ops to use effect commands" option is true:
https://github.com/SkriptLang/Skript/blob/master/src/main/resources/config.sk#L61-L64
> * Checking if executed effect command contains some text and cancel it
This sounds like a way to prevent certain effects or expressions from being used in effect commands, which is a bad use case since this could give users a false sense of security and consequently cause them to be less cautious about granting access to effect commands.
> * Replacing some text in the command such as [uuid] with `uuid of me` for example
If the point of effect commands is to test syntax quickly, it's sort of counterproductive to allow replacement like this
> * Logging effect commands
If logging of player commands is enabled, effect commands are already logged:
https://github.com/SkriptLang/Skript/blob/094afa9736489a19b81494b3226f91c0fe74c296/src/main/java/ch/njol/skript/command/Commands.java#L281-L282

**Comment by AyhamAl-Ali** [comment]
> you can disable the config option that allows ops to use them and instead grant the skript.effectcommands permission

This specific example was mainly to prevent specific players that have the ability to give/remove permissions to/from themselves because they can bypass it, so this can be hard coded in some script to prevent it.

If the purpose of effect commands is only for testing then I agree none of this should be added, but many users including me actually use it to perform quick actions in-game without having to open, edit, save and reload files which is what I explained a bit in this [comment](https://github.com/SkriptLang/Skript/issues/4360#issuecomment-950126379)

The whole idea of my suggestion is that this great feature can be taken further and give the users the ability to fully control it and made their own security on it.

I made my own effect command script a while ago using TuSKe's evaluate effect to add some more features such as multi-line effect commands (not truly multiline) can be found [here](https://github.com/AyhamAl-Ali/SkriptMultiEval/blob/main/SkriptMultiEval.sk)

**Comment by Moderocky** [comment]
I'm concerned that adding too much to effect commands will encourage people to misuse them (more than they already do.)
If you're concerned about them as a security issue I'd suggest disabling them in the live server environment completely.

**Comment by TheLimeGlass** [comment]
I didn't even notice this feature suggest when making my pull request, but anyways.
I added full support for addon developers to take control of this. I also personally don't believe it should be a syntax directly in Skript as the effect command system is designed for debugging, but with my pull request at https://github.com/SkriptLang/Skript/pull/4532 an addon can do whatever they want with it.
