### ISSUE TITLE
InventoryClickEvent raw slot expression

### ISSUE THREAD

**Issue by AriesStar1337** [SkriptLang/Skript#4461]
### Skript/Server Version

```
Server Version: git-Paper-69 (MC: 1.18.1)
Skript Version: 2.6
```

### Bug Description

Open inventory cause slot index to return wrong value

### Expected Behavior

Slot index return the correct value when open inventory

### Steps to Reproduce

```
on inventory click:
    send "Slot ID: %index of event-slot%"
    
on rightclick on a player:
    open event-entity's inventory for player
```

### Errors or Screenshots

![Bug](https://user-images.githubusercontent.com/49795821/145704659-6fefb527-2f92-4488-bc34-47ed362e2a42.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
This isn't a Skript issue, since `event.getSlot()` returns weird numbers for some slots, I'm not sure why. This is probably a server issue.

However, we could add an expression for [getRawSlot](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryClickEvent.html#getRawSlot()), which would return the value you're looking for.
