### ISSUE TITLE
Skript slow to parse "play" syntaxes

### ISSUE THREAD

**Issue by MinecollYT** [SkriptLang/Skript#4597]
### Skript/Server Version
```
[11:44:00 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[11:44:00 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[11:44:00 INFO]: [Skript] Server Version: git-Paper-408 (MC: 1.17.1)
[11:44:00 INFO]: [Skript] Skript Version: 2.6.1
[11:44:00 INFO]: [Skript] Installed Skript Addons: 
[11:44:00 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[11:44:00 INFO]: [Skript]  - skript-db v1.3.3
[11:44:00 INFO]: [Skript]  - SkBee v1.14.1 (https://github.com/ShaneBeee/SkBee)
[11:44:00 INFO]: [Skript]  - Skript-Packet v2.0.1 (www.github.com/Anarchick/skript-packet)
[11:44:00 INFO]: [Skript]  - ItemsAdder v2.5.5 (devs.beer)
[11:44:00 INFO]: [Skript] Installed dependencies: 
[11:44:00 INFO]: [Skript]  - Vault v1.7.3-b131
[11:44:00 INFO]: [Skript]  - WorldGuard v7.0.6+1cff55f
```

### Bug Description

When parsing a skript containing this code skript just crashes. The server still responds. 
```
function magicMan(p: player, msg: text):
	if {magicman} is not true:
		set {magicman} to true
		send "&d%{_p}%&8: &f%{_msg}%" to all players where ["%region at player input%" contains "magicman"]
		wait 2 seconds
		set {_answer} to a random integer between 1 and 3
		if {_answer} is 1:
			send "&dMagicMan&8: &fyes" to all players where ["%region at player input%" contains "magicman"]
			play sound "block.respawn_anchor.charge" with volume 0.8 and pitch 1.7 to to all players where ["%region at player input%" contains "magicman"]
		else if {_answer} is 2:
			send "&dMagicMan&8: &fno" to all players where ["%region at player input%" contains "magicman"]
			play sound "block.respawn_anchor.charge" with volume 0.8 and pitch 0.4 to to all players where ["%region at player input%" contains "magicman"]
		else if {_answer} is 3:
			send "&dMagicMan&8: &fmaybe" to all players where ["%region at player input%" contains "magicman"]
			play sound "block.respawn_anchor.charge" with volume 0.8 and pitch 1 to to all players where ["%region at player input%" contains "magicman"]
		wait 2 seconds
		set {magicman} to false
	else:
		send "&7..." to {_p}
```

When removing the following part everything works fine:
```
		wait 2 seconds
		set {_answer} to a random integer between 1 and 3
		if {_answer} is 1:
			send "&dMagicMan&8: &fyes" to all players where ["%region at player input%" contains "magicman"]
			play sound "block.respawn_anchor.charge" with volume 0.8 and pitch 1.7 to to all players where ["%region at player input%" contains "magicman"]
		else if {_answer} is 2:
			send "&dMagicMan&8: &fno" to all players where ["%region at player input%" contains "magicman"]
			play sound "block.respawn_anchor.charge" with volume 0.8 and pitch 0.4 to to all players where ["%region at player input%" contains "magicman"]
		else if {_answer} is 3:
			send "&dMagicMan&8: &fmaybe" to all players where ["%region at player input%" contains "magicman"]
			play sound "block.respawn_anchor.charge" with volume 0.8 and pitch 1 to to all players where ["%region at player input%" contains "magicman"]
		wait 2 seconds
```

Even the skUnity fails to parse this code: "Something went wrong trying to parse your script! Please refresh and try again"

### Expected Behavior

Parse the code or at least return an error when something is wrong

### Steps to Reproduce

Parse this code, you don't need to run it

### Errors or Screenshots
https://pastebin.com/dpKkWm9d

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by MinecollYT** [comment]
oh okay, so how could I rewrite this?

**Comment by TPGamesNL** [comment]
See above, but also likely caused by https://github.com/SkriptLang/Skript/issues/1091

**Comment by TheLimeGlass** [comment]
Reopening as this issue takes ~3000ms to parse where as the duplicated issue doesn't happen anymore.

**Comment by TheLimeGlass** [comment]
I did a profiler the other day and VisualEffect class takes 200ms on initialization of it's class. Potentially an issue within that class, and also Skript is probably sending anything that starts with play through the VisualEffect ClassInfo parser.

**Comment by Moderocky** [comment]
I can't reproduce any of the examples from this (or the other related issue) taking longer than 10 milliseconds on the latest 2.7.1 version, so I'm going to assume this has been improved over time by things like keyword parsing and general improvements, to the point where it isn't a problem anymore.
<img width="439" alt="image" src="https://github.com/SkriptLang/Skript/assets/14147477/06e3c321-b179-49ac-81fb-94590961942e">

The only time I *can* produce a longer time (of 0.3 seconds) is if the syntax is malformed or wrong, as it is in the original examples in this post.
<img width="585" alt="image" src="https://github.com/SkriptLang/Skript/assets/14147477/4d2c8d42-d370-45b7-a837-1b5295fa2be9">
<img width="124" alt="image" src="https://github.com/SkriptLang/Skript/assets/14147477/833402d4-9bb2-4f43-a3fa-a281c54c7d60">
However, since this isn't valid Skript syntax I don't think this counts as a bug, since even if we made it faster it would still just not work in the first place.

If somebody can find a new example of this taking too long (i.e. over a second per syntax) please re-open this issue or create a new one with that example.
