### ISSUE TITLE
CMI Economy not working

### ISSUE THREAD

**Issue by Arthful** [SkriptLang/Skript#4633]
### Skript/Server Version

Skript and Server version 1.18

### Bug Description

I was trying to create a shop skript that check's the player's balance,

_If player's balance is more than or equal to 500_

However skript cannot retrieved the economy from CMI
https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/
I tried reaching out to the CMI Author and did all the things he requested such as adding "CMI" to the Skript soft dependency. But there's no result

### Expected Behavior

Skript will obtain the player's balance

### Steps to Reproduce

In Skript:
_If player's balance is more than or equal to 500_

Download CMI, and it's custom vault injector
https://www.zrips.net/wp-content/uploads/2020/07/CMIEInjector1.0.2.3.jar

Enable the CMIEconomy in the config of CMI

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Please provide more info, do `/sk info` and edit the issue with the results
Also provide the output of the code you used, if there are any errors or any outputs (screenshots preferred)
Some info can be found here https://github.com/Zrips/CMI/issues/6690

**Comment by Arthful** [comment]
No skript errors in the console but it is unable to check for the player's balance

**Comment by AyhamAl-Ali** [comment]
Execute this code (not from console) and send the results here
```v
command /test: 
    trigger:
        broadcast "%player% - %player's balance%"
```

**Comment by Arthful** [comment]
![image](https://user-images.githubusercontent.com/100519431/156126502-15602eac-7aa3-43b4-844b-36b63d84e7fb.png)

**Comment by Arthful** [comment]
![image](https://user-images.githubusercontent.com/100519431/156127510-4af56f52-37fc-491e-8952-d9197f066dfc.png)

**Comment by Arthful** [comment]
Any update? @AyhamAl-Ali

**Comment by AyhamAl-Ali** [comment]
I've been in contact with CMI author (Zrips) about this issue, thanks to him for his amazing coorpration, he tested using the same environment used by the issue reporter with the test code I provided above and it was successful as shown below

![image](https://user-images.githubusercontent.com/20037329/156157399-6176a80d-f5a7-4a91-98b8-a643a11acb4a.png)

Therefore this is probably a user error, please try the following steps:
1. Remove all skript addons and any other plugin that might interfer with Vault's economy system (other than CMI and Skript)
2. Redownload CMI and the modified Vault version from CMI resource page (or injector version)
3. Redownload Skript (since you modified its plugin.yml)
4. Make sure you have economy enabled in CMI config
5. Test again using the code I sent above

After that if it's not fixed use [SkUnity ](https://discord.gg/0l3WlzBPKX7WNjkf) discord and I will help you further more

**Comment by Arthful** [comment]
Tried everything and it now works, probably the problem is the injector of another bank plugin "Supreme Banks". Thank you so much for the support!

**Comment by AyhamAl-Ali** [comment]
You're welcome \:)
