### ISSUE TITLE
Chicken throws an error

### ISSUE THREAD

**Issue by XenonsEU** [SkriptLang/Skript#4809]
### Skript/Server Version

```markdown
Server Version: git-Paper-277 (MC: 1.18.2) - It is !!1.19!! but it shows 1.18.2
Skript Version: 2.6.2-mc-1.19
Installed Skript Addons: 
Skent v3.1.0
Skacket v1.0.10
skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
skUtilities v0.9.2 (https://tim740.github.io/)
skript-db v1.3.3
skRayFall v1.9.27 (https://sk.rayfall.net/)
SkQuery v4.1.6
SkBee v1.16.0 (https://github.com/ShaneBeee/SkBee)
SkJade v1.4.1 (https://www.github.com/Ankoki-Dev/SkJade)
RediSkript v1.3.5
Skript-Packet v2.1.0 (www.github.com/Anarchick/skript-packet)
SkStuff v2.2.1
```

### Bug Description

When using entity in a function, they all work fine that I've tested so far
except chicken

when I put chicken as entity it just says that "Variables cannot be used here" or that the argument given is not of the correct type
different errors based on how many arguments the function has.
as soon as I swap the entity to anything else like cow/pig it works fine

### Expected Behavior

I want my chickens

### Steps to Reproduce

```
function testChicken(e: entity type):
    broadcast {_e}

command /testchicken:
    trigger:
        testChicken(chicken)
```

Swapping chicken argument with a cow works for example.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
It's conflicting with the item type `chicken` as in cooked chicken.

You can set the default parameter of the function or parse the input as an entity type so Skript knows which chicken you're referring too.

```vb
function testChicken(e: entity type = chicken):
	broadcast {_e}

command /testchicken:
	trigger:
		testChicken("chicken" parsed as entity type)
		testChicken()
```

You will also have conflicts with fishes and rabbit.

I know this is a common issue with Skript, but it depends on where it is. In this case it's probably just the fact that functions only attempt to parse once and error, rather than event-values that attempt to check super classes and other converters etc.

@TPGamesNL

**Comment by TheLimeGlass** [comment]
Potential duplicate https://github.com/SkriptLang/Skript/issues/4769 @TPGamesNL
