### ISSUE TITLE
`Had Played Before` check not working with players on for the first time

### ISSUE THREAD

**Issue by Zabrid** [SkriptLang/Skript#4831]
### Skript/Server Version

```markdown
Skript Version: 2.6.2

Addons:
- skript-yaml v1.4
- skript-reflect v2.3
- skUtilities v0.9.2
- skRayFall v1.9.27
- skBee v1.15.2
- Vault
```

### Bug Description

If a new player is currently online and they are playing for the first time the `has played before` check fails.

### Expected Behavior

The `has played before` check should not fail as they have played before.

### Steps to Reproduce

Get a new account on and do

`/checkaccount [<offline player>]:`
    
`    trigger:`

`        arg 1 has played before`

`        send "%arg 1% has played before"`

It will not return the message.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
This is mostly likely a server issue, this behavior has been there for a very long time, I guess it updates the player world data once the player quits the server that's why the second time they join the condition is true.

I suggest you also check if player is online to fix such case.
Closing as not a Skript issue, if it turns not feel free to reopen.
