### ISSUE TITLE
💡 Support launching fireworks in ExprLastSpawnedEntity

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#4942]
### Suggestion

suggested syntax: `[the] [last[ly]] (0:spawned|1:shot|2:launched) %*entitydata%`

### Why?

It's needed \:D

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TheLimeGlass** [comment]
I wouldn't put the launched part into the syntax as that makes the entitydata pointless as there can only be 1 entity that launches which is the firework. We can just add another pattern to the last spawned entity expression for fireworks. `last launched firework`

For reference this doesn't already work because the launch firework is done from a different effect than the spawn entity effect/section.
