### ISSUE TITLE
Dont detect empty lore of player's tool

### ISSUE THREAD

**Issue by ostermine** [SkriptLang/Skript#5236]
### Skript/Server Version

```markdown
version: 2.6.3
server - pufferfish 1.19.2
```

### Bug Description

```
command /test1:
	permission: sign.test
	trigger:
		if lore of player's tool is empty:
			send "lore is emty" to player
		else:
			send "lore is not empty"
```
if lore of item is empty - nothing happens, literally, every time triggered ELSE section

### Expected Behavior

if lore of player's tool is empty (holding in hand) just send "lore is emty" to player

### Steps to Reproduce

just hold any item with no lore and try this:

```
command /test1:
	permission: sign.test
	trigger:
		if lore of player's tool is empty:
			send "lore is empty" to player
		else:
			send "lore is not empty"
```

its just nothing happens, instead print "lore is empty"

### Errors or Screenshots

nothing to send like screenshots, because this bug just nothing to do

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by ostermine** [comment]
some code https://i.imgur.com/vuEMpUQ.png

**Comment by DelayedGaming** [comment]
It appears that the condition is failing as you were checking if the __non existent lore__ **is empty**. As there is no text to check on, the condition just fails.
Setting a lore to `""` will pass that condition, as it is indeed empty.
![image](https://user-images.githubusercontent.com/72163224/209980803-16ff0ff7-9d79-4a17-89a3-e1e7d079f98e.png)

**Comment by Mwexim** [comment]
This is expected behavior and should probably not be altered in any major way, except for making it more obvious to the user how the condition works exactly.

In my opinion CondIsEmpty should only work for strings. You can check if a list of objects is empty using `{list::*} is not set`. It has the same outcome if I’m not mistaken.

Though, limiting the condition to strings will break a ton of scripts, so I feel like there should be a warning instead to emphasize that the condition *could* have unexcpected results.

That said, in skript-parser we have something like `list lore of tool of player is empty` where you can explicitly tell the parser you want to check if the list is empty and not the strings of the list itself. I am personally, after reviewing this again, not in favor of this and will probably remove it there.

**Comment by TheLimeGlass** [comment]
Solution could be if the object expression is a string and it's null, return true.

**Comment by TheLimeGlass** [comment]
Would cause changes as the checker returns no null values.
