### ISSUE TITLE
"if {_list::*} contain element" doesn't work

### ISSUE THREAD

**Issue by MrYellow5** [SkriptLang/Skript#5292]
### Skript/Server Version

```markdown
I am in Skript 2.6.4 and I run Paper-160 (MC: 1.19.2).
I tested without any addon and the error continues.
```

### Bug Description

I have noticed this bug for several years.

When we look if a variable contains an element, and the size of the list is greater than 1, the condition will always be false.

### Expected Behavior

Normally, if we code
```
set {_list::*} to "element1" and "element2"
if {_list::*} contain "element1":
    send "contain"
else:
    send "do not contain"
```
it should return "contain", but it returns "do not contain". But, if the size of the list is 1, the code works correctly.

To counter this problem, I make this code :
```
set {_list::*} to "element1" and "element2"
if {_list::*} do not contain "element1":
    send "do not contain"
else:
    send "contain"
```
and it returns "contain" when the list contains the element.

### Steps to Reproduce

_See the "Expected Behavior" section ^^_

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
so I could replicate it on same version using
```

**Comment by Fusezion** [comment]
screenshot for above
![image](https://user-images.githubusercontent.com/81952476/209929258-ce24a755-9328-41a4-9342-5f199978ad63.png)

**Comment by AyhamAl-Ali** [comment]
This seems to be the intended behavior see
https://github.com/SkriptLang/Skript/blob/1610b779334912836a53c114ef2c2348893883c9/src/main/java/ch/njol/skript/conditions/CondContains.java#L57
https://github.com/SkriptLang/Skript/blob/1610b779334912836a53c114ef2c2348893883c9/src/main/java/ch/njol/skript/conditions/CondContains.java#L83
https://github.com/SkriptLang/Skript/blob/1610b779334912836a53c114ef2c2348893883c9/src/main/java/ch/njol/skript/conditions/CondContains.java#L111

The `contain` word means all the elements in the list is equal to the value you provided otherwise it will return false
Try this following code
```v
command /test_contain:
	trigger:
		set {_list::*} to "element1" and "element1"
		if {_list::*} contain "element1":
			send "contain"
		else:
			send "do not contain"
```
Should return `contain`

**Comment by MrYellow5** [comment]
Hooooooo thank you very much!
Indeed, it was a grammar mistake haha. Thank you very much for your quick and efficient answers!

Have a nice day/evening!
