### ISSUE TITLE
Allow returning multiple elements for each source object in PropertyExpression

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5521]
### Suggestion

Add support for returning an array within `SimplePropertyExpression#convert()`

### Why?

I've been trying to use `SimplePropertyExpression` class a bit more, and one of my classes can return an array of multiple itemstacks, however upon attempting I realized the method doesn't support array like all the other methods do

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TheLimeGlass** [comment]
https://github.com/SkriptLang/Skript/pull/5455

**Comment by APickledWalrus** [comment]
I do want to mention here for the record that your primary request is not possible due to how SimplePropertyExpressions work. They are actually just Converters, meaning they **must** return only 1 element per source object (never 1 to many). However, the linked PR will allow you to achieve this behavior using regular PropertyExpression.
