### ISSUE TITLE
"set version string" not working

### ISSUE THREAD

**Issue by noySq** [SkriptLang/Skript#5597]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Purpur-1949 (MC: 1.19.4)
[Skript] Skript Version: 2.7.0-beta2 (skriptlang-github)
[Skript] Installed Skript Addons:
[Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[Skript]  - SkBee v2.8.2 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies: None
```

### Bug Description

"set version string to "xyz"" is not working

### Expected Behavior

it should work and not throw an error

### Steps to Reproduce

on server list ping:
	set version string to "Test"

### Errors or Screenshots

[12:53:09 INFO]: [Skript] Reloading test.sk...
[12:53:09 INFO]: Line 2: (test.sk)
[12:53:09 INFO]:     The version string expression requires Paper 1.12.2 or newer
[12:53:09 INFO]:     Line: set version string to "Test"
[12:53:09 INFO]:
[12:53:09 INFO]: [Skript] Encountered 1 error while reloading test.sk! (43ms)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by noySq** [comment]
> Can you try the same code with Paper 1.19.4 instead of Purpur

Still getting the error with fresh server using the most recent Paper 1.19.4

**Comment by IllagerCaptain** [comment]
I can reproduce this.

**Comment by APickledWalrus** [comment]
This issue is because of this check here:
https://github.com/SkriptLang/Skript/blob/fa8a84226126bbb3bdc2cc14c8fc7c84d83b6b23/src/main/java/ch/njol/skript/expressions/ExprVersionString.java#L61

The problem is, the Paper version of this event extends this event, so the check is always true. This has only been noticed as an issue now because the isCurrentEvent method did not previously function correctly.

The solution is rather simple: return the "not available on this version" if PAPER_EVENT_EXISTS is false
Then, just check isCurrentEvent for the paper version of the event (for the second check)
