### ISSUE TITLE
Add Skript to Hangar

### ISSUE THREAD

**Issue by JakeGBLP** [SkriptLang/Skript#5627]
### Suggestion

Hangar is Paper's new forum website, kinda like https://www.spigotmc.org.

### Why?

Skript should be there as well

### Other

https://hangar.papermc.io/?page=0&q=Skript&sort=-recent_downloads

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Moderocky** [comment]
Skript is not available on any third-party plugin site currently, other than the original dev Bukkit site, which is not updated.

There are several reasons behind this, but the main one is that having users go through GitHub to download and update the plugin means that the user has to see things like the changelog, issue tracker, etc. and so will know A) what's going on and B) what to do if things go wrong.

If we hosted a download elsewhere then that would create extra work in maintaining these external pages with up-to-date information and patch notes every version, not to mention the inevitable risk of users asking for help and posting issues in the resource comments/reviews, which we won't see and so can't address.

There are also a couple of minor discussions we've had on the topic that I'd like to describe here.

1. It looks like PaperMC is going to diverge from Spigot at some point, making resources for these platforms incompatible. At that point we would have to choose one over the other, and rather than having to abandon a legacy, outdated resource page like dev Bukkit (that would confuse users) it seems sensible to wait until we know which of the two we'd prefer to support.

2. The public API from sites like Spigot is used by third-party resource downloaders (like server panels with automatic install/update software or things like 'plug man') which aren't especially healthy for our users. As mentioned above, it's really good when people have to scroll through the patch notes and information to download Skript, since they'll be made aware of any breaking changes in an update and how to fix them. If they're using some auto-download software they won't see these patch notes, their scripts are likely to break when we introduce a major change and they won't know what's wrong or how to fix it.

3. It's a long-term dream to separate out the core of Skript from its Bukkit (and potentially Minecraft) dependency so that it would be available for people to use in other projects. While this doesn't look like it will happen in the near future, it's something that we'd eventually like to do. This separation might involve changes to Skript in a way that makes it not an appropriate resource to host on a site like Spigot or Paper, so making a page now might leave future users with an outdated, non-functioning resource.

These are all very minor concerns, and of course we could still post it now in any case, but we haven't decided as a team what approach to take yet. \
It would definitely be nice to have Skript on plugin websites, but I think we all want to make sure that's done in a way that is healthy for users and doesn't cause us problems down the road. :)

**Comment by TheLimeGlass** [comment]
You can direct the download button to the changelog link of GitHub on Spigot.
