### ISSUE TITLE
Dispense event

### ISSUE THREAD

**Issue by jurajplayercze** [SkriptLang/Skript#5681]
### Suggestion

I would like to see `event-item entity` in on dispense event. 
I wasn't able to find out how to do that without skript-reflect. I am only able to get fired item, but not the item entity.
Tried last spawned entity, last dropped item, but anything i tried i wasn't able to get (for example) uuid of the item entity.

### Why?

I think it's kinda essential to that simple event.

### Other

Maybe to be able to set velocity of the fired item.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockDispenseEvent.html

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
How are you achieving this using skript-reflect?

**Comment by jurajplayercze** [comment]
That's really good question. I did not look for reflect solutions, so i don't achieve it yet. It sounds like we are not able to get that

**Comment by AyhamAl-Ali** [comment]
That's because the event doesn't have a method for grabbing the dispensed entity, only the item. Not sure if there is a way to grab the entity but I thought of looping the entities around the dispenser and that might fix your issue. However, we have an expression to get/change velocity of entities, see [docs](https://docs.skriptlang.org/docs.html?search=#ExprVelocity)

**Comment by TheLimeGlass** [comment]
You can listen to the `on spawn` event. The last dropped item only works when spawning a dropped item from a Skript effect.
