### ISSUE TITLE
Player is an itemtype | ClassInfo compared against ClassInfo

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#5723]
### Skript/Server Version

```markdown
2.7.0-beta2
Paper 1.19.4
```

### Bug Description

```
on script load:
	if a string is an itemtype:
		broadcast "wat"

on script load:
	if player is an itemtype:
		broadcast "wat"

on script load:
	if timespan is an itemtype:
		broadcast "wat"
	if timespan is a player:
		broadcast "wat"
```
parses correctly and prints `wat`

### Expected Behavior

This condition should not pass.

The player classinfo compared against another classinfo is concerning as I can tell Skripters could run into that issue when player is not present in an event.

Note this is unrelated to https://github.com/SkriptLang/Skript/pull/5503

**Comment by UnderscoreTud** [comment]
It broadcasts "wat" because `a string` is referring to the [string item](https://minecraft.fandom.com/wiki/String). Not because a player is an itemtype which is what your issue suggests. Maybe you should use different debug messages for different checks? So you know which is passing and which isn't.
