### ISSUE TITLE
"on portal create" trigger's expression

### ISSUE THREAD

**Issue by nshun1896** [SkriptLang/Skript#576]
There are no expressions for "player", "block" and "location" and so on, aren't there?
Are there any ways to detect "who create the portal" or "where the portal is"??

**Comment by TheBentoBox** [comment]
Have you tried using `event-location` to check the location?

The [Spigot portal creation event](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/world/PortalCreateEvent.html) doesn't have support for getting the player who created the portal, so that feature won't be possible to implement.

**Comment by nshun1896** [comment]
Thanks for replaying.
I tried event-location, event-portal and event-block only to find error log.

**Comment by TheBentoBox** [comment]
I see, thanks for the quick response. Hopefully bensku (or someone else through a PR) can add support for the blocks in the portal creation event soon.

**Comment by nshun1896** [comment]
Thanks, too.
I wait future updating!

**Comment by TheLimeGlass** [comment]
You can only get the world and the block of the portal. Then use those blocks to get the location. All that would be needed is the event-world (Which i'm making a PR now for) and an expression to get all the blocks.

**Comment by nshun1896** [comment]
@TheLimeGlass 
I see. That's  so nice to hear that. Thanks for your kind reply!
