### ISSUE TITLE
Java 11: java.lang.NoSuchMethodError: 'long java.util.Random.nextLong(long, long)'

### ISSUE THREAD

**Issue by DereWah** [SkriptLang/Skript#5819]
### Skript/Server Version

```markdown
Skript: 2.7-beta3
Server: 1.16 (arclight)
Java Version: 11
```

### Bug Description

Skript is not able to generate random integers. From the error, it looks like it uses a non-exising method in Java version 11.

### Expected Behavior

The expression
set {_x} to a random integer between 1 and 300
should set {_x} to a random integer.

### Steps to Reproduce

command /testran:
    trigger:
        set {_x} to a random integer between 1 and 1000
        send {_x}
        
Paste this command in a skript, on a server with Java 11, run it and check console.
        

### Errors or Screenshots

https://mclo.gs/K7P0aQi

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by iPlexy** [comment]
Use Java 16. Its the recommend Version for 1.16

**Comment by TheDGOfficial** [comment]
> Use Java 16. Its the recommend Version for 1.16

Java 16 is long EOL, Java 8, 11 and 17 are LTS releases; so they are still supported.

Besides, this method is added in Java 17, and is located in [RandomGenerator#nextLong](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/random/RandomGenerator.html#nextLong(long,long)). It's a default method in an interface added in Java 17 that is a supertype of all random generators. Part of [JEP 356](https://openjdk.org/jeps/356).

So it would still not work on Java 16.

Judging by build.gradle, Skript still supports Java 8:
https://github.com/SkriptLang/Skript/blob/a11a98a9bf6035329da69d6b531d1521d67d26b9/build.gradle#L258-L267

It compiles with Java 17 though. It sets source and target version, which should disallow any new language features from Java 9 and above being used, but it doesn't prevent new API from being used, which will fail silently at runtime.

Skript either needs to also use bootclasspath or just remove source  and target arguments and use the new --release flag in Java 9 and above ([JEP 247](https://openjdk.org/jeps/247)). This will make compilation require Java 9 or above but it will work on Java 8 and above (if you use --release 8), and will ensure no new language features or APIs from newer versions than minimum supported are used in the code. A snippet from the JEP's Motivation section mentions this issue:

> javac provides two command line options, -source and -target, which can be used to select the version of the Java language accepted by the compiler and the version of the class files it produces, respectively. By default, however, javac compiles against the most-recent version of the platform APIs. The compiled program can therefore accidentally use APIs only available in the current version of the platform. Such programs cannot run on older versions of the platform, regardless of the values passed to the -source and -target options. This is a long-term usability pain point, since users expect that by using these options they'll get class files that can run on the the platform version specified by -target.

If you still want to use new APIs whenever available and fall-back to Java 8 variants without using any sort of reflection or method handle work-arounds, there is also [Multi-Release JAR Files](https://openjdk.org/jeps/238).

Another alternative would be to use Java 8 for compilation, if you are not using any new APIs or language features it makes hardly a difference (mostly a small speed up in the Gradle build maybe, because of the compiler task running on the newer Java 17 JVM, which has GC and JIT enchancements that improve performance, but that shouldn't be huge and there is no runtime difference.)

**Comment by DereWah** [comment]
Any update on this?

**Comment by TheLimeGlass** [comment]
@UnderscoreTud addressed this issue before. Unsure if this was fixed or not. Not home.

**Comment by Fusezion** [comment]
Dere if you haven't already, can you try using 2.7.0 full release? We've had like 2-3 prs created related to that class since the initial update and I don't currently have any servers running an outdated java version.

**Comment by DereWah** [comment]
> @UnderscoreTud addressed this issue before. Unsure if this was fixed or not. Not home.
> 
> That's why tud was assigned this issue.

I can confirm with Skript 2.7.0 the issue is still happening:

https://mclo.gs/7QI8tqa

**Comment by Moderocky** [comment]
The issue is that the method used for generation `random.nextLong(origin, bound)` used in PRs like #5853 come from the RandomGenerator class, which isn't present in earlier versions of Java, which have only `random.nextLong()` from Random itself.
