### ISSUE TITLE
Ability to center messages easily

### ISSUE THREAD

**Issue by skTanky** [SkriptLang/Skript#5868]
### Suggestion

Make something to all people to center messages in chat easily example:

send "<center>Super cool example text<center>"

Having '<center>' around it would set it to the center of the message

### Why?

Would make it easier for people to center messages instead of having to use multiple spaces to center a message

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment]
In my opinion this is out of scope for Skript, but I'm not 100% against it.
Since players can change their chat width and different fonts change letter width, it's impossible to reliably center chat messages for all players. A syntax to center a message within a certain width is possible, but snippets already exist that will do this and it seems to me something an addon should do, not Skript.

**Comment by AyhamAl-Ali** [comment]
Indeed this is out-of-scope for Skript. Variant options affect this feature such as the ones sovdeeth mentioned (client chat width, custom fonts), you may find Skript/Java snippets online but yet non of them is 100% always accurate therefore adding such thing to Skript is not a good idea.

Thanks for your suggestion \:)
