### ISSUE TITLE
Escaping quotes is required in some places it shouldn't be

### ISSUE THREAD

**Issue by Pikachu920** [SkriptLang/Skript#590]
```
set {%subtext of "test" from characters 1 to 1%} to "value"
```
should work, since there shouldn't be a need to double quotes as the expression isn't inside a string, however quotes still need to be escaped in this scenario.
![](https://i.imgur.com/yD1RSKt.png)
![](https://i.imgur.com/J4Juubc.png)

**Comment by bensku** [comment]
Could you test this with older Skript versions? I can figure out where it comes from quicker if it was introduced by JSON chat.

**Comment by Pikachu920** [comment]
This was on dev25, so it was before json's time

**Comment by TPGamesNL** [comment]
The cause of this issue is is `VariableString.newInstance`, [line 214](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/lang/VariableString.java#L214) and [line 223](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/lang/VariableString.java#L223). Since variable 'strings' (aka `VariableString`s in `StringMode.VARIABLE_NAME`, which is used for all stuff between the `{` and `}`) are the only `StringMode` that isn't actually in quotes, it the double quotes shouldn't be dealt with (the check if it only contains double quotes on line 214 and the replacing double quotes with single quotes on line 223). This can be solved by adding simple conditions on the two lines that check if the type isn't `VARIABLE_NAME` (I tested it, it works).

I do have one concern, which is that it has been 3 and a half years (at least) since this bug has been present, and fixing this could break scripts that rely on this bug. I also don't see a simple way to accept both, as `{_%length of "" and ""%}` has different (valid) interpretations depending on whether the bug is present:
`{_%length of "" and ""%}` -> `{_%length of ("") and ("")%}` -> `{_0 and 0}` when the bug is not present.
`{_%length of "" and ""%}` -> `{_%length of ("" and "")%}` -> `{_5}` when the bug isn't present.
