### ISSUE TITLE
Skript highest priority setting causes Skript commands to be undetected in command event

### ISSUE THREAD

**Issue by not-3than** [SkriptLang/Skript#5908]
### Skript/Server Version

```markdown
[02:39:11 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[02:39:11 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[02:39:11 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[02:39:11 INFO]: [Skript] Server Version: git-Paper-388 (MC: 1.18.2)
[02:39:11 INFO]: [Skript] Skript Version: 2.6.4
[02:39:11 INFO]: [Skript] Installed Skript Addons: 
[02:39:11 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[02:39:11 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[02:39:11 INFO]: [Skript]  - DiSky v4.7.0
[02:39:11 INFO]: [Skript]  - MorkazSk v1.3
[02:39:11 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[02:39:11 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[02:39:11 INFO]: [Skript]  - SkBee v2.16.0 (https://github.com/ShaneBeee/SkBee)
[02:39:11 INFO]: [Skript] Installed dependencies: 
[02:39:11 INFO]: [Skript]  - Vault v1.7.3-b131
[02:39:11 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

Recently I set the plugin priority of Skript to `highest` to see if it could detect WorldGuard blocking `on break:` events, but forgot to switch it back. I have a few scripts (including a combatlog one) that check to see if a player is running a command via `on command:` event. After noticing that it couldn't detect any of my custom teleportation commands, I further investigated and found it couldn't detect any Skript commands at all. It wasn't until I changed my priority back to `high` was I able to see those commands in the command event.

### Expected Behavior

Any and all commands a player runs should fire the `on command:` event, but for some reason in this case with this particular version (haven't tested others), it would not fire for Skript commands (except for /skript + aliases).

### Steps to Reproduce

1) Use Paper 1.18.2 and Skript 2.6.4
2) Set priority to `highest` in config.sk
3) Use `on command:` to detect commands, and try a command created in Skript.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
See this [comment ](https://github.com/SkriptLang/Skript/issues/5891#issuecomment-1669950909)for more info on plugin priorities however, it may not be very related to this specific issue. Other plugins may have cancelled some/all commands in certain situations and with Skript being highest priority makes Skript ignore the cancelled events, this is mostly fixed in #5896

**Comment by sovdeeth** [comment]
After preliminary investigation:
Skript handles commands a bit strangely, due to the necessity of being able to register and deregister on the fly.
Namely, it uses the PlayerPreprocessCommandEvent to listen for its commands, rather than doing the proper registration hullabaloo. It listens to this event on HIGHEST, the latest possible moment it can (and still cancel the event). It checks if the attempted command matches a Skript event, and if so, cancels the event so other plugins don't try to handle it.
However, the `on command` event ALSO listens to PPCE, and if it's at HIGHEST or MONITOR, the event will be cancelled by Skript by the time it gets around to running, leading the to Skript trigger never being called.
I'll look into this further to see if there's any workaround, but I think it may be something we just have to live with.

**Comment by not-3than** [comment]
Alright thank you! It does seem to be quite a hinderance on overall functionality, seeing as how the majority of that event no longer functions. Please let me know if there’s something I can do to fix this!

**Comment by sovdeeth** [comment]
> Alright thank you! It does seem to be quite a hinderance on overall functionality, seeing as how the majority of that event no longer functions. Please let me know if there’s something I can do to fix this!

The only thing you can do is make sure the `on command` event runs at HIGH priority or lower, like `with priority HIGH`.

**Comment by sovdeeth** [comment]
@not-3than Try this nightly jar for 2.7: https://github.com/SkriptLang/Skript/actions/runs/6066909722
I can make you one for 2.6.4 if you can't test on 2.7 for some reason.

**Comment by not-3than** [comment]
I have a live server and try not to use dev versions. If you can make 2.6.4 I can test. This isn’t a huge issue for me, I didn’t end up needing to change priorities in skript config, but I can still test nonetheless.- EthanOn Sep 3, 2023, at 3:12 PM, sovdee ***@***.***> wrote:﻿
@not-3than Try this nightly jar for 2.7: https://github.com/SkriptLang/Skript/actions/runs/6066909722
I can make you one for 2.6.4 if you can't test on 2.7 for some reason.

**Comment by sovdeeth** [comment]
> I have a live server and try not to use dev versions. If you can make 2.6.4 I can test. This isn’t a huge issue for me, I didn’t end up needing to change priorities in skript config, but I can still test nonetheless.- Ethan

This jar should work for 2.6.4
[Skript.zip](https://github.com/SkriptLang/Skript/files/12508065/Skript.zip)

**Comment by sovdeeth** [comment]
This issue currently only exists when listening at HIGHEST or MONITOR for commands that are run by players that do not have the permission to use them. To my knowledge, fixing this completely will require a breaking change to how permission messages are sent (see the above PR for more detail, 6126). 
We'll leave this open until that change is made (2.8?) or some better solution comes along.
