### ISSUE TITLE
Enums / Enumerations

### ISSUE THREAD

**Issue by andriemc** [SkriptLang/Skript#5921]
### Suggestion

Skript currently doesnt have support for enums, which can be kinda useful at times.

Basically lets say you have a list of items, and you want them to be easy to access so something such as `{_enumName}.%itemName%`, it can possibly be defined using `set {_enumName} to (enumeration|enum) [(with|of)] %list%`

### Why?

This can improve ease-of-use for skripters.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Shroobz** [comment]
Agreed, been wanting this for 6 months

**Comment by AyhamAl-Ali** [comment]
This is not English-friendly syntax but can you give a good usage for this?

**Comment by Fusezion** [comment]
I don't see the use in this if going based off `set {_enumName} to (enumeration|enum) [(with|of)] %list%`
it's just a shorter form of 
```
set {_list::DIAMOND} to diamond
set {_list::GOLD_DIAMOND} to gold ingot
set {_list::GREEN_DIAMOND} to emerald
send {_list::GREEN_DIAMOND}
```

**Comment by TheLimeGlass** [comment]
You can already do this with aliases and only enum classinfos that have been registered.
```
on target:
    the target cause is target cause.nether portal
    the target cause is target cause.nether_portal
    the target cause is target cause.NETHER_PORTAL
```

**Comment by Moderocky** [comment]
I'm going to close this because it is incredibly unclear what the suggestion is for, and the issue-maker has not commented to add any more information or to clarify this.
Due to its vagueness this isn't a good issue to be a base for any kind of enum discussion.

If the issue-maker wants to have another go at explaining what they are suggesting we can re-open this issue, or they can make a new one.
