### ISSUE TITLE
Weird error for inventory click events, "this.invi" isn't set?

### ISSUE THREAD

**Issue by not-3than** [SkriptLang/Skript#6011]
### Skript/Server Version

```markdown
https://prnt.sc/pohSFaP4YMm7
```

### Bug Description

Sometimes (can't identify specifically when this happens) there is a long error spewed into the console but I cannot understand why, when, or how it's happening.

### Expected Behavior

No error? The code itself has always worked perfectly fine for me, reloads without error, and I've never noticed anything off about it, but that error shows up in console pretty frequently (due to the code running fairly frequently).

### Steps to Reproduce

```
on inventory click:
    if (1 of event-slot) is nether star named "&3&lDiscernite":
        if event-slot's lore isn't set:
            cancel event
            set event-slot's lore to "&bImportant Currency" and "&f" and "&7Use at /warp Shop" and "&7to get good gear!"
```
Use this code, and wait? I guess? I cannot figure out what causes it, but maybe someone who understands what the error says can help more.

### Errors or Screenshots

https://gist.github.com/not-3than/bc1756ae848d1951392dc3b55c8c1cae

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
I'm unable to replicate this error (Master Branch, SelfBuild), possible issue with using PurPur?

**Comment by not-3than** [comment]
I only recently made the switch to Purpur from Paper, and this happened before using Purpur.

**Comment by Fusezion** [comment]
Have you tried using 2.7?

**Comment by not-3than** [comment]
No, I did install 2.7 on my server but there were a lot of glitches and the server was having slight freezing/stuttering every 1.3ish seconds that I couldn’t immediately find the root cause of.
There were also some events or effects that just didn’t work anymore, and decided it’s best if I report the bugs I run into and wait until 2.7.1 or 2.7.2 when it’s more stable.
My server is live with peak 40-50 players every day, so I can’t leave those kinda of bugs/vulnerabilities alone. I’m not sure if there is any change in code for this particular event from 2.6.4 to 2.7 that would resolve this issue either.

**Comment by Fusezion** [comment]
2.7 only has 2 issues 1. aliases missing 2. `apply potion of ... for ...` only ever doing 15 seconds. 

No events or anything else was changed, skript-reflect is the only known addon to break when upgrading. 
if you don't mind trying this on a fresh build with 2.7 only and this exact code we'll be able to help a bit more

**Comment by Moderocky** [comment]
I am unable to replicate this issue on either the current `2.7.0` release or the outdated `2.6.4` release with what you have provided.

Having investigated, I am fairly confident that some third-party addon (or server installation) is messing with things in a way that breaks an inventory nullability contract.

I would imagine the error might be caused by players clicking an unexpected item in an artificially-created inventory (like a plugin chest menu) but I really can't say without more information, or the script that actually caused the error in your error log.

If you find more information I can reopen this but I'm afraid there is nothing we can do without more information or a way to reliably reproduce the issue.
