### ISSUE TITLE
Setting lore of Inventory Slot expression isn't working

### ISSUE THREAD

**Issue by Blueyescat** [SkriptLang/Skript#624]
`set lore of slot 0 of player to "asd"`
-or-
```
set {_x} to slot 0 of player
set lore of {_x} to "asd"
```

Nothing happens. Tried with dev27 and dev28c

**Comment by TheBentoBox** [comment]
Are you saying your first example doesn't work, or just the 2nd one where you store it in a variable first? If just the 2nd one isn't working, this isn't really an issue, I imagine setting a variable to the slot just stores a copy of the item in the variable, so when you're changing its lore you're changing the variable and not the actual slot.

**Comment by Blueyescat** [comment]
@TheBentoBox Both.

I thought it was me, but this is works:
```
set {_x} to player's tool
set lore of {_x} to "asd"
```

**Comment by TheBentoBox** [comment]
Sorry I never responded to this, didn't see you'd responded yourself. It seems like sometimes it stores the item by reference (`player's tool`) whereas for slots it saves it as a copy, which is why it doesn't work as you'd expect. Not necessarily a bug, but an inconsistency that should probably be fixed to work the same in both situations (regardless of which one is chosen). We'll see what bensku can do.

**Comment by bensku** [comment]
The root cause mighr be deeper. Slot handling isn't exactlty, uhh, stable.

**Comment by Snow-Pyon** [comment]
Could someone confirm if this is still an issue?

**Comment by Blueyescat** [comment]
Hmm very old, but yes, it is sill an issue. There is no any error.

**Comment by Nicofisi** [comment]
Again, *possibly* caused by what I described here https://github.com/SkriptLang/Skript/issues/1287#issuecomment-406381386, but the best way to confirm that would be to, well, fix #1287

**Comment by Nicofisi** [comment]
Nevermind here too, also not related to #1287

**Comment by TPGamesNL** [comment]
I cannot replicate this, this was most likely in https://github.com/SkriptLang/Skript/pull/3860
