### ISSUE TITLE
SkriptSerialiser doing wrong stuff

### ISSUE THREAD

**Issue by Vulcano771** [SkriptLang/Skript#6442]
### Skript/Server Version

```markdown
Skript v. 2.8.2 (latest)
```

### Bug Description

enchantment table gets parsed as visualeffect and it throws an error in console.

### Expected Behavior

enchantment table being parsed as itemtype

### Steps to Reproduce

`set {test::*} to "Enchanter", enchantment table`

### Errors or Screenshots

NaN

### Other

NaN

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
It's because you are making a list of multiple types of objects. It's thinking enchantment table is an temType or Visual effect and you want the other, while you also have a string in the ist? Why? Also the calling code should reparse correctly the literal to be enchantment table of a visual effect if the syntax requires it to be a visual effect and the variable was originally set as enchantment table of itemtype. But since you have a string in there it'll error as you cannot convert string to visual effect without parse as. (edited)
You can also use visual effects within %objects% to collect only the visual effects within the list. Same for any type, if you so desire to be doing this weird multiple type object list.
Send error if you have one, so Skript can make an error explaining this. It could also be because you didn't properly end your list with and. List format is 1,2, 3 and 4
