### ISSUE TITLE
Getting a uuid of a var inside code

### ISSUE THREAD

**Issue by GrimEpp** [SkriptLang/Skript#837]
[![Screenshot from Gyazo](https://gyazo.com/91e79f05c0e788fcfb2a22d1bcaf1b02/raw)](https://gyazo.com/91e79f05c0e788fcfb2a22d1bcaf1b02)

This bug occurs when you try to get add a number to a var with a uuid in a function

**Comment by Blueyescat** [comment]
:white_check_mark: confirmed with 1.12.1 PaperSpigot + Skript dev29:

Can use this: `send "%{_%player's uuid%}%"`
But can't use this: `send "%{_%{_p}'s uuid%}%"`

**Comment by jaylawl** [comment]
Confirming for dev31 / paper 1.12

`set {jaygolf_temp::%{_player}'s uuid%} to {_latest_hole}`

**Comment by Matocolotoe** [comment]
Pretty much happens on every expression that uses a local variable

**Comment by andrei923** [comment]
Still persists

**Comment by TheBentoBox** [comment]
Not sure if the priority can be escalated but I can confirm that this is really annoying. Basically any time you want to pass players into a function and get their UUID you have to break it up into multiple lines because of this exact bug.

**Comment by Runakai1** [comment]
This has been a bug for almost three years now. It's a really annoying bug. Is anything planned to fix this?

**Comment by FranKusmiruk** [comment]
@Runakai1 parser bugs like this are hard to spot, hence why we didn't fix it yet. After we release the next alpha I can take a look at it again and see what's up with this for once and all.

**Comment by TPGamesNL** [comment]
Alright so I've had enough of this bug, so I decided to find the cause of it. Apparently, it's literally just [SkriptParser line 271](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/lang/SkriptParser.java#L271). If you change `((the )?var(iable)? )?\{([^{}]|%\{|\}%)+\}` to `((the )?var(iable)? )?\{.+\}` (replace `[^{}]|%\{|\}%` with `.`), it works just fine. I presume the reason this was added, so people wouldn't try using variables in variables like so: `{var::{_p}}`, but they should've only made it fail on any curly brackets which is not between a pair of `%`, not make it fail on any curly bracket which isn't directly next to a `%`. 

I was going to PR this, but I thought it would be better to first ask if it's important to keep it failing on variables like `{var::{_p}}`. The easist way to fix this is by changing the regex, as said above, but because the regex is only used is in the `parseVariable` method from `SkriptParser`, a simple parser could be made in there to make sure there isn't any weird stuff going on.
