### ISSUE TITLE
Power not working in half

### ISSUE THREAD

**Issue by knugi** [SkriptLang/Skript#852]
Hi, my problem is bow. It enchantment power is served for potion type. In send loop value give me "strength" then if I change power to strength in my variable then problem not resolved.
I not have question to this problem then i turn to you because it is Skript problem. 

Below is my short code with problem.
```
on script load:
	set {bow::*} to power, unbreaking, flame, infinity and punch

#...
loop {bow::*}:
	send "%loop-value%"
	set {_max} to getMaxEnchantment(loop-value) #Function that return integer max enchantment for enchantment
	set {_slot} to loop-index parsed as integer - 1
	loop {_max} times:
		set {_book} to "enchanted book of %loop-value-1% %loop-number%" parsed as item type
		set player's current inventory's slot {_slot} to {_book}
		add 9 to {_slot}
```
but this code is work :)
```
command /s:
	trigger:
		give bow of power 5 to player
```

Spigot 1.12
Skript 2.2-dev31b

**Comment by bensku** [comment]
Parse error ot it just doesn't work?

**Comment by knugi** [comment]
@Pikachu920, i can use parse from text to item type. It's work. With all enchatment this code it's work, but in power not :?

**Comment by TheBentoBox** [comment]
I've found the issue; if you check the [lang file](https://github.com/bensku/Skript/blob/master/src/main/resources/lang/english.lang) you'll see that the aliases for the strength potion effect are declared as follows:

```
increase_damage: strength, power, increase damage, increased damage
```

Because of this, when writing just `power` as an expression to try to store the enchantment type, it instead parses as the potion effect type since it's an alias for strength. Recommended fix is simply removing `power` from the list of `increase_damage` aliases as it should never be referred to that since it conflicts with a vanilla enchantment type.
