### ISSUE TITLE
Default converter from string to world doesn't seem to work

### ISSUE THREAD

**Issue by MinecraftAdmin** [SkriptLang/Skript#853]
One of my Skripts fail to run on Dev 31b. These worked pre-dev31b.

- [ ] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: teleport player 2.6 blocks above {_loc}
- [ ] [Server thread/ERROR]: [Skript] can't understand this event: 'on vote'
- [ ] [Server thread/ERROR]: [Skript] Can't understand this loop: 'loop all items in player's inventory'
- [ ] [Server thread/ERROR]: [Skript] Can't understand this loop: 'loop all players in "elytrafall"'
- [ ] [Server thread/ERROR]: [Skript] Can't compare an entity with 'in world "60_jumps"' (parkour.sk, line 237: victim is in world "60_jumps":')
- [ ] [Server thread/ERROR]: [Skript] loop-player is not a world (parkour.sk, line 993: block 1 blocks below loop-player is orange stained clay:')
- [ ] [Server thread/ERROR]: [Skript] the clicked block is not a world (parkour.sk, line 1286: loop items in clicked block:')
- [ ] [Server thread/ERROR]: [Skript] Can't compare 'block 1 blocks below player' with an item type (parkour.sk, line 1373: block 1 blocks below player is gold block:')

**Comment by Snow-Pyon** [comment]
1, 6 and 8. Try using `meters` instead of `blocks` or just remove it. Someone had a similar issue in #828 and using `meters` fixed it. Although using `blocks` should be fine as what I can see on the pattern of the [direction expression; ](http://bensku.github.io/Skript/expressions.html#ExprDirection)this might be another parser bug? @bensku.
2. The `on vote` event is of skRayFall, not related to Skript. You can try updating to the latest release anyways.
3 and 7. The `items in` expression is broken due to a parser bug as far I've heard. This has been reported in #841.
4 and 5. That's supposed to be a world and not a string input, but there is a converter string -> world if my memory serves me right, did it broke?

**Comment by TheBentoBox** [comment]
As @Snow-Pyon said the only thing here that's really valid is the fact that the `in world %text%` converter doesn't seem to be working. I guess that's enough to leave this open, though.

**Comment by TheBentoBox** [comment]
Is this still an issue?

**Comment by TheLimeGlass** [comment]
no `loop all players in world "elytrafall":` should be used.

**Comment by Blueyescat** [comment]
The word **`world`** doesn't change anything in this case, it errors because the world isn't loaded ^^

**Comment by TheLimeGlass** [comment]
So then it's a different error that I already elaborated alot on. #duplicate.
