### ISSUE TITLE
2.3 release notes

### ISSUE THREAD

**Issue by bensku** [SkriptLang/Skript#878]
Whenever 2.3 comes out, it would be great to have all changes since 2.2 collected to a single list. Creating such a list would be very time consuming, though.

**Comment by TheBentoBox** [comment]
I could try to work on this soon; I imagine the best way to do this would be to scour the docs for all changes listed as being added since release-2.2 followed by going through all of this fork's releases to see anything that might've been missed (such as important bug fixes that wouldn't be listed in the docs).

**Comment by Syst3ms** [comment]
The Google doc is up at http://bit.ly/2xQgG6o. I added some notes as well as TODO. Feel free to modify them if you want to.

**Comment by bensku** [comment]
@Syst3ms Probably going to release 2.3 on Spigot, but I'm not going to announce it before it is *almost* ready. Starting a flame war on Spigot forums is not my intention :)

**Comment by Syst3ms** [comment]
You start a flame war on spigot as soon as you say anything Skript-related anyway :stuck_out_tongue:. God is this community cancerous.
