### ISSUE TITLE
on break event for item frames and paintings and more

### ISSUE THREAD

**Issue by Spiralexe** [SkriptLang/Skript#892]
using the **on break:** event 
and breaking an item frame triggers the event but player isn't set
same goes for paintings

and event-block / event-item are both not set either

mc 1.12.1
skript 2.2-dev29

**Comment by JeepSmash** [comment]
Item frames and paintings should not use on break events since they are entities and not blocks.  They are covered by the on damage event.  Regarding item frames: On right click events are not called if players click on item frames making it impossible to stop players from placing items in empty frames or rotating the items in frames. This was reported 10 months ago and hasn't been fixed #290 
```
on damage of item frame:

on damage of painting:
```

**Comment by TheBentoBox** [comment]
Yeah, you shouldn't be using `on break`, but hanging entities probably shouldn't fire break events so that people can't make this mistake (possibly with an error message telling them to use `on damage`).

**Comment by Syst3ms** [comment]
Using `on break:` with an hanging entity only works because they have aliases for their corresponding items. What would be more efficient would be to error when using an alias of an item and implement an error specific to hanging entities on the fly.

**Comment by JeepSmash** [comment]
After doing some  more testing with this stuff regarding item frames and paintings:

1 'on break' is called when a item frame/painting breaks
   a The only thing set is event-entity
   b event-entity is set to the item frame/painting entity instead of the player breaking it
3 'on damage of item frame' is only called when an item is in the frame and not when it is empty and breaking
4 'on damage of painting' is never called
5 when a player left clicks to break empty item frame/painting there is no 'on click' event called
6 No click event is called when a player right clicks an item frame with an item in it (rotating it)

If trying to detect players breaking an item frame the only thing i can think of is using the on 'break event' and looping the players in a 5 block radius around the event-entity (the max distance a player can hit an entity from with their hands).  But if multiple players are in that radius there is no way to know which unless you check their targeted entity/block but if they are causing the damage from a farther distance with a projectile/piston/liquid/etc there is no 100% sure way to tell until something here is fixed.  It would be nice if both 'on break' and 'on damage' events were called for the case of the item frame and painting so players could use which ever meets their needs best.  But at this point at least one is needed to be able to detect a player breaking those entities properly.

**Comment by Matocolotoe** [comment]
the only way to prevent this is to use HangingBreakEvent and/or HangingBreakByEntityEvent

**Comment by SwagPancakes** [comment]
Still having the issue today with the latest version

**Comment by SwagPancakes** [comment]
I fixed it by using BlockBreakEvent instead of "break"
and used event.getPlayer() instead of "event-player" or "player" and event.getBlock()
skript-mirror
