### ISSUE TITLE
Checking if  a player has an item (item as variable)

### ISSUE THREAD

**Issue by StealWonders** [SkriptLang/Skript#999]
This code no longer works with dev32b
`player's inventory doesn't contain 16 of {arrow.poison}
			give 1 of {arrow.poison} to player`
It used to allow me to check if a player has a poisonarrow (they aren't in aliases yet).

**Comment by hazycraft** [comment]
@StealWonders for the time being you can use still check for tipped arrows and use command like /give @p minecraft:tipped_arrow 1 0 {Potion:"minecraft:poison"} to give poison arrows.

**Comment by Syst3ms** [comment]
Or you could use [QuarSK](/Syst3ms/QuarSK/wiki/Documentation)

**Comment by bensku** [comment]
I'm not really sure why it would have worked even before. What exactly does arrow.poison variable contain?

**Comment by bensku** [comment]
Not accurate enough. What code sets it?

**Comment by StealWonders** [comment]
set {arrow.%arg%} to player's tool 
or something similar

**Comment by bensku** [comment]
Hm, that should not be causing any problems.

**Comment by TPGamesNL** [comment]
2.6-alpha1
```
command /test:
	trigger:
		if player's inventory contains 16 of {item}:
			message "yes contain"
		else:
			message "no contain"
```
`set {item} to tool of me` when holding 1 stone
conditions returns true only if there is an exact item stack of 16 stone in the inventory, if the item amount is 17, is returns false.

`CondContains` uses `ItemType#isContainedIn` for `ItemType`s, but `Inventory#contains` for `ItemStack`. The latter does not check item amounts like the first method does.

Possibly related to https://github.com/SkriptLang/Skript/issues/3814, but this might be fixed by having `ExprXOf` accept itemtype
